// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 GitStore contributors

// gRPC service implementation for the GitService contract (gitstore.git.v1).

use std::path::PathBuf;
use std::sync::Arc;
use tokio::sync::RwLock;
use tonic::{Request, Response, Status};

use crate::git::repo::{init_or_open_repository, list_tags};

// Generated by tonic-build (build.rs) from shared/proto/gitstore/git/v1/git_service.proto
pub mod proto {
    tonic::include_proto!("gitstore.git.v1");
}

use proto::git_service_server::GitService;
use proto::*;

pub struct GitServiceImpl {
    pub repo_path: Arc<PathBuf>,
    /// Write lock ensures serialised mutations; reads are lock-free (bare repo).
    pub write_lock: Arc<RwLock<()>>,
}

impl GitServiceImpl {
    pub fn new(repo_path: PathBuf) -> Self {
        Self {
            repo_path: Arc::new(repo_path),
            write_lock: Arc::new(RwLock::new(())),
        }
    }
}

// --- helpers -----------------------------------------------------------------

/// Resolve a ref (tag, branch, commit SHA, or "HEAD") to a git2::Commit.
fn resolve_ref_to_commit<'repo>(
    repo: &'repo git2::Repository,
    ref_str: &str,
) -> Result<git2::Commit<'repo>, Status> {
    let obj = repo
        .revparse_single(ref_str)
        .map_err(|e| Status::not_found(format!("ref '{}' not found: {}", ref_str, e)))?;

    obj.peel_to_commit()
        .map_err(|e| Status::internal(format!("failed to peel ref '{}' to commit: {}", ref_str, e)))
}

/// Walk the tree rooted at `commit` and collect all blobs under `prefix`.
fn list_tree_files(
    _repo: &git2::Repository,
    commit: &git2::Commit<'_>,
    prefix: &str,
) -> Result<Vec<FileEntry>, Status> {
    let tree = commit
        .tree()
        .map_err(|e| Status::internal(format!("failed to get tree: {}", e)))?;

    let mut files: Vec<FileEntry> = Vec::new();

    tree.walk(git2::TreeWalkMode::PreOrder, |dir, entry| {
        if entry.kind() != Some(git2::ObjectType::Blob) {
            return git2::TreeWalkResult::Ok;
        }
        let full_path = if dir.is_empty() {
            entry.name().unwrap_or("").to_string()
        } else {
            format!("{}{}", dir, entry.name().unwrap_or(""))
        };

        if prefix.is_empty() || full_path.starts_with(prefix) {
            files.push(FileEntry {
                path: full_path,
                size_bytes: 0, // filled lazily below if needed
                blob_sha: entry.id().to_string(),
            });
        }
        git2::TreeWalkResult::Ok
    })
    .map_err(|e| Status::internal(format!("tree walk error: {}", e)))?;

    Ok(files)
}

// --- RPC implementations -----------------------------------------------------

#[tonic::async_trait]
impl GitService for GitServiceImpl {
    async fn get_file(
        &self,
        request: Request<GetFileRequest>,
    ) -> Result<Response<GetFileResponse>, Status> {
        let req = request.into_inner();
        let repo_path = Arc::clone(&self.repo_path);

        tokio::task::spawn_blocking(move || {
            let repo = init_or_open_repository(&repo_path)
                .map_err(|e| Status::internal(format!("failed to open repo: {}", e)))?;

            let ref_str = if req.r#ref.is_empty() { "HEAD".to_string() } else { req.r#ref.clone() };
            let commit = resolve_ref_to_commit(&repo, &ref_str)?;

            let tree = commit
                .tree()
                .map_err(|e| Status::internal(format!("failed to get tree: {}", e)))?;

            let entry = tree
                .get_path(std::path::Path::new(&req.path))
                .map_err(|_| Status::not_found(format!("file '{}' not found at ref '{}'", req.path, ref_str)))?;

            let blob = repo
                .find_blob(entry.id())
                .map_err(|e| Status::internal(format!("failed to find blob: {}", e)))?;

            let content = blob.content().to_vec();
            let size_bytes = content.len() as u64;
            let blob_sha = entry.id().to_string();

            Ok(Response::new(GetFileResponse {
                path: req.path,
                content,
                blob_sha,
                size_bytes,
            }))
        })
        .await
        .map_err(|e| Status::internal(format!("task join error: {}", e)))?
    }

    type GetFileStreamStream = tokio_stream::wrappers::ReceiverStream<Result<FileChunk, Status>>;

    async fn get_file_stream(
        &self,
        request: Request<GetFileRequest>,
    ) -> Result<Response<Self::GetFileStreamStream>, Status> {
        let req = request.into_inner();
        let repo_path = Arc::clone(&self.repo_path);

        let (tx, rx) = tokio::sync::mpsc::channel(16);

        tokio::task::spawn_blocking(move || {
            let send = |chunk: Result<FileChunk, Status>| {
                // ignore send errors — client disconnected
                let _ = tx.blocking_send(chunk);
            };

            let repo = match init_or_open_repository(&repo_path) {
                Ok(r) => r,
                Err(e) => {
                    send(Err(Status::internal(format!("failed to open repo: {}", e))));
                    return;
                }
            };

            let ref_str = if req.r#ref.is_empty() { "HEAD".to_string() } else { req.r#ref.clone() };
            let commit = match resolve_ref_to_commit(&repo, &ref_str) {
                Ok(c) => c,
                Err(e) => { send(Err(e)); return; }
            };

            let tree = match commit.tree() {
                Ok(t) => t,
                Err(e) => { send(Err(Status::internal(format!("tree: {}", e)))); return; }
            };

            let entry = match tree.get_path(std::path::Path::new(&req.path)) {
                Ok(e) => e,
                Err(_) => {
                    send(Err(Status::not_found(format!("file '{}' not found", req.path))));
                    return;
                }
            };

            let blob = match repo.find_blob(entry.id()) {
                Ok(b) => b,
                Err(e) => { send(Err(Status::internal(format!("blob: {}", e)))); return; }
            };

            const CHUNK: usize = 256 * 1024; // 256 KiB
            let content = blob.content();
            let chunks: Vec<&[u8]> = content.chunks(CHUNK).collect();
            let last = chunks.len().saturating_sub(1);
            for (i, chunk) in chunks.into_iter().enumerate() {
                send(Ok(FileChunk {
                    data: chunk.to_vec(),
                    chunk_index: i as u32,
                    is_last: i == last,
                }));
            }
        });

        Ok(Response::new(tokio_stream::wrappers::ReceiverStream::new(rx)))
    }

    async fn list_files(
        &self,
        request: Request<ListFilesRequest>,
    ) -> Result<Response<ListFilesResponse>, Status> {
        let req = request.into_inner();
        let repo_path = Arc::clone(&self.repo_path);

        tokio::task::spawn_blocking(move || {
            let repo = init_or_open_repository(&repo_path)
                .map_err(|e| Status::internal(format!("failed to open repo: {}", e)))?;

            let ref_str = if req.r#ref.is_empty() { "HEAD".to_string() } else { req.r#ref.clone() };
            let commit = resolve_ref_to_commit(&repo, &ref_str)?;
            let ref_commit_sha = commit.id().to_string();

            let files = list_tree_files(&repo, &commit, &req.path_prefix)?;

            Ok(Response::new(ListFilesResponse {
                files,
                ref_commit_sha,
            }))
        })
        .await
        .map_err(|e| Status::internal(format!("task join error: {}", e)))?
    }

    async fn commit_file(
        &self,
        _request: Request<CommitFileRequest>,
    ) -> Result<Response<CommitFileResponse>, Status> {
        Err(Status::unimplemented("CommitFile not yet implemented"))
    }

    async fn delete_file(
        &self,
        _request: Request<DeleteFileRequest>,
    ) -> Result<Response<DeleteFileResponse>, Status> {
        Err(Status::unimplemented("DeleteFile not yet implemented"))
    }

    async fn create_tag(
        &self,
        _request: Request<CreateTagRequest>,
    ) -> Result<Response<CreateTagResponse>, Status> {
        Err(Status::unimplemented("CreateTag not yet implemented"))
    }

    async fn list_tags(
        &self,
        request: Request<ListTagsRequest>,
    ) -> Result<Response<ListTagsResponse>, Status> {
        let req = request.into_inner();
        let repo_path = Arc::clone(&self.repo_path);

        tokio::task::spawn_blocking(move || {
            let repo = init_or_open_repository(&repo_path)
                .map_err(|e| Status::internal(format!("failed to open repo: {}", e)))?;

            let all_tags = list_tags(&repo)
                .map_err(|e| Status::internal(format!("failed to list tags: {}", e)))?;

            let tags: Vec<TagEntry> = all_tags
                .into_iter()
                .filter(|t| req.prefix.is_empty() || t.starts_with(&req.prefix))
                .filter_map(|name| {
                    let commit_sha = crate::git::repo::get_tag_commit(&repo, &name).ok()?;
                    let message = get_tag_message(&repo, &name).unwrap_or_default();
                    Some(TagEntry { name, commit_sha, message })
                })
                .collect();

            Ok(Response::new(ListTagsResponse { tags }))
        })
        .await
        .map_err(|e| Status::internal(format!("task join error: {}", e)))?
    }

    async fn get_latest_tag(
        &self,
        request: Request<GetLatestTagRequest>,
    ) -> Result<Response<GetLatestTagResponse>, Status> {
        let req = request.into_inner();
        let repo_path = Arc::clone(&self.repo_path);

        tokio::task::spawn_blocking(move || {
            let repo = init_or_open_repository(&repo_path)
                .map_err(|e| Status::internal(format!("failed to open repo: {}", e)))?;

            let all_tags = list_tags(&repo)
                .map_err(|e| Status::internal(format!("failed to list tags: {}", e)))?;

            let prefix = if req.prefix.is_empty() { "v" } else { &req.prefix };

            let mut release_tags: Vec<String> = all_tags
                .into_iter()
                .filter(|t| t.starts_with(prefix))
                .collect();

            if release_tags.is_empty() {
                return Ok(Response::new(GetLatestTagResponse {
                    tag: None,
                    found: false,
                }));
            }

            // Semver sort: parse with semver crate is optional; string sort suffices for
            // well-formed v<major>.<minor>.<patch> tags used in this project.
            release_tags.sort_by(|a, b| {
                let av = a.trim_start_matches(prefix);
                let bv = b.trim_start_matches(prefix);
                cmp_semver_str(av, bv)
            });

            let latest_name = release_tags.last().unwrap();
            let commit_sha = crate::git::repo::get_tag_commit(&repo, latest_name)
                .map_err(|e| Status::internal(format!("failed to get tag commit: {}", e)))?;
            let message = get_tag_message(&repo, latest_name).unwrap_or_default();

            Ok(Response::new(GetLatestTagResponse {
                tag: Some(TagEntry {
                    name: latest_name.clone(),
                    commit_sha,
                    message,
                }),
                found: true,
            }))
        })
        .await
        .map_err(|e| Status::internal(format!("task join error: {}", e)))?
    }
}

/// Compare two semver version strings (e.g. "1.2.3" vs "1.10.0").
fn cmp_semver_str(a: &str, b: &str) -> std::cmp::Ordering {
    let parse = |s: &str| -> (u64, u64, u64) {
        let mut parts = s.splitn(3, '.').map(|p| p.parse::<u64>().unwrap_or(0));
        (
            parts.next().unwrap_or(0),
            parts.next().unwrap_or(0),
            parts.next().unwrap_or(0),
        )
    };
    parse(a).cmp(&parse(b))
}

/// Returns the annotated tag message, or empty string for lightweight tags.
fn get_tag_message(repo: &git2::Repository, tag_name: &str) -> Option<String> {
    let reference = repo.find_reference(&format!("refs/tags/{}", tag_name)).ok()?;
    let tag = reference.peel_to_tag().ok()?;
    tag.message().map(|s| s.to_string())
}

/// Verify the repo is accessible at startup; returns error if not.
pub fn verify_repo(repo_path: &PathBuf) -> anyhow::Result<()> {
    init_or_open_repository(repo_path)?;
    Ok(())
}

// ---------------------------------------------------------------------------
#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn make_test_service(repo_path: &std::path::Path) -> GitServiceImpl {
        GitServiceImpl::new(repo_path.to_path_buf())
    }

    /// Create a bare repo with one commit containing `products/p1.md`.
    fn repo_with_commit(dir: &std::path::Path) {
        let repo = git2::Repository::init_bare(dir).unwrap();

        let content = b"---\nid: p1\n---\nhello";
        let blob_oid = repo.blob(content).unwrap();

        let sub_tree_oid = {
            let mut b = repo.treebuilder(None).unwrap();
            b.insert("p1.md", blob_oid, 0o100644).unwrap();
            b.write().unwrap()
        };

        let root_tree_oid = {
            let mut b = repo.treebuilder(None).unwrap();
            b.insert("products", sub_tree_oid, 0o040000).unwrap();
            b.write().unwrap()
        };

        let root_tree = repo.find_tree(root_tree_oid).unwrap();
        let sig = git2::Signature::now("test", "test@example.com").unwrap();
        let commit_oid = repo.commit(Some("HEAD"), &sig, &sig, "init", &root_tree, &[]).unwrap();
        drop(root_tree);

        let commit = repo.find_commit(commit_oid).unwrap();
        let obj = commit.as_object();
        repo.tag("v1.0.0", obj, &sig, "release v1.0.0", false).unwrap();
    }

    #[tokio::test]
    async fn test_get_file_happy_path() {
        let dir = TempDir::new().unwrap();
        repo_with_commit(dir.path());

        let svc = make_test_service(dir.path());
        let req = Request::new(GetFileRequest {
            path: "products/p1.md".to_string(),
            r#ref: "HEAD".to_string(),
        });
        let resp = svc.get_file(req).await.unwrap();
        assert_eq!(resp.into_inner().content, b"---\nid: p1\n---\nhello");
    }

    #[tokio::test]
    async fn test_get_file_unknown_ref_returns_not_found() {
        let dir = TempDir::new().unwrap();
        repo_with_commit(dir.path());

        let svc = make_test_service(dir.path());
        let req = Request::new(GetFileRequest {
            path: "products/p1.md".to_string(),
            r#ref: "nonexistent-branch".to_string(),
        });
        let err = svc.get_file(req).await.unwrap_err();
        assert_eq!(err.code(), tonic::Code::NotFound);
    }

    #[tokio::test]
    async fn test_get_file_missing_file_returns_not_found() {
        let dir = TempDir::new().unwrap();
        repo_with_commit(dir.path());

        let svc = make_test_service(dir.path());
        let req = Request::new(GetFileRequest {
            path: "products/nonexistent.md".to_string(),
            r#ref: "HEAD".to_string(),
        });
        let err = svc.get_file(req).await.unwrap_err();
        assert_eq!(err.code(), tonic::Code::NotFound);
    }

    #[tokio::test]
    async fn test_list_files_returns_tree_entries() {
        let dir = TempDir::new().unwrap();
        repo_with_commit(dir.path());

        let svc = make_test_service(dir.path());
        let req = Request::new(ListFilesRequest {
            r#ref: "HEAD".to_string(),
            path_prefix: "products/".to_string(),
            recursive: true,
        });
        let resp = svc.list_files(req).await.unwrap();
        let files = resp.into_inner().files;
        assert_eq!(files.len(), 1);
        assert_eq!(files[0].path, "products/p1.md");
    }

    #[tokio::test]
    async fn test_get_latest_tag_returns_correct_tag() {
        let dir = TempDir::new().unwrap();
        repo_with_commit(dir.path());

        let svc = make_test_service(dir.path());
        let req = Request::new(GetLatestTagRequest { prefix: "v".to_string() });
        let resp = svc.get_latest_tag(req).await.unwrap().into_inner();

        assert!(resp.found);
        let tag = resp.tag.unwrap();
        assert_eq!(tag.name, "v1.0.0");
        assert!(!tag.commit_sha.is_empty());
    }

    #[tokio::test]
    async fn test_get_latest_tag_empty_repo_returns_found_false() {
        let dir = TempDir::new().unwrap();
        git2::Repository::init_bare(dir.path()).unwrap();

        let svc = make_test_service(dir.path());
        let req = Request::new(GetLatestTagRequest { prefix: "v".to_string() });
        let resp = svc.get_latest_tag(req).await.unwrap().into_inner();

        assert!(!resp.found);
        assert!(resp.tag.is_none());
    }

    #[test]
    fn test_cmp_semver_str() {
        use std::cmp::Ordering::*;
        assert_eq!(cmp_semver_str("1.0.0", "1.0.0"), Equal);
        assert_eq!(cmp_semver_str("1.0.0", "1.10.0"), Less);
        assert_eq!(cmp_semver_str("2.0.0", "1.9.9"), Greater);
        assert_eq!(cmp_semver_str("1.2.3", "1.2.10"), Less);
    }
}
