// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/gitstore-dev/gitstore/api/internal/graph/scalar"
)

// An object with a globally unique ID
type Node interface {
	IsNode()
	// Globally unique identifier (format: [type]_[base62])
	GetID() string
}

// Authentication session response
type AuthSession struct {
	// JWT token for authentication
	Token string `json:"token"`
	// Token expiration time (ISO 8601)
	ExpiresAt time.Time `json:"expiresAt"`
	// Authenticated user information
	User *User `json:"user"`
}

// Catalog statistics
type CatalogStats struct {
	// Total products
	ProductCount int32 `json:"productCount"`
	// Total categories
	CategoryCount int32 `json:"categoryCount"`
	// Total collections
	CollectionCount int32 `json:"collectionCount"`
	// Number of orphaned product references
	OrphanedReferences int32 `json:"orphanedReferences"`
}

// Catalog version information
type CatalogVersion struct {
	// Version tag (e.g., v1.0.0)
	Tag string `json:"tag"`
	// Commit SHA
	Commit string `json:"commit"`
	// Release timestamp
	PublishedAt time.Time `json:"publishedAt"`
	// Release message
	Message *string `json:"message,omitempty"`
	// Statistics
	Stats *CatalogStats `json:"stats"`
}

// Category represents a hierarchical classification system for products
type Category struct {
	// Globally unique identifier (format: cat_[base62])
	ID string `json:"id"`
	// Category display name
	Name string `json:"name"`
	// URL-friendly slug (unique)
	Slug string `json:"slug"`
	// Parent category (null for root categories)
	Parent *Category `json:"parent,omitempty"`
	// Child categories (subcategories)
	Children []*Category `json:"children"`
	// Display order within parent
	DisplayOrder int32 `json:"displayOrder"`
	// Products in this category (includes subcategory products)
	Products *ProductConnection `json:"products"`
	// Markdown body content (category description with rich formatting)
	Body *string `json:"body,omitempty"`
	// Creation timestamp
	CreatedAt time.Time `json:"createdAt"`
	// Last modification timestamp
	UpdatedAt time.Time `json:"updatedAt"`
	// Full path from root (e.g., ["Electronics", "Computers", "Laptops"])
	Path []string `json:"path"`
	// Depth in tree (root = 0)
	Depth int32 `json:"depth"`
}

func (Category) IsNode() {}

// Globally unique identifier (format: [type]_[base62])
func (this Category) GetID() string { return this.ID }

// Optimistic lock conflict for category
type CategoryOptimisticLockConflict struct {
	// Current version in database
	CurrentVersion time.Time `json:"currentVersion"`
	// Version client attempted to update
	AttemptedVersion time.Time `json:"attemptedVersion"`
	// Current state of the category
	Current *Category `json:"current"`
	// Diff between current and attempted
	Diff string `json:"diff"`
}

// Collection represents a curated grouping of products (flat, non-hierarchical)
type Collection struct {
	// Globally unique identifier (format: coll_[base62])
	ID string `json:"id"`
	// Collection display name
	Name string `json:"name"`
	// URL-friendly slug (unique)
	Slug string `json:"slug"`
	// Display order for collection listing
	DisplayOrder int32 `json:"displayOrder"`
	// Products in this collection
	Products *ProductConnection `json:"products"`
	// Markdown body content (collection description with rich formatting)
	Body *string `json:"body,omitempty"`
	// Creation timestamp
	CreatedAt time.Time `json:"createdAt"`
	// Last modification timestamp
	UpdatedAt time.Time `json:"updatedAt"`
	// Number of products in this collection
	ProductCount int32 `json:"productCount"`
}

func (Collection) IsNode() {}

// Globally unique identifier (format: [type]_[base62])
func (this Collection) GetID() string { return this.ID }

// Optimistic lock conflict for collection
type CollectionOptimisticLockConflict struct {
	// Current version in database
	CurrentVersion time.Time `json:"currentVersion"`
	// Version client attempted to update
	AttemptedVersion time.Time `json:"attemptedVersion"`
	// Current state of the collection
	Current *Collection `json:"current"`
	// Diff between current and attempted
	Diff string `json:"diff"`
}

// Input for creating a category
type CreateCategoryInput struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Category name
	Name string `json:"name"`
	// URL-friendly slug (must be unique)
	Slug string `json:"slug"`
	// Parent category ID (null for root)
	ParentID *string `json:"parentId,omitempty"`
	// Display order
	DisplayOrder *int32 `json:"displayOrder,omitempty"`
	// Markdown body content
	Body *string `json:"body,omitempty"`
}

// Payload for createCategory mutation
type CreateCategoryPayload struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// The created category
	Category *Category `json:"category,omitempty"`
}

// Input for creating a collection
type CreateCollectionInput struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Collection name
	Name string `json:"name"`
	// URL-friendly slug (must be unique)
	Slug string `json:"slug"`
	// Display order
	DisplayOrder *int32 `json:"displayOrder,omitempty"`
	// Product IDs to include
	ProductIds []string `json:"productIds,omitempty"`
	// Markdown body content
	Body *string `json:"body,omitempty"`
}

// Payload for createCollection mutation
type CreateCollectionPayload struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// The created collection
	Collection *Collection `json:"collection,omitempty"`
}

// Input for creating a new namespace.
type CreateNamespaceInput struct {
	// The human-readable identifier for the namespace.
	// Must be globally unique across all tiers.
	// DNS label format: lowercase alphanumeric and hyphens, 1–63 characters.
	// Cannot begin or end with a hyphen. Cannot be a reserved name.
	Identifier string `json:"identifier"`
	// Optional human-friendly display name.
	DisplayName *string `json:"displayName,omitempty"`
	// The tier of the namespace being created.
	// USER and ORGANISATION tiers may be created by any authenticated user.
	// ENTERPRISE tier requires isAdmin == true in the caller's JWT.
	Tier NamespaceTier `json:"tier"`
	// For ORGANISATION tier only: the identifier of the parent enterprise namespace.
	// The referenced namespace must exist and have tier ENTERPRISE.
	// Omit for USER and ENTERPRISE tier namespaces.
	ParentEnterpriseIdentifier *string `json:"parentEnterpriseIdentifier,omitempty"`
}

// Payload returned after successfully creating a namespace.
type CreateNamespacePayload struct {
	// The newly created namespace.
	Namespace *Namespace `json:"namespace"`
}

// Input for creating a product
type CreateProductInput struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Stock Keeping Unit (must be unique)
	Sku string `json:"sku"`
	// Product display name
	Title string `json:"title"`
	// Markdown body content (product description)
	Body *string `json:"body,omitempty"`
	// Product price
	Price scalar.Decimal `json:"price"`
	// Currency code (default: USD)
	Currency *string `json:"currency,omitempty"`
	// Inventory status (default: IN_STOCK)
	InventoryStatus *InventoryStatus `json:"inventoryStatus,omitempty"`
	// Available quantity
	InventoryQuantity *int32 `json:"inventoryQuantity,omitempty"`
	// Primary category ID (required)
	CategoryID string `json:"categoryId"`
	// Collection IDs (optional)
	CollectionIds []string `json:"collectionIds,omitempty"`
	// Product image URLs
	Images []string `json:"images,omitempty"`
	// Custom metadata
	Metadata map[string]any `json:"metadata,omitempty"`
}

// Payload for createProduct mutation
type CreateProductPayload struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// The created product
	Product *Product `json:"product,omitempty"`
}

// Input for deleting a category
type DeleteCategoryInput struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Category ID to delete
	ID string `json:"id"`
}

// Payload for deleteCategory mutation
type DeleteCategoryPayload struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Deleted category ID
	DeletedCategoryID *string `json:"deletedCategoryId,omitempty"`
	// Orphaned product IDs (products that referenced this category)
	OrphanedProductIds []string `json:"orphanedProductIds,omitempty"`
}

// Input for deleting a collection
type DeleteCollectionInput struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Collection ID to delete
	ID string `json:"id"`
}

// Payload for deleteCollection mutation
type DeleteCollectionPayload struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Deleted collection ID
	DeletedCollectionID *string `json:"deletedCollectionId,omitempty"`
}

// Input for deleting a namespace.
type DeleteNamespaceInput struct {
	// The identifier of the namespace to delete.
	// Deletion is blocked if any repositories exist within the namespace.
	// Requires the caller to be the namespace owner (createdBy) or isAdmin.
	Identifier string `json:"identifier"`
}

// Payload returned after successfully deleting a namespace.
type DeleteNamespacePayload struct {
	// The identifier of the deleted namespace.
	DeletedIdentifier string `json:"deletedIdentifier"`
}

// Input for deleting a product
type DeleteProductInput struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Product ID to delete
	ID string `json:"id"`
}

// Payload for deleteProduct mutation
type DeleteProductPayload struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Deleted product ID
	DeletedProductID *string `json:"deletedProductId,omitempty"`
}

// Login mutation input (Relay pattern)
type LoginInput struct {
	// Client mutation ID for request tracking (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Username
	Username string `json:"username"`
	// Password
	Password string `json:"password"`
}

// Login mutation payload (Relay pattern)
type LoginPayload struct {
	// Client mutation ID for request tracking (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Authentication session (token + user info)
	Session *AuthSession `json:"session,omitempty"`
}

// Logout mutation input (Relay pattern)
type LogoutInput struct {
	// Client mutation ID for request tracking (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

// Logout mutation payload (Relay pattern)
type LogoutPayload struct {
	// Client mutation ID for request tracking (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Success indicator
	Success bool `json:"success"`
}

type Mutation struct {
}

// A namespace is the primary isolation boundary for repositories in GitStore.
// Namespaces are globally unique across all tiers — the same identifier cannot
// exist as both a user-space and an organisation namespace.
type Namespace struct {
	// Globally unique system-generated ID (UUID).
	ID string `json:"id"`
	// Human-readable identifier, globally unique across all tiers.
	// DNS label format: lowercase alphanumeric and hyphens, 1–63 characters.
	// Cannot begin or end with a hyphen.
	Identifier string `json:"identifier"`
	// Optional human-friendly display name.
	DisplayName *string `json:"displayName,omitempty"`
	// The tier of this namespace.
	Tier NamespaceTier `json:"tier"`
	// For ORGANISATION tier namespaces: the ID of the parent enterprise namespace,
	// if one was declared at creation time.
	// Null for USER and ENTERPRISE tier namespaces.
	ParentEnterpriseID *string `json:"parentEnterpriseId,omitempty"`
	// Timestamp when this namespace was created.
	CreatedAt time.Time `json:"createdAt"`
	// Username of the caller who created this namespace.
	CreatedBy string `json:"createdBy"`
	// Timestamp when this namespace was last modified.
	UpdatedAt time.Time `json:"updatedAt"`
	// Username of the caller who last modified this namespace.
	UpdatedBy string `json:"updatedBy"`
}

func (Namespace) IsNode() {}

// Globally unique identifier (format: [type]_[base62])
func (this Namespace) GetID() string { return this.ID }

// Optimistic lock conflict information
type OptimisticLockConflict struct {
	// Current version in database
	CurrentVersion time.Time `json:"currentVersion"`
	// Version client attempted to update
	AttemptedVersion time.Time `json:"attemptedVersion"`
	// Current state of the entity
	Current *Product `json:"current"`
	// Diff between current and attempted (human-readable)
	Diff string `json:"diff"`
}

// Information about pagination in a connection
type PageInfo struct {
	// When paginating forwards, are there more items?
	HasNextPage bool `json:"hasNextPage"`
	// When paginating backwards, are there more items?
	HasPreviousPage bool `json:"hasPreviousPage"`
	// When paginating backwards, the cursor to continue
	StartCursor *string `json:"startCursor,omitempty"`
	// When paginating forwards, the cursor to continue
	EndCursor *string `json:"endCursor,omitempty"`
}

// Product represents a sellable item in the catalog
type Product struct {
	// Globally unique identifier (format: prod_[base62])
	ID string `json:"id"`
	// Stock Keeping Unit (unique)
	Sku string `json:"sku"`
	// Product display name
	Title string `json:"title"`
	// Markdown body content (product description with rich formatting)
	Body *string `json:"body,omitempty"`
	// Product price
	Price scalar.Decimal `json:"price"`
	// Currency code (ISO 4217)
	Currency string `json:"currency"`
	// Inventory status
	InventoryStatus InventoryStatus `json:"inventoryStatus"`
	// Available quantity (null if not tracked)
	InventoryQuantity *int32 `json:"inventoryQuantity,omitempty"`
	// Primary category (exactly one)
	Category *Category `json:"category"`
	// Collections this product belongs to (multiple allowed)
	Collections []*Collection `json:"collections"`
	// Product image URLs (external CDN)
	Images []string `json:"images"`
	// Custom metadata (free-form JSON)
	Metadata map[string]any `json:"metadata,omitempty"`
	// Creation timestamp
	CreatedAt time.Time `json:"createdAt"`
	// Last modification timestamp
	UpdatedAt time.Time `json:"updatedAt"`
}

func (Product) IsNode() {}

// Globally unique identifier (format: [type]_[base62])
func (this Product) GetID() string { return this.ID }

// Connection type for paginated products (Relay pattern)
type ProductConnection struct {
	// List of product edges
	Edges []*ProductEdge `json:"edges"`
	// Pagination information
	PageInfo *PageInfo `json:"pageInfo"`
	// Total count of products matching filter
	TotalCount int32 `json:"totalCount"`
}

// Edge type for Product connection (Relay pattern)
type ProductEdge struct {
	// Cursor for pagination
	Cursor string `json:"cursor"`
	// The product node
	Node *Product `json:"node"`
}

// Product filter options
type ProductFilter struct {
	// Filter by category ID (includes subcategory products)
	CategoryID *string `json:"categoryId,omitempty"`
	// Filter by collection ID
	CollectionID *string `json:"collectionId,omitempty"`
	// Filter by inventory status
	InventoryStatus *InventoryStatus `json:"inventoryStatus,omitempty"`
	// Filter by minimum price
	PriceMin *scalar.Decimal `json:"priceMin,omitempty"`
	// Filter by maximum price
	PriceMax *scalar.Decimal `json:"priceMax,omitempty"`
	// Search query (title, description, SKU)
	Search *string `json:"search,omitempty"`
}

// Input for publishing catalog changes
type PublishCatalogInput struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Release version tag (e.g., v1.0.0)
	Version string `json:"version"`
	// Release notes/commit message
	Message string `json:"message"`
}

// Payload for publishCatalog mutation
type PublishCatalogPayload struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// New catalog version
	CatalogVersion *CatalogVersion `json:"catalogVersion,omitempty"`
}

type Query struct {
}

// Refresh token mutation input (Relay pattern)
type RefreshTokenInput struct {
	// Client mutation ID for request tracking (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

// Refresh token mutation payload (Relay pattern)
type RefreshTokenPayload struct {
	// Client mutation ID for request tracking (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// New authentication session
	Session *AuthSession `json:"session,omitempty"`
}

// Input for reordering categories (drag-and-drop)
type ReorderCategoriesInput struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Ordered list of category IDs within parent
	OrderedIds []string `json:"orderedIds"`
	// Parent category ID (null for root categories)
	ParentID *string `json:"parentId,omitempty"`
	// Category ID being moved (for tree restructure)
	MovedCategoryID *string `json:"movedCategoryId,omitempty"`
	// New parent ID for moved category (for tree restructure)
	NewParentID *string `json:"newParentId,omitempty"`
}

// Payload for reorderCategories mutation
type ReorderCategoriesPayload struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Updated categories
	Categories []*Category `json:"categories,omitempty"`
}

// Input for reordering collections (drag-and-drop)
type ReorderCollectionsInput struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Ordered list of collection IDs
	OrderedIds []string `json:"orderedIds"`
}

// Payload for reorderCollections mutation
type ReorderCollectionsPayload struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Updated collections
	Collections []*Collection `json:"collections,omitempty"`
}

// Input for updating a category
type UpdateCategoryInput struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Category ID to update
	ID string `json:"id"`
	// New name
	Name *string `json:"name,omitempty"`
	// New slug
	Slug *string `json:"slug,omitempty"`
	// New parent ID (null to make root, ID to change parent)
	ParentID *string `json:"parentId,omitempty"`
	// New display order
	DisplayOrder *int32 `json:"displayOrder,omitempty"`
	// New body content
	Body *string `json:"body,omitempty"`
	// Version for optimistic locking
	Version time.Time `json:"version"`
}

// Payload for updateCategory mutation
type UpdateCategoryPayload struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// The updated category
	Category *Category `json:"category,omitempty"`
	// Conflict information (if optimistic lock failed)
	Conflict *CategoryOptimisticLockConflict `json:"conflict,omitempty"`
}

// Input for updating a collection
type UpdateCollectionInput struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Collection ID to update
	ID string `json:"id"`
	// New name
	Name *string `json:"name,omitempty"`
	// New slug
	Slug *string `json:"slug,omitempty"`
	// New display order
	DisplayOrder *int32 `json:"displayOrder,omitempty"`
	// New product IDs (replaces all)
	ProductIds []string `json:"productIds,omitempty"`
	// New body content
	Body *string `json:"body,omitempty"`
	// Version for optimistic locking
	Version time.Time `json:"version"`
}

// Payload for updateCollection mutation
type UpdateCollectionPayload struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// The updated collection
	Collection *Collection `json:"collection,omitempty"`
	// Conflict information (if optimistic lock failed)
	Conflict *CollectionOptimisticLockConflict `json:"conflict,omitempty"`
}

// Input for updating a product
type UpdateProductInput struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Product ID to update
	ID string `json:"id"`
	// New SKU (optional, must be unique)
	Sku *string `json:"sku,omitempty"`
	// New title
	Title *string `json:"title,omitempty"`
	// New description
	Description *string `json:"description,omitempty"`
	// New body content
	Body *string `json:"body,omitempty"`
	// New price
	Price *scalar.Decimal `json:"price,omitempty"`
	// New currency
	Currency *string `json:"currency,omitempty"`
	// New inventory status
	InventoryStatus *InventoryStatus `json:"inventoryStatus,omitempty"`
	// New inventory quantity
	InventoryQuantity *int32 `json:"inventoryQuantity,omitempty"`
	// New category ID
	CategoryID *string `json:"categoryId,omitempty"`
	// New collection IDs (replaces all)
	CollectionIds []string `json:"collectionIds,omitempty"`
	// New image URLs (replaces all)
	Images []string `json:"images,omitempty"`
	// New metadata (replaces all)
	Metadata map[string]any `json:"metadata,omitempty"`
	// Version for optimistic locking (updated_at timestamp)
	Version time.Time `json:"version"`
}

// Payload for updateProduct mutation
type UpdateProductPayload struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// The updated product
	Product *Product `json:"product,omitempty"`
	// Conflict information (if optimistic lock failed)
	Conflict *OptimisticLockConflict `json:"conflict,omitempty"`
}

// Authenticated user information
type User struct {
	// Username
	Username string `json:"username"`
	// Whether the user has admin privileges
	IsAdmin bool `json:"isAdmin"`
}

// Product inventory status
type InventoryStatus string

const (
	InventoryStatusInStock      InventoryStatus = "IN_STOCK"
	InventoryStatusOutOfStock   InventoryStatus = "OUT_OF_STOCK"
	InventoryStatusPreorder     InventoryStatus = "PREORDER"
	InventoryStatusDiscontinued InventoryStatus = "DISCONTINUED"
)

var AllInventoryStatus = []InventoryStatus{
	InventoryStatusInStock,
	InventoryStatusOutOfStock,
	InventoryStatusPreorder,
	InventoryStatusDiscontinued,
}

func (e InventoryStatus) IsValid() bool {
	switch e {
	case InventoryStatusInStock, InventoryStatusOutOfStock, InventoryStatusPreorder, InventoryStatusDiscontinued:
		return true
	}
	return false
}

func (e InventoryStatus) String() string {
	return string(e)
}

func (e *InventoryStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InventoryStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InventoryStatus", str)
	}
	return nil
}

func (e InventoryStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InventoryStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InventoryStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// The tier of a namespace, which determines ownership and repository capabilities.
type NamespaceTier string

const (
	// User-space namespace: owned by an individual, directly owns repositories.
	// Any authenticated user may create one.
	NamespaceTierUser NamespaceTier = "USER"
	// Organisation namespace: owned by a team or company, directly owns repositories.
	// May declare a parent enterprise at creation time.
	// Any authenticated user may create one.
	NamespaceTierOrganisation NamespaceTier = "ORGANISATION"
	// Enterprise namespace: organises organisations, does NOT own repositories directly.
	// Only callers with an elevated platform role (isAdmin) may create one.
	NamespaceTierEnterprise NamespaceTier = "ENTERPRISE"
)

var AllNamespaceTier = []NamespaceTier{
	NamespaceTierUser,
	NamespaceTierOrganisation,
	NamespaceTierEnterprise,
}

func (e NamespaceTier) IsValid() bool {
	switch e {
	case NamespaceTierUser, NamespaceTierOrganisation, NamespaceTierEnterprise:
		return true
	}
	return false
}

func (e NamespaceTier) String() string {
	return string(e)
}

func (e *NamespaceTier) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NamespaceTier(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NamespaceTier", str)
	}
	return nil
}

func (e NamespaceTier) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NamespaceTier) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NamespaceTier) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
