// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/shopspring/decimal"
)

// An object with a globally unique ID
type Node interface {
	IsNode()
	// Globally unique identifier (format: [type]_[base62])
	GetID() string
}

type AdmissionControlDefaults struct {
	Phase         *string `json:"phase,omitempty"`
	BranchPattern *string `json:"branchPattern,omitempty"`
}

// A pointer to another catalogue resource.
type CatalogObjectReference struct {
	APIVersion      *string `json:"apiVersion,omitempty"`
	Kind            *string `json:"kind,omitempty"`
	Name            string  `json:"name"`
	Namespace       *string `json:"namespace,omitempty"`
	UID             *string `json:"uid,omitempty"`
	ResourceVersion *string `json:"resourceVersion,omitempty"`
	FieldPath       *string `json:"fieldPath,omitempty"`
}

type CatalogStats struct {
	ProductCount       int32 `json:"productCount"`
	CategoryCount      int32 `json:"categoryCount"`
	CollectionCount    int32 `json:"collectionCount"`
	OrphanedReferences int32 `json:"orphanedReferences"`
}

type CatalogVersion struct {
	Tag         string        `json:"tag"`
	Commit      string        `json:"commit"`
	PublishedAt time.Time     `json:"publishedAt"`
	Message     *string       `json:"message,omitempty"`
	Stats       *CatalogStats `json:"stats"`
}

// Category represents a hierarchical classification system for products.
// Follows the Kubernetes-style resource envelope: id / apiVersion / kind / metadata / spec / status.
// Tree-traversal convenience fields (parent, children, path, depth, products, body) are top-level
// because they are computed or graph-linked and do not belong in spec or status.
type Category struct {
	// Globally unique identifier (format: cat_[base62])
	ID string `json:"id"`
	// Kubernetes-style apiVersion (e.g. catalog.gitstore.dev/v1beta1).
	APIVersion *string `json:"apiVersion,omitempty"`
	// Resource kind. Always "CategoryTaxonomy" for git-backed categories.
	Kind *string `json:"kind,omitempty"`
	// Resource metadata (name, labels, system-assigned fields).
	Metadata *ObjectMeta `json:"metadata"`
	// Author-supplied specification (title, parentRef, media).
	Spec *CategorySpec `json:"spec"`
	// System-written status. Null until the first push is admitted.
	Status *CategoryTaxonomyStatus `json:"status,omitempty"`
	// Markdown body content (category description).
	Body *string `json:"body,omitempty"`
	// Parent category (null for root categories).
	Parent *Category `json:"parent,omitempty"`
	// Direct child categories.
	Children []*Category `json:"children"`
	// Products in this category (includes subcategory products).
	Products *ProductConnection `json:"products"`
	// Full path from root (e.g., ["electronics", "computers", "laptops"]).
	// Derived from the materialized ancestor path stored at admission time.
	Path []string `json:"path"`
	// Depth in tree (root = 0).
	Depth int32 `json:"depth"`
}

func (Category) IsNode() {}

// Globally unique identifier (format: [type]_[base62])
func (this Category) GetID() string { return this.ID }

// Selector for looking up a category by exactly one unique key.
type CategoryBy struct {
	// Look up by globally unique Relay ID (encodes the category UID).
	ID *string `json:"id,omitempty"`
	// Look up by namespace identifier + category name (Kubernetes-style metadata.name).
	NamespacePath *CategoryNamespacePath `json:"namespacePath,omitempty"`
}

// Connection type for paginated categories (Relay pattern)
type CategoryConnection struct {
	// List of category edges
	Edges []*CategoryEdge `json:"edges"`
	// Pagination information
	PageInfo *PageInfo `json:"pageInfo"`
	// Total count of categories
	TotalCount int32 `json:"totalCount"`
}

// Edge type for Category connection (Relay pattern)
type CategoryEdge struct {
	// Cursor for pagination
	Cursor string `json:"cursor"`
	// The category node
	Node *Category `json:"node"`
}

// Composite selector: namespace identifier (human-readable slug) + category name.
type CategoryNamespacePath struct {
	Namespace string `json:"namespace"`
	Name      string `json:"name"`
}

// Optimistic lock conflict for category
type CategoryOptimisticLockConflict struct {
	// TODO: Should this be a datetime?
	// Current version in database
	CurrentVersion time.Time `json:"currentVersion"`
	// TODO: Should this be a datetime?
	// Version client attempted to update
	AttemptedVersion time.Time `json:"attemptedVersion"`
	// Current state of the category
	Current *Category `json:"current"`
	// Diff between current and attempted
	Diff string `json:"diff"`
}

// Author-supplied specification for a CategoryTaxonomy resource.
type CategorySpec struct {
	Title     string                  `json:"title"`
	ParentRef *CatalogObjectReference `json:"parentRef,omitempty"`
	Media     []*MediaDefinition      `json:"media"`
}

// System-written status for a git-backed CategoryTaxonomy resource.
type CategoryTaxonomyStatus struct {
	ObservedGeneration  int32                     `json:"observedGeneration"`
	LastAppliedRevision string                    `json:"lastAppliedRevision"`
	Conditions          []*Condition              `json:"conditions"`
	Resolved            *ResolvedCategoryTaxonomy `json:"resolved,omitempty"`
}

// CategoryTaxonomy-specific watch event. Carries the same envelope as
// the generic WatchEvent but with a strongly-typed `category` field
// instead of a JSON-boxed `object`, so core-kind consumers get full
// type safety.
type CategoryWatchEvent struct {
	Type            WatchEventType `json:"type"`
	Namespace       *string        `json:"namespace,omitempty"`
	Name            string         `json:"name"`
	ResourceVersion string         `json:"resourceVersion"`
	// Full Category resource for ADDED/MODIFIED. Null for DELETED/BOOKMARK.
	Category *Category `json:"category,omitempty"`
}

// A Collection is a namespace-scoped catalog resource that groups products via
// a declarative label selector. Defined by git push; mutations are not supported.
type Collection struct {
	// Globally unique Relay ID (encodes the collection UID).
	ID string `json:"id"`
	// API version. Always catalog.gitstore.dev/v1beta1.
	APIVersion *string `json:"apiVersion,omitempty"`
	// Resource kind. Always Collection.
	Kind *string `json:"kind,omitempty"`
	// System-managed identity and metadata.
	Metadata *ObjectMeta `json:"metadata"`
	// Author-controlled specification: title, selector, and media.
	Spec *CollectionSpec `json:"spec"`
	// System-computed status: conditions and member count.
	Status *CollectionStatus `json:"status,omitempty"`
	// Markdown body content (collection description).
	Body *string `json:"body,omitempty"`
	// Paginated connection of products matched by this collection's label selector.
	Products *ProductConnection `json:"products"`
}

func (Collection) IsNode() {}

// Globally unique identifier (format: [type]_[base62])
func (this Collection) GetID() string { return this.ID }

// Selector for looking up a collection by exactly one unique key.
type CollectionBy struct {
	// Look up by globally unique Relay ID (encodes the collection UID).
	ID *string `json:"id,omitempty"`
	// Look up by namespace identifier + collection name.
	NamespacePath *CollectionNamespacePath `json:"namespacePath,omitempty"`
}

// Paginated connection for collections (Relay pattern).
type CollectionConnection struct {
	Edges      []*CollectionEdge `json:"edges"`
	PageInfo   *PageInfo         `json:"pageInfo"`
	TotalCount int32             `json:"totalCount"`
}

// Edge type for Collection connection (Relay pattern).
type CollectionEdge struct {
	Cursor string      `json:"cursor"`
	Node   *Collection `json:"node"`
}

// Composite selector: namespace identifier + collection name.
type CollectionNamespacePath struct {
	Namespace string `json:"namespace"`
	Name      string `json:"name"`
}

type CollectionOptimisticLockConflict struct {
	Current *Collection `json:"current"`
}

// Author-controlled specification for a Collection resource.
type CollectionSpec struct {
	// Human-readable display title for the collection.
	Title string `json:"title"`
	// Label selector that determines collection membership.
	// An absent or empty selector yields zero members.
	Selector *LabelSelector `json:"selector,omitempty"`
	// Media slots referencing File resources.
	Media []*MediaDefinition `json:"media"`
}

// System-computed status for a Collection resource.
type CollectionStatus struct {
	// Generation of the spec that this status was computed from.
	ObservedGeneration int32 `json:"observedGeneration"`
	// Git revision of the last successfully admitted push.
	LastAppliedRevision *string `json:"lastAppliedRevision,omitempty"`
	// Condition set written at admission time.
	Conditions []*Condition `json:"conditions"`
	// Resolved membership snapshot (cached hint; collection.products is authoritative).
	Resolved *ResolvedCollectionDefinition `json:"resolved,omitempty"`
}

// Controller-only finalizer completion for a terminating namespace.
type CompleteNamespaceDeletionInput struct {
	Identifier      string `json:"identifier"`
	ResourceVersion string `json:"resourceVersion"`
}

type CompleteNamespaceDeletionPayload struct {
	DeletedIdentifier *string         `json:"deletedIdentifier,omitempty"`
	Conflict          *StatusConflict `json:"conflict,omitempty"`
}

// A named status condition shared by core catalog resources.
type Condition struct {
	Type               string          `json:"type"`
	Status             ConditionStatus `json:"status"`
	ObservedGeneration *int32          `json:"observedGeneration,omitempty"`
	LastTransitionTime time.Time       `json:"lastTransitionTime"`
	Reason             *string         `json:"reason,omitempty"`
	Message            *string         `json:"message,omitempty"`
}

// A named status condition input, mirroring the shared Condition
// convention used across core resources.
type ConditionInput struct {
	Type               string          `json:"type"`
	Status             ConditionStatus `json:"status"`
	ObservedGeneration int32           `json:"observedGeneration"`
	LastTransitionTime time.Time       `json:"lastTransitionTime"`
	Reason             *string         `json:"reason,omitempty"`
	Message            *string         `json:"message,omitempty"`
}

// Input for creating a category
type CreateCategoryInput struct {
	// Category name
	Name string `json:"name"`
	// URL-friendly slug (must be unique)
	Slug string `json:"slug"`
	// Parent category ID (null for root)
	ParentID *string `json:"parentId,omitempty"`
	// Display order
	DisplayOrder *int32 `json:"displayOrder,omitempty"`
	// Markdown body content
	Body *string `json:"body,omitempty"`
}

// Payload for createCategory mutation
type CreateCategoryPayload struct {
	// The created category
	Category *Category `json:"category,omitempty"`
}

type CreateCollectionInput struct {
	Name string `json:"name"`
}

type CreateCollectionPayload struct {
	Collection *Collection `json:"collection,omitempty"`
}

// Declarative resource envelope for creating a namespace.
type CreateNamespaceInput struct {
	APIVersion string                  `json:"apiVersion"`
	Kind       string                  `json:"kind"`
	Metadata   *NamespaceMetadataInput `json:"metadata"`
	Spec       *NamespaceSpecInput     `json:"spec"`
}

// Payload returned after successfully creating a namespace.
type CreateNamespacePayload struct {
	// The newly created namespace.
	Namespace *Namespace `json:"namespace"`
}

type CreateRepositoryInput struct {
	Namespace     string  `json:"namespace"`
	Name          string  `json:"name"`
	DefaultBranch *string `json:"defaultBranch,omitempty"`
}

type CreateRepositoryPayload struct {
	Repository *Repository `json:"repository"`
}

// Input for deleting a category
type DeleteCategoryInput struct {
	// Category ID to delete
	ID string `json:"id"`
}

// Payload for deleteCategory mutation
type DeleteCategoryPayload struct {
	// Deleted category ID
	DeletedCategoryID *string `json:"deletedCategoryId,omitempty"`
	// Orphaned product IDs (products that referenced this category)
	OrphanedProductIds []string `json:"orphanedProductIds,omitempty"`
}

type DeleteCollectionInput struct {
	ID string `json:"id"`
}

type DeleteCollectionPayload struct {
	DeletedCollectionID *string `json:"deletedCollectionId,omitempty"`
}

// Input for deleting a namespace.
type DeleteNamespaceInput struct {
	// The identifier of the namespace to delete.
	// Deletion is blocked if any repositories exist within the namespace.
	// Requires the caller to be the namespace owner (createdBy) or isAdmin.
	Identifier string `json:"identifier"`
}

// Payload returned after successfully deleting a namespace.
type DeleteNamespacePayload struct {
	// The identifier of the deleted namespace.
	DeletedIdentifier string `json:"deletedIdentifier"`
	// Whether this request started termination or observed an existing termination.
	Outcome NamespaceDeletionOutcome `json:"outcome"`
}

type DeleteRepositoryInput struct {
	RepositoryID string `json:"repositoryId"`
}

type DeleteRepositoryPayload struct {
	DeletedRepositoryID string `json:"deletedRepositoryId"`
}

// Gate that controls when a price template is eligible.
// Multiple constraints are combined with the specified operator.
type EligibilityDefinition struct {
	// Logical combination of constraints: ALL (AND) or ANY (OR).
	Operator EligibilityOperator `json:"operator"`
	// Individual constraint rules.
	Constraints []*PriceRuleConstraint `json:"constraints"`
}

type File struct {
	ID         string      `json:"id"`
	APIVersion string      `json:"apiVersion"`
	Kind       string      `json:"kind"`
	Metadata   *ObjectMeta `json:"metadata"`
	Spec       *FileSpec   `json:"spec"`
	Status     *FileStatus `json:"status,omitempty"`
	Body       *string     `json:"body,omitempty"`
}

func (File) IsNode() {}

// Globally unique identifier (format: [type]_[base62])
func (this File) GetID() string { return this.ID }

type FileChecksum struct {
	Algorithm string `json:"algorithm"`
	Value     string `json:"value"`
}

type FileImageProcessing struct {
	Variants []*FileVariantRequest `json:"variants"`
}

type FileProcessing struct {
	Image *FileImageProcessing `json:"image,omitempty"`
}

type FileReference struct {
	Name     string `json:"name"`
	Kind     string `json:"kind"`
	Optional bool   `json:"optional"`
}

type FileSource struct {
	Type           string        `json:"type"`
	URI            string        `json:"uri"`
	Checksum       *FileChecksum `json:"checksum,omitempty"`
	CredentialsRef *SecretRef    `json:"credentialsRef,omitempty"`
}

type FileSpec struct {
	ContentType string          `json:"contentType"`
	Type        *string         `json:"type,omitempty"`
	Source      *FileSource     `json:"source"`
	Processing  *FileProcessing `json:"processing,omitempty"`
}

type FileStatus struct {
	ObservedGeneration  int32                   `json:"observedGeneration"`
	LastAppliedRevision string                  `json:"lastAppliedRevision"`
	Conditions          []*Condition            `json:"conditions"`
	Resolved            *ResolvedFileDefinition `json:"resolved,omitempty"`
}

type FileVariantRequest struct {
	Name string `json:"name"`
}

type FileWatchEvent struct {
	Type            WatchEventType `json:"type"`
	Namespace       *string        `json:"namespace,omitempty"`
	Name            string         `json:"name"`
	ResourceVersion string         `json:"resourceVersion"`
	File            *File          `json:"file,omitempty"`
}

type HookToggle struct {
	Enabled bool `json:"enabled"`
}

// Inventory management configuration for a ProductVariant.
type InventoryDefinition struct {
	// Whether inventory levels are tracked. When false, the variant is always
	// considered available regardless of stockLocationRefs.
	Managed bool `json:"managed"`
	// Behaviour when stock is exhausted. Only meaningful when managed is true.
	// DENY prevents purchase; BACKORDER allows orders against future stock.
	Policy *InventoryPolicy `json:"policy,omitempty"`
	// References to stock location resources. Stored as-is when managed is false;
	// actively evaluated when managed is true.
	StockLocationRefs []*CatalogObjectReference `json:"stockLocationRefs"`
}

// A key-value pair for label maps.
type KeyValuePair struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// A label selector that matches products by their labels.
// matchLabels and matchExpressions are combined with logical AND.
// An empty selector (all fields absent) matches nothing.
type LabelSelector struct {
	// Exact key-value pairs that must all be present on a product's labels.
	MatchLabels map[string]any `json:"matchLabels,omitempty"`
	// Set-based requirements. All entries must be satisfied.
	MatchExpressions []*LabelSelectorRequirement `json:"matchExpressions"`
}

// Input mirror of the existing LabelSelector type for watch/list filters.
// Exact-match labels are expressed as a JSON object map to match the
// resource metadata shape used elsewhere in the API.
type LabelSelectorInput struct {
	MatchLabels      map[string]any                   `json:"matchLabels,omitempty"`
	MatchExpressions []*LabelSelectorRequirementInput `json:"matchExpressions,omitempty"`
}

// A single label selector expression with set-based semantics.
type LabelSelectorRequirement struct {
	// The label key this requirement applies to.
	Key string `json:"key"`
	// The operator: IN, NOT_IN, EXISTS, or DOES_NOT_EXIST.
	Operator LabelSelectorOperator `json:"operator"`
	// The set of values. Required for IN and NOT_IN; must be empty for EXISTS and DOES_NOT_EXIST.
	Values []string `json:"values"`
}

type LabelSelectorRequirementInput struct {
	Key      string                `json:"key"`
	Operator LabelSelectorOperator `json:"operator"`
	Values   []string              `json:"values,omitempty"`
}

// Login mutation input (Relay pattern)
type LoginInput struct {
	// Username
	Username string `json:"username"`
	// Password
	Password string `json:"password"`
	// Optional OAuth2 scope request.
	// Scope requests are currently unsupported by local providers.
	Scope *string `json:"scope,omitempty"`
}

// Login mutation payload (Relay pattern)
type LoginPayload struct {
	// OIDC-compatible token payload.
	Token *TokenResponse `json:"token"`
}

// Logout mutation payload (Relay pattern)
type LogoutPayload struct {
	// Success indicator
	Success bool `json:"success"`
}

type MediaDefinition struct {
	FileRef *FileReference `json:"fileRef"`
}

type Mutation struct {
}

// A namespace is the primary isolation boundary for repositories in GitStore.
// Namespaces are globally unique across all tiers — the same identifier cannot
// exist as both a user-space and an organization namespace.
type Namespace struct {
	// Relay transport identity.
	ID string `json:"id"`
	// Versioned Namespace API contract.
	APIVersion string `json:"apiVersion"`
	// Resource kind discriminator.
	Kind string `json:"kind"`
	// Namespace identity and system metadata.
	Metadata *NamespaceMetadata `json:"metadata"`
	// Author-controlled desired state.
	Spec *NamespaceSpec `json:"spec"`
	// System-owned observed state.
	Status *NamespaceStatus `json:"status"`
	// Human-readable identifier, globally unique across all tiers.
	// DNS label format: lowercase alphanumeric and hyphens, 1–63 characters.
	// Cannot begin or end with a hyphen.
	Identifier string `json:"identifier"`
	// Optional human-friendly display name.
	DisplayName *string `json:"displayName,omitempty"`
	// The tier of this namespace.
	Tier NamespaceTier `json:"tier"`
	// Timestamp when this namespace was created.
	CreatedAt time.Time `json:"createdAt"`
	// Username of the caller who created this namespace.
	CreatedBy string `json:"createdBy"`
	// Timestamp when this namespace was last modified.
	UpdatedAt time.Time `json:"updatedAt"`
	// Username of the caller who last modified this namespace.
	UpdatedBy string `json:"updatedBy"`
	// Markdown body content (namespace description).
	Body *string `json:"body,omitempty"`
}

func (Namespace) IsNode() {}

// Globally unique identifier (format: [type]_[base62])
func (this Namespace) GetID() string { return this.ID }

// Selector for looking up a namespace by exactly one unique key.
type NamespaceBy struct {
	ID         *string `json:"id,omitempty"`
	Identifier *string `json:"identifier,omitempty"`
	Name       *string `json:"name,omitempty"`
}

// Connection type for paginated namespaces (Relay pattern).
type NamespaceConnection struct {
	// List of namespace edges.
	Edges []*NamespaceEdge `json:"edges"`
	// Pagination information.
	PageInfo *PageInfo `json:"pageInfo"`
	// Total count of namespaces.
	TotalCount int32 `json:"totalCount"`
}

// Edge type for Namespace connection (Relay pattern).
type NamespaceEdge struct {
	// Cursor for pagination.
	Cursor string `json:"cursor"`
	// The namespace node.
	Node *Namespace `json:"node"`
}

// Object metadata for the top-level Namespace kind.
// Unlike ObjectMeta, this type intentionally has no namespace field.
type NamespaceMetadata struct {
	Name              string            `json:"name"`
	Labels            map[string]any    `json:"labels,omitempty"`
	Annotations       map[string]any    `json:"annotations,omitempty"`
	UID               string            `json:"uid"`
	ResourceVersion   string            `json:"resourceVersion"`
	Generation        int32             `json:"generation"`
	CreationTimestamp time.Time         `json:"creationTimestamp"`
	Revision          *string           `json:"revision,omitempty"`
	OwnerReferences   []*OwnerReference `json:"ownerReferences"`
	Finalizers        []string          `json:"finalizers"`
}

// Author-controlled metadata for Namespace mutations.
type NamespaceMetadataInput struct {
	Name        string         `json:"name"`
	Labels      map[string]any `json:"labels,omitempty"`
	Annotations map[string]any `json:"annotations,omitempty"`
}

type NamespacePushPolicyDefaults struct {
	MaxPackSizeBytes *int64                    `json:"maxPackSizeBytes,omitempty"`
	MaxFileSizeBytes *int64                    `json:"maxFileSizeBytes,omitempty"`
	ReceivePackHooks *ReceivePackHookDefaults  `json:"receivePackHooks,omitempty"`
	SchemaValidation *SchemaValidationDefaults `json:"schemaValidation,omitempty"`
	AdmissionControl *AdmissionControlDefaults `json:"admissionControl,omitempty"`
}

type NamespacePushPolicyDefaultsInput struct {
	MaxPackSizeBytes *int64 `json:"maxPackSizeBytes,omitempty"`
	MaxFileSizeBytes *int64 `json:"maxFileSizeBytes,omitempty"`
}

type NamespaceRepositoryDefaults struct {
	Visibility    *RepositoryVisibility `json:"visibility,omitempty"`
	DefaultBranch *string               `json:"defaultBranch,omitempty"`
}

type NamespaceRepositoryDefaultsInput struct {
	Visibility    *RepositoryVisibility `json:"visibility,omitempty"`
	DefaultBranch *string               `json:"defaultBranch,omitempty"`
}

// Author-controlled desired state for a Namespace.
type NamespaceSpec struct {
	Title              *string                      `json:"title,omitempty"`
	Tier               NamespaceTier                `json:"tier"`
	RepositoryDefaults *NamespaceRepositoryDefaults `json:"repositoryDefaults,omitempty"`
	PushPolicyDefaults *NamespacePushPolicyDefaults `json:"pushPolicyDefaults,omitempty"`
}

type NamespaceSpecInput struct {
	Title              *string                           `json:"title,omitempty"`
	Tier               NamespaceTier                     `json:"tier"`
	RepositoryDefaults *NamespaceRepositoryDefaultsInput `json:"repositoryDefaults,omitempty"`
	PushPolicyDefaults *NamespacePushPolicyDefaultsInput `json:"pushPolicyDefaults,omitempty"`
}

// System-owned observed state for a Namespace.
type NamespaceStatus struct {
	ObservedGeneration  int32        `json:"observedGeneration"`
	LastAppliedRevision *string      `json:"lastAppliedRevision,omitempty"`
	Conditions          []*Condition `json:"conditions"`
}

// System-managed metadata shared by core catalog resources.
type ObjectMeta struct {
	Name              string            `json:"name"`
	Namespace         string            `json:"namespace"`
	Labels            map[string]any    `json:"labels,omitempty"`
	Annotations       map[string]any    `json:"annotations,omitempty"`
	UID               string            `json:"uid"`
	ResourceVersion   string            `json:"resourceVersion"`
	Generation        int32             `json:"generation"`
	CreationTimestamp time.Time         `json:"creationTimestamp"`
	Revision          *string           `json:"revision,omitempty"`
	OwnerReferences   []*OwnerReference `json:"ownerReferences"`
	Finalizers        []string          `json:"finalizers"`
	DeletionTimestamp *time.Time        `json:"deletionTimestamp,omitempty"`
}

type OwnerReference struct {
	APIVersion         string `json:"apiVersion"`
	Kind               string `json:"kind"`
	Name               string `json:"name"`
	UID                string `json:"uid"`
	BlockOwnerDeletion bool   `json:"blockOwnerDeletion"`
}

// Information about pagination in a connection
type PageInfo struct {
	// When paginating forwards, are there more items?
	HasNextPage bool `json:"hasNextPage"`
	// When paginating backwards, are there more items?
	HasPreviousPage bool `json:"hasPreviousPage"`
	// When paginating backwards, the cursor to continue
	StartCursor *string `json:"startCursor,omitempty"`
	// When paginating forwards, the cursor to continue
	EndCursor *string `json:"endCursor,omitempty"`
}

type PriceRangeDefinition struct {
	CurrencyCode string          `json:"currencyCode"`
	Min          decimal.Decimal `json:"min"`
	Max          decimal.Decimal `json:"max"`
}

// A single eligibility constraint expressed as a CEL expression.
// Syntax is validated at admission; runtime evaluation is performed by the pricing engine.
type PriceRuleConstraint struct {
	// Optional human-readable name for documentation purposes.
	Name *string `json:"name,omitempty"`
	// CEL expression evaluated against runtime cart context.
	// Must be syntactically valid CEL; validated at admission.
	Expression string `json:"expression"`
}

// A named collection of price templates for a variant.
type PriceSet struct {
	// Identifier for this price set, unique within the variant spec.
	Name string `json:"name"`
	// Ordered list of price templates. Evaluation order is determined by priority.
	Prices []*PriceTemplate `json:"prices"`
}

// A single price rule within a PriceSet. Carries amount, currency, validity
// window, quantity thresholds, strategy, and optional eligibility constraints.
type PriceTemplate struct {
	// Identifier for this price template within the price set.
	Name string `json:"name"`
	// ISO 8601 timestamp from which this price is valid (inclusive). Null means no lower bound.
	ValidFromTime *time.Time `json:"validFromTime,omitempty"`
	// ISO 8601 timestamp until which this price is valid (exclusive). Null means no upper bound.
	// Must be strictly after validFromTime when both are present.
	ValidUntilTime *time.Time `json:"validUntilTime,omitempty"`
	// Optional quantity range that must be satisfied for this price to apply.
	Quantity *QuantityDefinition `json:"quantity,omitempty"`
	// ISO 4217 currency code (e.g. USD, EUR).
	CurrencyCode string `json:"currencyCode"`
	// Monetary amount for this price template, stored with full decimal precision.
	Amount decimal.Decimal `json:"amount"`
	// Pricing strategy (e.g. fixed, percentage_discount).
	Strategy *StrategyDefinition `json:"strategy"`
	// Evaluation priority. Lower values are evaluated first.
	Priority int32 `json:"priority"`
	// Optional eligibility gate. If absent, the price applies unconditionally.
	Eligibility *EligibilityDefinition `json:"eligibility,omitempty"`
}

// Top-level pricing configuration for a ProductVariant.
type PricingDefinition struct {
	// Named price set containing one or more price templates.
	PriceSet *PriceSet `json:"priceSet,omitempty"`
}

// Kubernetes-style product resource. All fields are read from the datastore,
// which holds the fully hydrated view populated by the post-push ingest pipeline.
type Product struct {
	ID         string         `json:"id"`
	APIVersion string         `json:"apiVersion"`
	Kind       string         `json:"kind"`
	Metadata   *ObjectMeta    `json:"metadata"`
	Spec       *ProductSpec   `json:"spec"`
	Status     *ProductStatus `json:"status,omitempty"`
	// Markdown body content (product description).
	Body *string `json:"body,omitempty"`
	// Paginated list of ProductVariants belonging to this product.
	ProductVariants *ProductVariantConnection `json:"productVariants"`
}

func (Product) IsNode() {}

// Globally unique identifier (format: [type]_[base62])
func (this Product) GetID() string { return this.ID }

// Selector for a single product lookup. Exactly one field must be set.
type ProductBy struct {
	// Look up by globally unique Relay ID (encodes the product UID).
	ID *string `json:"id,omitempty"`
	// Look up by namespace identifier + product name (Kubernetes-style metadata.name).
	NamespacePath *ProductNamespacePath `json:"namespacePath,omitempty"`
}

// Connection type for paginated products (Relay pattern).
type ProductConnection struct {
	Edges      []*ProductEdge `json:"edges"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	TotalCount int32          `json:"totalCount"`
}

// Edge type for Product connection (Relay pattern).
type ProductEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Product `json:"node"`
}

// Composite selector: namespace identifier (human-readable slug) + product name.
type ProductNamespacePath struct {
	Namespace string `json:"namespace"`
	Name      string `json:"name"`
}

type ProductOptionDefinition struct {
	Name   string   `json:"name"`
	Title  *string  `json:"title,omitempty"`
	Values []string `json:"values"`
}

type ProductSpec struct {
	Title       *string                    `json:"title,omitempty"`
	CategoryRef *CatalogObjectReference    `json:"categoryRef,omitempty"`
	Tags        []string                   `json:"tags"`
	Media       []*MediaDefinition         `json:"media"`
	Options     []*ProductOptionDefinition `json:"options"`
}

type ProductStatus struct {
	ObservedGeneration  int32                      `json:"observedGeneration"`
	LastAppliedRevision *string                    `json:"lastAppliedRevision,omitempty"`
	Conditions          []*Condition               `json:"conditions"`
	Resolved            *ResolvedProductDefinition `json:"resolved,omitempty"`
}

// Kubernetes-style ProductVariant resource. The atomic sellable SKU unit.
// Product is the non-sellable parent descriptor; ProductVariant carries pricing,
// inventory policy, and the selected option combination that makes a SKU unique.
type ProductVariant struct {
	// Globally unique Relay ID (encodes the variant UID).
	ID string `json:"id"`
	// API version. Always catalog.gitstore.dev/v1beta1.
	APIVersion string `json:"apiVersion"`
	// Resource kind. Always ProductVariant.
	Kind string `json:"kind"`
	// System-managed identity and metadata.
	Metadata *ObjectMeta `json:"metadata"`
	// Author-controlled specification: SKU, pricing, inventory, and options.
	Spec *ProductVariantSpec `json:"spec"`
	// System-computed status written at admission and updated by the controller.
	Status *ProductVariantStatus `json:"status,omitempty"`
	// Variant-specific descriptive copy authored in the Markdown body.
	Body *string `json:"body,omitempty"`
}

func (ProductVariant) IsNode() {}

// Globally unique identifier (format: [type]_[base62])
func (this ProductVariant) GetID() string { return this.ID }

// Selector for a single ProductVariant lookup. Exactly one field must be set.
type ProductVariantBy struct {
	// Look up by globally unique Relay ID (encodes the variant UID).
	ID *string `json:"id,omitempty"`
	// Look up by namespace identifier + variant name (Kubernetes-style metadata.name).
	NamespacePath *ProductVariantNamespacePath `json:"namespacePath,omitempty"`
}

// Paginated connection for ProductVariants (Relay pattern).
type ProductVariantConnection struct {
	Edges      []*ProductVariantEdge `json:"edges"`
	PageInfo   *PageInfo             `json:"pageInfo"`
	TotalCount int32                 `json:"totalCount"`
}

// Edge type for ProductVariant connection (Relay pattern).
type ProductVariantEdge struct {
	Cursor string          `json:"cursor"`
	Node   *ProductVariant `json:"node"`
}

// Composite selector: namespace identifier (human-readable slug) + variant name.
type ProductVariantNamespacePath struct {
	Namespace string `json:"namespace"`
	Name      string `json:"name"`
}

// Author-controlled specification for a ProductVariant resource.
type ProductVariantSpec struct {
	// Human-readable display title for this variant.
	Title string `json:"title"`
	// Stock-keeping unit: globally unique identifier for the variant within the namespace.
	Sku string `json:"sku"`
	// Reference to the parent Product this variant belongs to.
	ProductRef *CatalogObjectReference `json:"productRef"`
	// Inventory management settings.
	Inventory *InventoryDefinition `json:"inventory,omitempty"`
	// Pricing rules and price templates.
	Pricing *PricingDefinition `json:"pricing,omitempty"`
	// The combination of option name/value pairs that uniquely identify this variant.
	// Must match a valid combination defined on the parent Product.
	SelectedOptions []*SelectedOptionDefinition `json:"selectedOptions"`
	// Media slots referencing File resources.
	Media []*MediaDefinition `json:"media"`
}

// System-computed status for a ProductVariant resource.
type ProductVariantStatus struct {
	// Generation of the spec that this status was computed from.
	ObservedGeneration int32 `json:"observedGeneration"`
	// Git revision of the last successfully admitted push.
	LastAppliedRevision *string `json:"lastAppliedRevision,omitempty"`
	// Condition set written at admission and updated by the controller.
	Conditions []*Condition `json:"conditions"`
	// Resolved aggregates computed at admission and kept current by the controller.
	Resolved *ResolvedProductVariantDefinition `json:"resolved,omitempty"`
}

// Product-specific watch event. Carries the same envelope as
// CategoryWatchEvent but with a strongly-typed `product` field instead
// of a JSON-boxed `object`, so core-kind consumers get full type safety.
type ProductWatchEvent struct {
	Type            WatchEventType `json:"type"`
	Namespace       *string        `json:"namespace,omitempty"`
	Name            string         `json:"name"`
	ResourceVersion string         `json:"resourceVersion"`
	// Full Product resource for ADDED/MODIFIED. Null for DELETED/BOOKMARK.
	Product *Product `json:"product,omitempty"`
}

type PublishCatalogInput struct {
	Version string `json:"version"`
	Message string `json:"message"`
}

type PublishCatalogPayload struct {
	CatalogVersion *CatalogVersion `json:"catalogVersion,omitempty"`
}

// Inclusive quantity range that must be satisfied for a price template to apply.
type QuantityDefinition struct {
	// Minimum order quantity (inclusive).
	Min int32 `json:"min"`
	// Maximum order quantity (inclusive). Null means unbounded.
	Max *int32 `json:"max,omitempty"`
}

type Query struct {
}

type ReceivePackHookDefaults struct {
	PreReceive           *HookToggle `json:"preReceive,omitempty"`
	Update               *HookToggle `json:"update,omitempty"`
	PostReceive          *HookToggle `json:"postReceive,omitempty"`
	ProcReceive          *HookToggle `json:"procReceive,omitempty"`
	PostUpdate           *HookToggle `json:"postUpdate,omitempty"`
	ReferenceTransaction *HookToggle `json:"referenceTransaction,omitempty"`
}

// Refresh token mutation input (Relay pattern)
type RefreshTokenInput struct {
	// Refresh token used to issue a new access token.
	RefreshToken string `json:"refreshToken"`
	// Optional OAuth2 scope request.
	// Scope requests are currently unsupported by local providers.
	Scope *string `json:"scope,omitempty"`
}

// Refresh token mutation payload (Relay pattern)
type RefreshTokenPayload struct {
	// OIDC-compatible token payload.
	Token *TokenResponse `json:"token"`
}

type RenameRepositoryInput struct {
	// Relay ID of the repository to rename.
	RepositoryID string `json:"repositoryId"`
	NewName      string `json:"newName"`
}

type RenameRepositoryPayload struct {
	Repository *Repository `json:"repository"`
}

// Input for reordering categories (drag-and-drop)
type ReorderCategoriesInput struct {
	// Ordered list of category IDs within parent
	OrderedIds []string `json:"orderedIds"`
	// Parent category ID (null for root categories)
	ParentID *string `json:"parentId,omitempty"`
	// Category ID being moved (for tree restructure)
	MovedCategoryID *string `json:"movedCategoryId,omitempty"`
	// New parent ID for moved category (for tree restructure)
	NewParentID *string `json:"newParentId,omitempty"`
}

// Payload for reorderCategories mutation
type ReorderCategoriesPayload struct {
	// Updated categories
	Categories []*Category `json:"categories,omitempty"`
}

// A namespace-scoped GitStore Repository resource.
type Repository struct {
	// Relay transport identity.
	ID string `json:"id"`
	// Versioned Repository API contract.
	APIVersion string `json:"apiVersion"`
	// Resource kind discriminator. Always "Repository".
	Kind string `json:"kind"`
	// System-managed identity, namespace ownership, versioning, and creation metadata.
	Metadata *ObjectMeta `json:"metadata"`
	// Declarative Repository configuration. Fields without an existing write and
	// persistence path project deterministic reserved defaults in this API version.
	Spec *RepositorySpec `json:"spec"`
	// System-derived Repository state. Present for every Repository, including
	// resources created before this contract existed.
	Status        *RepositoryStatus `json:"status"`
	Name          string            `json:"name"`
	Namespace     *Namespace        `json:"namespace"`
	DefaultBranch string            `json:"defaultBranch"`
	StorageClass  string            `json:"storageClass"`
	StoragePath   string            `json:"storagePath"`
	CreatedAt     time.Time         `json:"createdAt"`
	CreatedBy     string            `json:"createdBy"`
	UpdatedAt     time.Time         `json:"updatedAt"`
	UpdatedBy     string            `json:"updatedBy"`
	// Markdown body content (repository description).
	Body *string `json:"body,omitempty"`
}

func (Repository) IsNode() {}

// Globally unique identifier (format: [type]_[base62])
func (this Repository) GetID() string { return this.ID }

// Selector for a single repository lookup.
// Exactly one field must be set.
type RepositoryBy struct {
	// Look up by globally unique Relay ID.
	ID *string `json:"id,omitempty"`
	// Look up by namespace identifier + repository name.
	NamespacePath *RepositoryNamespacePath `json:"namespacePath,omitempty"`
}

type RepositoryConnection struct {
	Edges      []*RepositoryEdge `json:"edges"`
	PageInfo   *PageInfo         `json:"pageInfo"`
	TotalCount int32             `json:"totalCount"`
}

type RepositoryEdge struct {
	Cursor string      `json:"cursor"`
	Node   *Repository `json:"node"`
}

// Composite selector: namespace identifier (human-readable slug) + repository name.
type RepositoryNamespacePath struct {
	// Namespace identifier slug (e.g., "acme").
	Namespace string `json:"namespace"`
	// Repository name (e.g., "my-catalog").
	Name string `json:"name"`
}

// Repository-level push-policy projection. Maximum-size fields use existing
// persisted values. Extended override groups are reserved and null until a future
// feature defines their write and persistence semantics.
type RepositoryPushPolicy struct {
	MaxPackSizeBytes int64                     `json:"maxPackSizeBytes"`
	MaxFileSizeBytes int64                     `json:"maxFileSizeBytes"`
	ReceivePackHooks *ReceivePackHookDefaults  `json:"receivePackHooks,omitempty"`
	SchemaValidation *SchemaValidationDefaults `json:"schemaValidation,omitempty"`
	AdmissionControl *AdmissionControlDefaults `json:"admissionControl,omitempty"`
}

// Declarative desired-state projection for a Repository. In this feature,
// visibility is reserved and projects PRIVATE until write semantics are added.
type RepositorySpec struct {
	DefaultBranch string                `json:"defaultBranch"`
	Visibility    RepositoryVisibility  `json:"visibility"`
	PushPolicy    *RepositoryPushPolicy `json:"pushPolicy"`
}

// System-owned observed state for a Repository.
type RepositoryStatus struct {
	ObservedGeneration  int32   `json:"observedGeneration"`
	LastAppliedRevision *string `json:"lastAppliedRevision,omitempty"`
	// Shared resource conditions. Empty in this feature because no Repository
	// condition-producing writer or Repository-specific condition vocabulary exists.
	Conditions []*Condition                  `json:"conditions"`
	Resolved   *ResolvedRepositoryDefinition `json:"resolved"`
}

type ResolvedCategoryDefinition struct {
	Name string   `json:"name"`
	Path []string `json:"path"`
}

// Controller-computed category hierarchy metadata.
type ResolvedCategoryTaxonomy struct {
	Depth int32 `json:"depth"`
	// Ancestor path from root to self, e.g. ["electronics", "computers",
	// "laptops"] for the "laptops" category (root-to-self order). A root
	// category's path is a single-element array containing its own name.
	// Distinct from Category.path, which is a read-time-derived field
	// computed from the separate ancestor_path datastore column (see
	// specs/040-controller-watch-status-api/research.md R9/R10).
	Path         []string `json:"path"`
	ChildCount   int32    `json:"childCount"`
	ProductCount int32    `json:"productCount"`
}

type ResolvedCategoryTaxonomyInput struct {
	Depth int32 `json:"depth"`
	// Ancestor path from root to self, e.g. ["electronics", "computers",
	// "laptops"] (root-to-self order). A root category's path is a
	// single-element array containing its own name.
	Path         []string `json:"path"`
	ChildCount   int32    `json:"childCount"`
	ProductCount int32    `json:"productCount"`
}

// Resolved membership information cached at last admission.
type ResolvedCollectionDefinition struct {
	// Cached count of matching products at last admission.
	MemberCount int32 `json:"memberCount"`
}

type ResolvedFileDefinition struct {
	Name             string                 `json:"name"`
	URL              string                 `json:"url"`
	ContentType      *string                `json:"contentType,omitempty"`
	ResolvedVariants []*ResolvedFileVariant `json:"resolvedVariants"`
}

type ResolvedFileVariant struct {
	Name string  `json:"name"`
	URL  *string `json:"url,omitempty"`
}

// Resolved inventory summary for a ProductVariant.
type ResolvedInventoryDefinition struct {
	Managed           bool             `json:"managed"`
	AvailableQuantity int32            `json:"availableQuantity"`
	Policy            *InventoryPolicy `json:"policy,omitempty"`
}

// Resolved summary of the variant's price set.
type ResolvedPriceSetDefinition struct {
	Name string `json:"name"`
	// Stable hash of all price templates in the set.
	Hash *string `json:"hash,omitempty"`
	// Number of CEL expressions compiled successfully.
	CompiledExpressions int32 `json:"compiledExpressions"`
	// Total number of price templates.
	PriceCount int32 `json:"priceCount"`
	// Distinct currency codes present in the price set.
	Currencies []string `json:"currencies"`
	// Distinct strategy types present in the price set.
	Strategies []string `json:"strategies"`
}

type ResolvedProductDefinition struct {
	Category          *ResolvedCategoryDefinition `json:"category,omitempty"`
	PriceRange        []*PriceRangeDefinition     `json:"priceRange"`
	TotalInventory    int32                       `json:"totalInventory"`
	VariantSummary    *VariantSummaryDefinition   `json:"variantSummary,omitempty"`
	DefaultVariantRef *CatalogObjectReference     `json:"defaultVariantRef,omitempty"`
	Media             []*ResolvedFileDefinition   `json:"media"`
}

// Resolved identity of the parent Product resource.
type ResolvedProductRef struct {
	Name string `json:"name"`
	UID  string `json:"uid"`
}

// Resolved aggregates for a ProductVariant, computed at admission and kept current.
type ResolvedProductVariantDefinition struct {
	// Resolved parent product identity.
	Product *ResolvedProductRef `json:"product,omitempty"`
	// Stable fingerprint of the selectedOptions combination (sorted name:value pairs).
	SelectedOptionsHash *string `json:"selectedOptionsHash,omitempty"`
	// Resolved pricing summary.
	PriceSet *ResolvedPriceSetDefinition `json:"priceSet,omitempty"`
	// Resolved inventory summary.
	Inventory *ResolvedInventoryDefinition `json:"inventory,omitempty"`
	// Resolved media files.
	Media []*ResolvedFileDefinition `json:"media"`
}

// System-computed Repository values that authors cannot set directly.
type ResolvedRepositoryDefinition struct {
	StoragePath  string `json:"storagePath"`
	StorageClass string `json:"storageClass"`
}

type SchemaValidationDefaults struct {
	Phase          *string `json:"phase,omitempty"`
	TimeoutSeconds *int32  `json:"timeoutSeconds,omitempty"`
}

type SecretRef struct {
	Kind      string  `json:"kind"`
	Name      string  `json:"name"`
	Key       *string `json:"key,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
}

// A resolved name/value pair representing one product option selection.
type SelectedOptionDefinition struct {
	// Option name, must match a name declared on the parent Product's options list.
	Name string `json:"name"`
	// Selected value for the named option.
	Value string `json:"value"`
}

// Optimistic-concurrency conflict payload shared by all status-write
// mutations (per-kind and generic).
type StatusConflict struct {
	// The resource's actual current resourceVersion, for retry.
	CurrentResourceVersion string `json:"currentResourceVersion"`
}

// Pricing strategy applied when this price template is selected.
type StrategyDefinition struct {
	// Strategy identifier (e.g. fixed, percentage_discount, cost_plus).
	Type string `json:"type"`
}

type Subscription struct {
}

// OIDC-compatible token response.
type TokenResponse struct {
	// Access token used for authenticated API calls.
	AccessToken string `json:"accessToken"`
	// Token type. Always `Bearer` for GitStore-issued tokens.
	TokenType string `json:"tokenType"`
	// Seconds until the access token expires.
	ExpiresIn int32 `json:"expiresIn"`
	// Refresh token used to obtain a new access token.
	// For local providers, this is currently a GitStore-issued token.
	RefreshToken *string `json:"refreshToken,omitempty"`
	// Granted scope set as a space-delimited string.
	// Scope requests are currently unsupported and this field is null.
	Scope *string `json:"scope,omitempty"`
	// OIDC ID token when available.
	// GitStore local providers currently do not issue this field.
	IDToken *string `json:"idToken,omitempty"`
}

type TransferRepositoryInput struct {
	// Relay ID of the repository to transfer.
	RepositoryID string `json:"repositoryId"`
	// Relay ID of the destination namespace.
	TargetNamespaceID string `json:"targetNamespaceId"`
}

type TransferRepositoryPayload struct {
	Repository *Repository `json:"repository"`
}

// Input for updating a category
type UpdateCategoryInput struct {
	// Category ID to update
	ID string `json:"id"`
	// New name
	Name *string `json:"name,omitempty"`
	// New slug
	Slug *string `json:"slug,omitempty"`
	// New parent ID (null to make root, ID to change parent)
	ParentID *string `json:"parentId,omitempty"`
	// New display order
	DisplayOrder *int32 `json:"displayOrder,omitempty"`
	// New body content
	Body *string `json:"body,omitempty"`
	// TODO: Should this be a datetime?
	// Version for optimistic locking
	Version time.Time `json:"version"`
}

// Payload for updateCategory mutation
type UpdateCategoryPayload struct {
	// The updated category
	Category *Category `json:"category,omitempty"`
	// Conflict information (if optimistic lock failed)
	Conflict *CategoryOptimisticLockConflict `json:"conflict,omitempty"`
}

type UpdateCategoryStatusInput struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
	// Required optimistic-concurrency precondition (FR-009). Must equal
	// the resource's current metadata.resourceVersion.
	ResourceVersion string `json:"resourceVersion"`
	// Null = unchanged. Set on every successful reconcile per spec 026 FR-008.
	ObservedGeneration *int32 `json:"observedGeneration,omitempty"`
	// Null = unchanged, e.g. "main@sha1:a1b2c3d".
	LastAppliedRevision *string `json:"lastAppliedRevision,omitempty"`
	// Null = unchanged. Non-null = full replacement of the conditions slice.
	Conditions []*ConditionInput `json:"conditions,omitempty"`
	// Null = unchanged. Kind-specific — not part of any generic patch shape.
	Resolved *ResolvedCategoryTaxonomyInput `json:"resolved,omitempty"`
	// Controller-only foreground-deletion completion request. This extends the
	// existing status subresource rather than introducing a parallel
	// CategoryTaxonomy mutation.
	CompleteDeletion *bool `json:"completeDeletion,omitempty"`
	// Controller-only bounded Product drain. The server removes non-blocking
	// owner references and writes CategoryDeleted without changing product spec.
	DecoupleProducts *bool `json:"decoupleProducts,omitempty"`
}

type UpdateCategoryStatusPayload struct {
	// Null when the write failed (conflict or not-found).
	Category *Category `json:"category,omitempty"`
	// Non-null only when the resourceVersion precondition failed.
	Conflict *StatusConflict `json:"conflict,omitempty"`
	// True when another bounded Product page remains to be processed.
	HasMoreProductDependents bool `json:"hasMoreProductDependents"`
}

type UpdateCollectionInput struct {
	ID string `json:"id"`
}

type UpdateCollectionPayload struct {
	Collection *Collection                       `json:"collection,omitempty"`
	Conflict   *CollectionOptimisticLockConflict `json:"conflict,omitempty"`
}

// Declarative resource envelope for updating a namespace.
type UpdateNamespaceInput struct {
	APIVersion string                  `json:"apiVersion"`
	Kind       string                  `json:"kind"`
	Metadata   *NamespaceMetadataInput `json:"metadata"`
	Spec       *NamespaceSpecInput     `json:"spec"`
}

type UpdateNamespacePayload struct {
	Namespace *Namespace `json:"namespace,omitempty"`
}

type UpdateProductStatusInput struct {
	Name            string            `json:"name"`
	Namespace       string            `json:"namespace"`
	ResourceVersion string            `json:"resourceVersion"`
	Conditions      []*ConditionInput `json:"conditions,omitempty"`
	RemoveOwnerUID  *string           `json:"removeOwnerUID,omitempty"`
}

type UpdateProductStatusPayload struct {
	Product  *Product        `json:"product,omitempty"`
	Conflict *StatusConflict `json:"conflict,omitempty"`
}

type UpdateResourceStatusInput struct {
	Kind                string            `json:"kind"`
	Name                string            `json:"name"`
	Namespace           string            `json:"namespace"`
	ResourceVersion     string            `json:"resourceVersion"`
	ObservedGeneration  *int32            `json:"observedGeneration,omitempty"`
	LastAppliedRevision *string           `json:"lastAppliedRevision,omitempty"`
	Conditions          []*ConditionInput `json:"conditions,omitempty"`
	// Kind-specific resolved payload, JSON-boxed since no static input type
	// exists for an arbitrary CRD kind (mirrors WatchEvent.object).
	Resolved map[string]any `json:"resolved,omitempty"`
}

type UpdateResourceStatusPayload struct {
	// JSON-boxed current resource state; null when the write failed.
	Object   map[string]any  `json:"object,omitempty"`
	Conflict *StatusConflict `json:"conflict,omitempty"`
}

// Authenticated user information
type User struct {
	// Username
	Username string `json:"username"`
	// Whether the user has admin privileges
	IsAdmin bool `json:"isAdmin"`
}

type VariantSummaryDefinition struct {
	Total       int32 `json:"total"`
	Ready       int32 `json:"ready"`
	Unavailable int32 `json:"unavailable"`
}

// A single change notification for a watched resource kind, delivered by
// the generic watchResources subscription.
type WatchEvent struct {
	Type      WatchEventType `json:"type"`
	Kind      string         `json:"kind"`
	Namespace *string        `json:"namespace,omitempty"`
	Name      string         `json:"name"`
	// Opaque resume cursor. Present on every event, including BOOKMARK.
	ResourceVersion string `json:"resourceVersion"`
	// Full resource payload for ADDED/MODIFIED. Null for DELETED/BOOKMARK.
	// JSON-boxed because the generic watchResources path has no
	// compile-time-known shape for CRD kinds.
	Object map[string]any `json:"object,omitempty"`
}

type ConditionStatus string

const (
	ConditionStatusTrue    ConditionStatus = "TRUE"
	ConditionStatusFalse   ConditionStatus = "FALSE"
	ConditionStatusUnknown ConditionStatus = "UNKNOWN"
)

var AllConditionStatus = []ConditionStatus{
	ConditionStatusTrue,
	ConditionStatusFalse,
	ConditionStatusUnknown,
}

func (e ConditionStatus) IsValid() bool {
	switch e {
	case ConditionStatusTrue, ConditionStatusFalse, ConditionStatusUnknown:
		return true
	}
	return false
}

func (e ConditionStatus) String() string {
	return string(e)
}

func (e *ConditionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConditionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConditionStatus", str)
	}
	return nil
}

func (e ConditionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConditionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConditionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Logical combination operator for eligibility constraints.
type EligibilityOperator string

const (
	// All constraints must be satisfied.
	EligibilityOperatorAll EligibilityOperator = "ALL"
	// At least one constraint must be satisfied.
	EligibilityOperatorAny EligibilityOperator = "ANY"
)

var AllEligibilityOperator = []EligibilityOperator{
	EligibilityOperatorAll,
	EligibilityOperatorAny,
}

func (e EligibilityOperator) IsValid() bool {
	switch e {
	case EligibilityOperatorAll, EligibilityOperatorAny:
		return true
	}
	return false
}

func (e EligibilityOperator) String() string {
	return string(e)
}

func (e *EligibilityOperator) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EligibilityOperator(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EligibilityOperator", str)
	}
	return nil
}

func (e EligibilityOperator) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EligibilityOperator) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EligibilityOperator) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Inventory oversell policy applied when managed stock reaches zero.
type InventoryPolicy string

const (
	// Reject new orders when stock reaches zero.
	InventoryPolicyDeny InventoryPolicy = "DENY"
	// Allow orders against negative stock (backorder).
	InventoryPolicyBackorder InventoryPolicy = "BACKORDER"
)

var AllInventoryPolicy = []InventoryPolicy{
	InventoryPolicyDeny,
	InventoryPolicyBackorder,
}

func (e InventoryPolicy) IsValid() bool {
	switch e {
	case InventoryPolicyDeny, InventoryPolicyBackorder:
		return true
	}
	return false
}

func (e InventoryPolicy) String() string {
	return string(e)
}

func (e *InventoryPolicy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InventoryPolicy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InventoryPolicy", str)
	}
	return nil
}

func (e InventoryPolicy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InventoryPolicy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InventoryPolicy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Product inventory status
type InventoryStatus string

const (
	InventoryStatusInStock      InventoryStatus = "IN_STOCK"
	InventoryStatusOutOfStock   InventoryStatus = "OUT_OF_STOCK"
	InventoryStatusPreorder     InventoryStatus = "PREORDER"
	InventoryStatusDiscontinued InventoryStatus = "DISCONTINUED"
)

var AllInventoryStatus = []InventoryStatus{
	InventoryStatusInStock,
	InventoryStatusOutOfStock,
	InventoryStatusPreorder,
	InventoryStatusDiscontinued,
}

func (e InventoryStatus) IsValid() bool {
	switch e {
	case InventoryStatusInStock, InventoryStatusOutOfStock, InventoryStatusPreorder, InventoryStatusDiscontinued:
		return true
	}
	return false
}

func (e InventoryStatus) String() string {
	return string(e)
}

func (e *InventoryStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InventoryStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InventoryStatus", str)
	}
	return nil
}

func (e InventoryStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InventoryStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InventoryStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Operators supported in a LabelSelectorRequirement.
type LabelSelectorOperator string

const (
	LabelSelectorOperatorIn           LabelSelectorOperator = "IN"
	LabelSelectorOperatorNotIn        LabelSelectorOperator = "NOT_IN"
	LabelSelectorOperatorExists       LabelSelectorOperator = "EXISTS"
	LabelSelectorOperatorDoesNotExist LabelSelectorOperator = "DOES_NOT_EXIST"
)

var AllLabelSelectorOperator = []LabelSelectorOperator{
	LabelSelectorOperatorIn,
	LabelSelectorOperatorNotIn,
	LabelSelectorOperatorExists,
	LabelSelectorOperatorDoesNotExist,
}

func (e LabelSelectorOperator) IsValid() bool {
	switch e {
	case LabelSelectorOperatorIn, LabelSelectorOperatorNotIn, LabelSelectorOperatorExists, LabelSelectorOperatorDoesNotExist:
		return true
	}
	return false
}

func (e LabelSelectorOperator) String() string {
	return string(e)
}

func (e *LabelSelectorOperator) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LabelSelectorOperator(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LabelSelectorOperator", str)
	}
	return nil
}

func (e LabelSelectorOperator) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LabelSelectorOperator) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LabelSelectorOperator) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// The successful result of requesting Namespace termination.
type NamespaceDeletionOutcome string

const (
	// This request set the deletion timestamp and foreground deletion finalizer.
	NamespaceDeletionOutcomeTerminationStarted NamespaceDeletionOutcome = "TERMINATION_STARTED"
	// The Namespace was already terminating, so no datastore write occurred.
	NamespaceDeletionOutcomeAlreadyTerminating NamespaceDeletionOutcome = "ALREADY_TERMINATING"
)

var AllNamespaceDeletionOutcome = []NamespaceDeletionOutcome{
	NamespaceDeletionOutcomeTerminationStarted,
	NamespaceDeletionOutcomeAlreadyTerminating,
}

func (e NamespaceDeletionOutcome) IsValid() bool {
	switch e {
	case NamespaceDeletionOutcomeTerminationStarted, NamespaceDeletionOutcomeAlreadyTerminating:
		return true
	}
	return false
}

func (e NamespaceDeletionOutcome) String() string {
	return string(e)
}

func (e *NamespaceDeletionOutcome) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NamespaceDeletionOutcome(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NamespaceDeletionOutcome", str)
	}
	return nil
}

func (e NamespaceDeletionOutcome) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NamespaceDeletionOutcome) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NamespaceDeletionOutcome) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// The tier of a namespace, which determines ownership and repository capabilities.
type NamespaceTier string

const (
	// User-space namespace: owned by an individual, directly owns repositories.
	// Any authenticated user may create one.
	NamespaceTierUser NamespaceTier = "USER"
	// Organization namespace: owned by a team or company, directly owns repositories.
	// Any authenticated user may create one.
	NamespaceTierOrganization NamespaceTier = "ORGANIZATION"
)

var AllNamespaceTier = []NamespaceTier{
	NamespaceTierUser,
	NamespaceTierOrganization,
}

func (e NamespaceTier) IsValid() bool {
	switch e {
	case NamespaceTierUser, NamespaceTierOrganization:
		return true
	}
	return false
}

func (e NamespaceTier) String() string {
	return string(e)
}

func (e *NamespaceTier) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NamespaceTier(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NamespaceTier", str)
	}
	return nil
}

func (e NamespaceTier) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NamespaceTier) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NamespaceTier) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RepositoryVisibility string

const (
	RepositoryVisibilityPublic   RepositoryVisibility = "PUBLIC"
	RepositoryVisibilityPrivate  RepositoryVisibility = "PRIVATE"
	RepositoryVisibilityInternal RepositoryVisibility = "INTERNAL"
)

var AllRepositoryVisibility = []RepositoryVisibility{
	RepositoryVisibilityPublic,
	RepositoryVisibilityPrivate,
	RepositoryVisibilityInternal,
}

func (e RepositoryVisibility) IsValid() bool {
	switch e {
	case RepositoryVisibilityPublic, RepositoryVisibilityPrivate, RepositoryVisibilityInternal:
		return true
	}
	return false
}

func (e RepositoryVisibility) String() string {
	return string(e)
}

func (e *RepositoryVisibility) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RepositoryVisibility(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RepositoryVisibility", str)
	}
	return nil
}

func (e RepositoryVisibility) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RepositoryVisibility) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RepositoryVisibility) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WatchEventType string

const (
	WatchEventTypeAdded    WatchEventType = "ADDED"
	WatchEventTypeModified WatchEventType = "MODIFIED"
	WatchEventTypeDeleted  WatchEventType = "DELETED"
	// Carries only a resourceVersion advance with no object change — used
	// to let a long-idle subscription periodically refresh its cursor
	// without a corresponding resource change. object is always null.
	WatchEventTypeBookmark WatchEventType = "BOOKMARK"
)

var AllWatchEventType = []WatchEventType{
	WatchEventTypeAdded,
	WatchEventTypeModified,
	WatchEventTypeDeleted,
	WatchEventTypeBookmark,
}

func (e WatchEventType) IsValid() bool {
	switch e {
	case WatchEventTypeAdded, WatchEventTypeModified, WatchEventTypeDeleted, WatchEventTypeBookmark:
		return true
	}
	return false
}

func (e WatchEventType) String() string {
	return string(e)
}

func (e *WatchEventType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WatchEventType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WatchEventType", str)
	}
	return nil
}

func (e WatchEventType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WatchEventType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WatchEventType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
