// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/shopspring/decimal"
)

// An object with a globally unique ID
type Node interface {
	IsNode()
	// Globally unique identifier (format: [type]_[base62])
	GetID() string
}

// Authentication session response
type AuthSession struct {
	// JWT token for authentication
	Token string `json:"token"`
	// Token expiration time (ISO 8601)
	ExpiresAt time.Time `json:"expiresAt"`
	// Authenticated user information
	User *User `json:"user"`
}

// A pointer to another catalogue resource.
type CatalogObjectReference struct {
	APIVersion      *string `json:"apiVersion,omitempty"`
	Kind            *string `json:"kind,omitempty"`
	Name            string  `json:"name"`
	Namespace       *string `json:"namespace,omitempty"`
	UID             *string `json:"uid,omitempty"`
	ResourceVersion *string `json:"resourceVersion,omitempty"`
	FieldPath       *string `json:"fieldPath,omitempty"`
}

// Catalog statistics
type CatalogStats struct {
	// Total products
	ProductCount int32 `json:"productCount"`
	// Total categories
	CategoryCount int32 `json:"categoryCount"`
	// Total collections
	CollectionCount int32 `json:"collectionCount"`
	// Number of orphaned product references
	OrphanedReferences int32 `json:"orphanedReferences"`
}

// Catalog version information
type CatalogVersion struct {
	// Version tag (e.g., v1.0.0)
	Tag string `json:"tag"`
	// Commit SHA
	Commit string `json:"commit"`
	// Release timestamp
	PublishedAt time.Time `json:"publishedAt"`
	// Release message
	Message *string `json:"message,omitempty"`
	// Statistics
	Stats *CatalogStats `json:"stats"`
}

// Category represents a hierarchical classification system for products.
// Follows the Kubernetes-style resource envelope: id / apiVersion / kind / metadata / spec / status.
// Tree-traversal convenience fields (parent, children, path, depth, products, body) are top-level
// because they are computed or graph-linked and do not belong in spec or status.
type Category struct {
	// Globally unique identifier (format: cat_[base62])
	ID string `json:"id"`
	// Kubernetes-style apiVersion (e.g. catalog.gitstore.dev/v1beta1).
	APIVersion *string `json:"apiVersion,omitempty"`
	// Resource kind. Always "CategoryTaxonomy" for git-backed categories.
	Kind *string `json:"kind,omitempty"`
	// Resource metadata (name, labels, system-assigned fields).
	Metadata *CategoryObjectMeta `json:"metadata"`
	// Author-supplied specification (title, parentRef, media).
	Spec *CategorySpec `json:"spec"`
	// System-written status. Null until the first push is admitted.
	Status *CategoryTaxonomyStatus `json:"status,omitempty"`
	// Markdown body content (category description).
	Body *string `json:"body,omitempty"`
	// Parent category (null for root categories).
	Parent *Category `json:"parent,omitempty"`
	// Direct child categories.
	Children []*Category `json:"children"`
	// Products in this category (includes subcategory products).
	Products *ProductConnection `json:"products"`
	// Full path from root (e.g., ["electronics", "computers", "laptops"]).
	// Derived from the materialized ancestor path stored at admission time.
	Path []string `json:"path"`
	// Depth in tree (root = 0).
	Depth int32 `json:"depth"`
}

func (Category) IsNode() {}

// Globally unique identifier (format: [type]_[base62])
func (this Category) GetID() string { return this.ID }

// Selector for looking up a category by exactly one unique key.
type CategoryBy struct {
	ID   *string `json:"id,omitempty"`
	Slug *string `json:"slug,omitempty"`
	// Look up a git-backed category by its metadata.name (unique within namespace).
	Name *string `json:"name,omitempty"`
}

// A named status condition following the Kubernetes condition convention.
type CategoryCondition struct {
	Type               string    `json:"type"`
	Status             string    `json:"status"`
	ObservedGeneration int32     `json:"observedGeneration"`
	LastTransitionTime time.Time `json:"lastTransitionTime"`
	Reason             *string   `json:"reason,omitempty"`
	Message            *string   `json:"message,omitempty"`
}

// Connection type for paginated categories (Relay pattern)
type CategoryConnection struct {
	// List of category edges
	Edges []*CategoryEdge `json:"edges"`
	// Pagination information
	PageInfo *PageInfo `json:"pageInfo"`
	// Total count of categories
	TotalCount int32 `json:"totalCount"`
}

// Edge type for Category connection (Relay pattern)
type CategoryEdge struct {
	// Cursor for pagination
	Cursor string `json:"cursor"`
	// The category node
	Node *Category `json:"node"`
}

// Metadata for a CategoryTaxonomy resource.
// Author-supplied fields (name, namespace, labels, annotations) originate from the git file.
// System-assigned fields (uid through ownerReferences) are written by the ingest pipeline.
type CategoryObjectMeta struct {
	Name      string  `json:"name"`
	Namespace *string `json:"namespace,omitempty"`
	// Kubernetes-style labels. Use KeyValuePair list (JSON type alignment with Product deferred).
	Labels            []*KeyValuePair   `json:"labels"`
	Annotations       []*KeyValuePair   `json:"annotations"`
	UID               string            `json:"uid"`
	ResourceVersion   string            `json:"resourceVersion"`
	Generation        int32             `json:"generation"`
	CreationTimestamp time.Time         `json:"creationTimestamp"`
	Revision          *string           `json:"revision,omitempty"`
	OwnerReferences   []*OwnerReference `json:"ownerReferences"`
}

// Optimistic lock conflict for category
type CategoryOptimisticLockConflict struct {
	// TODO: Should this be a datetime?
	// Current version in database
	CurrentVersion time.Time `json:"currentVersion"`
	// TODO: Should this be a datetime?
	// Version client attempted to update
	AttemptedVersion time.Time `json:"attemptedVersion"`
	// Current state of the category
	Current *Category `json:"current"`
	// Diff between current and attempted
	Diff string `json:"diff"`
}

// Author-supplied specification for a CategoryTaxonomy resource.
type CategorySpec struct {
	Title     string                  `json:"title"`
	ParentRef *CatalogObjectReference `json:"parentRef,omitempty"`
	Media     []*MediaDefinition      `json:"media"`
}

// System-written status for a git-backed CategoryTaxonomy resource.
type CategoryTaxonomyStatus struct {
	ObservedGeneration  int32                     `json:"observedGeneration"`
	LastAppliedRevision string                    `json:"lastAppliedRevision"`
	Conditions          []*CategoryCondition      `json:"conditions"`
	Resolved            *ResolvedCategoryTaxonomy `json:"resolved,omitempty"`
}

// Collection represents a curated grouping of products (flat, non-hierarchical)
type Collection struct {
	// Globally unique identifier (format: coll_[base62])
	ID string `json:"id"`
	// Collection display name
	Name string `json:"name"`
	// URL-friendly slug (unique)
	Slug string `json:"slug"`
	// Display order for collection listing
	DisplayOrder int32 `json:"displayOrder"`
	// Products in this collection
	Products *ProductConnection `json:"products"`
	// Markdown body content (collection description with rich formatting)
	Body *string `json:"body,omitempty"`
	// Creation timestamp
	CreatedAt time.Time `json:"createdAt"`
	// Last modification timestamp
	UpdatedAt time.Time `json:"updatedAt"`
	// Number of products in this collection
	ProductCount int32 `json:"productCount"`
}

func (Collection) IsNode() {}

// Globally unique identifier (format: [type]_[base62])
func (this Collection) GetID() string { return this.ID }

// Selector for looking up a collection by exactly one unique key.
type CollectionBy struct {
	ID   *string `json:"id,omitempty"`
	Slug *string `json:"slug,omitempty"`
}

// Connection type for paginated collections (Relay pattern)
type CollectionConnection struct {
	// List of collection edges
	Edges []*CollectionEdge `json:"edges"`
	// Pagination information
	PageInfo *PageInfo `json:"pageInfo"`
	// Total count of collections
	TotalCount int32 `json:"totalCount"`
}

// Edge type for Collection connection (Relay pattern)
type CollectionEdge struct {
	// Cursor for pagination
	Cursor string `json:"cursor"`
	// The collection node
	Node *Collection `json:"node"`
}

// Optimistic lock conflict for collection
type CollectionOptimisticLockConflict struct {
	// TODO: Should this be a datetime?
	// Current version in database
	CurrentVersion time.Time `json:"currentVersion"`
	// TODO: Should this be a datetime?
	// Version client attempted to update
	AttemptedVersion time.Time `json:"attemptedVersion"`
	// Current state of the collection
	Current *Collection `json:"current"`
	// Diff between current and attempted
	Diff string `json:"diff"`
}

// Input for creating a category
type CreateCategoryInput struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Category name
	Name string `json:"name"`
	// URL-friendly slug (must be unique)
	Slug string `json:"slug"`
	// Parent category ID (null for root)
	ParentID *string `json:"parentId,omitempty"`
	// Display order
	DisplayOrder *int32 `json:"displayOrder,omitempty"`
	// Markdown body content
	Body *string `json:"body,omitempty"`
}

// Payload for createCategory mutation
type CreateCategoryPayload struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// The created category
	Category *Category `json:"category,omitempty"`
}

// Input for creating a collection
type CreateCollectionInput struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Collection name
	Name string `json:"name"`
	// URL-friendly slug (must be unique)
	Slug string `json:"slug"`
	// Display order
	DisplayOrder *int32 `json:"displayOrder,omitempty"`
	// Product IDs to include
	ProductIds []string `json:"productIds,omitempty"`
	// Markdown body content
	Body *string `json:"body,omitempty"`
}

// Payload for createCollection mutation
type CreateCollectionPayload struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// The created collection
	Collection *Collection `json:"collection,omitempty"`
}

// Input for creating a new namespace.
type CreateNamespaceInput struct {
	// Client mutation ID for request tracking (Relay pattern).
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// The human-readable identifier for the namespace.
	// Must be globally unique across all tiers.
	// DNS label format: lowercase alphanumeric and hyphens, 1–63 characters.
	// Cannot begin or end with a hyphen. Cannot be a reserved name.
	Identifier string `json:"identifier"`
	// Optional human-friendly display name.
	DisplayName *string `json:"displayName,omitempty"`
	// The tier of the namespace being created.
	// USER and ORGANISATION tiers may be created by any authenticated user.
	// ENTERPRISE tier requires isAdmin == true in the caller's JWT.
	Tier NamespaceTier `json:"tier"`
	// For ORGANISATION tier only: the identifier of the parent enterprise namespace.
	// The referenced namespace must exist and have tier ENTERPRISE.
	// Omit for USER and ENTERPRISE tier namespaces.
	ParentEnterpriseIdentifier *string `json:"parentEnterpriseIdentifier,omitempty"`
}

// Payload returned after successfully creating a namespace.
type CreateNamespacePayload struct {
	// Client mutation ID for request tracking (Relay pattern).
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// The newly created namespace.
	Namespace *Namespace `json:"namespace"`
}

type CreateRepositoryInput struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	NamespaceID      string  `json:"namespaceId"`
	Name             string  `json:"name"`
	DefaultBranch    *string `json:"defaultBranch,omitempty"`
}

type CreateRepositoryPayload struct {
	ClientMutationID *string     `json:"clientMutationId,omitempty"`
	Repository       *Repository `json:"repository"`
}

// Input for deleting a category
type DeleteCategoryInput struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Category ID to delete
	ID string `json:"id"`
}

// Payload for deleteCategory mutation
type DeleteCategoryPayload struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Deleted category ID
	DeletedCategoryID *string `json:"deletedCategoryId,omitempty"`
	// Orphaned product IDs (products that referenced this category)
	OrphanedProductIds []string `json:"orphanedProductIds,omitempty"`
}

// Input for deleting a collection
type DeleteCollectionInput struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Collection ID to delete
	ID string `json:"id"`
}

// Payload for deleteCollection mutation
type DeleteCollectionPayload struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Deleted collection ID
	DeletedCollectionID *string `json:"deletedCollectionId,omitempty"`
}

// Input for deleting a namespace.
type DeleteNamespaceInput struct {
	// Client mutation ID for request tracking (Relay pattern).
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// The identifier of the namespace to delete.
	// Deletion is blocked if any repositories exist within the namespace.
	// Requires the caller to be the namespace owner (createdBy) or isAdmin.
	Identifier string `json:"identifier"`
}

// Payload returned after successfully deleting a namespace.
type DeleteNamespacePayload struct {
	// Client mutation ID for request tracking (Relay pattern).
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// The identifier of the deleted namespace.
	DeletedIdentifier string `json:"deletedIdentifier"`
}

type DeleteRepositoryInput struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	RepositoryID     string  `json:"repositoryId"`
}

type DeleteRepositoryPayload struct {
	ClientMutationID    *string `json:"clientMutationId,omitempty"`
	DeletedRepositoryID string  `json:"deletedRepositoryId"`
}

type FileReference struct {
	Name     string `json:"name"`
	Kind     string `json:"kind"`
	Optional bool   `json:"optional"`
}

// A key-value pair for label maps.
type KeyValuePair struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// Login mutation input (Relay pattern)
type LoginInput struct {
	// Client mutation ID for request tracking (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Username
	Username string `json:"username"`
	// Password
	Password string `json:"password"`
}

// Login mutation payload (Relay pattern)
type LoginPayload struct {
	// Client mutation ID for request tracking (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Authentication session (token + user info)
	Session *AuthSession `json:"session,omitempty"`
}

// Logout mutation input (Relay pattern)
type LogoutInput struct {
	// Client mutation ID for request tracking (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

// Logout mutation payload (Relay pattern)
type LogoutPayload struct {
	// Client mutation ID for request tracking (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Success indicator
	Success bool `json:"success"`
}

type MediaDefinition struct {
	FileRef *FileReference `json:"fileRef"`
}

type Mutation struct {
}

// A namespace is the primary isolation boundary for repositories in GitStore.
// Namespaces are globally unique across all tiers — the same identifier cannot
// exist as both a user-space and an organisation namespace.
type Namespace struct {
	// Globally unique system-generated ID (UUID).
	ID string `json:"id"`
	// Human-readable identifier, globally unique across all tiers.
	// DNS label format: lowercase alphanumeric and hyphens, 1–63 characters.
	// Cannot begin or end with a hyphen.
	Identifier string `json:"identifier"`
	// Optional human-friendly display name.
	DisplayName *string `json:"displayName,omitempty"`
	// The tier of this namespace.
	Tier NamespaceTier `json:"tier"`
	// For ORGANISATION tier namespaces: the ID of the parent enterprise namespace,
	// if one was declared at creation time.
	// Null for USER and ENTERPRISE tier namespaces.
	ParentEnterpriseID *string `json:"parentEnterpriseId,omitempty"`
	// Timestamp when this namespace was created.
	CreatedAt time.Time `json:"createdAt"`
	// Username of the caller who created this namespace.
	CreatedBy string `json:"createdBy"`
	// Timestamp when this namespace was last modified.
	UpdatedAt time.Time `json:"updatedAt"`
	// Username of the caller who last modified this namespace.
	UpdatedBy string `json:"updatedBy"`
}

func (Namespace) IsNode() {}

// Globally unique identifier (format: [type]_[base62])
func (this Namespace) GetID() string { return this.ID }

// Selector for looking up a namespace by exactly one unique key.
type NamespaceBy struct {
	ID         *string `json:"id,omitempty"`
	Identifier *string `json:"identifier,omitempty"`
}

// Connection type for paginated namespaces (Relay pattern).
type NamespaceConnection struct {
	// List of namespace edges.
	Edges []*NamespaceEdge `json:"edges"`
	// Pagination information.
	PageInfo *PageInfo `json:"pageInfo"`
	// Total count of namespaces.
	TotalCount int32 `json:"totalCount"`
}

// Edge type for Namespace connection (Relay pattern).
type NamespaceEdge struct {
	// Cursor for pagination.
	Cursor string `json:"cursor"`
	// The namespace node.
	Node *Namespace `json:"node"`
}

type OwnerReference struct {
	APIVersion string `json:"apiVersion"`
	Kind       string `json:"kind"`
	Name       string `json:"name"`
	UID        string `json:"uid"`
}

// Information about pagination in a connection
type PageInfo struct {
	// When paginating forwards, are there more items?
	HasNextPage bool `json:"hasNextPage"`
	// When paginating backwards, are there more items?
	HasPreviousPage bool `json:"hasPreviousPage"`
	// When paginating backwards, the cursor to continue
	StartCursor *string `json:"startCursor,omitempty"`
	// When paginating forwards, the cursor to continue
	EndCursor *string `json:"endCursor,omitempty"`
}

type PriceRangeDefinition struct {
	CurrencyCode string          `json:"currencyCode"`
	Min          decimal.Decimal `json:"min"`
	Max          decimal.Decimal `json:"max"`
}

// Kubernetes-style product resource. All fields are read from the datastore,
// which holds the fully hydrated view populated by the post-push ingest pipeline.
type Product struct {
	ID         string             `json:"id"`
	APIVersion string             `json:"apiVersion"`
	Kind       string             `json:"kind"`
	Metadata   *ProductObjectMeta `json:"metadata"`
	Spec       *ProductSpec       `json:"spec"`
	Status     *ProductStatus     `json:"status,omitempty"`
}

func (Product) IsNode() {}

// Globally unique identifier (format: [type]_[base62])
func (this Product) GetID() string { return this.ID }

// Selector for a single product lookup. Exactly one field must be set.
type ProductBy struct {
	// Look up by globally unique Relay ID (encodes the product UID).
	ID *string `json:"id,omitempty"`
	// Look up by namespace identifier + product name (Kubernetes-style metadata.name).
	NamespacePath *ProductNamespacePath `json:"namespacePath,omitempty"`
}

type ProductCondition struct {
	Type               ProductConditionType `json:"type"`
	Status             ConditionStatus      `json:"status"`
	ObservedGeneration *int32               `json:"observedGeneration,omitempty"`
	LastTransitionTime time.Time            `json:"lastTransitionTime"`
	Reason             *string              `json:"reason,omitempty"`
	Message            *string              `json:"message,omitempty"`
}

// Connection type for paginated products (Relay pattern).
type ProductConnection struct {
	Edges      []*ProductEdge `json:"edges"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	TotalCount int32          `json:"totalCount"`
}

// Edge type for Product connection (Relay pattern).
type ProductEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Product `json:"node"`
}

// Composite selector: namespace identifier (human-readable slug) + product name.
type ProductNamespacePath struct {
	Namespace string `json:"namespace"`
	Name      string `json:"name"`
}

// Metadata for a product resource. Author-supplied fields (name, namespace,
// labels, annotations) originate from the git file. System-assigned fields
// (uid, resourceVersion, etc.) are written by the ingest pipeline.
type ProductObjectMeta struct {
	Name              string            `json:"name"`
	Namespace         string            `json:"namespace"`
	Labels            map[string]any    `json:"labels,omitempty"`
	Annotations       map[string]any    `json:"annotations,omitempty"`
	UID               string            `json:"uid"`
	ResourceVersion   string            `json:"resourceVersion"`
	Generation        int32             `json:"generation"`
	CreationTimestamp time.Time         `json:"creationTimestamp"`
	Revision          *string           `json:"revision,omitempty"`
	OwnerReferences   []*OwnerReference `json:"ownerReferences"`
}

type ProductOptionDefinition struct {
	Name   string   `json:"name"`
	Title  *string  `json:"title,omitempty"`
	Values []string `json:"values"`
}

type ProductSpec struct {
	Title       *string                    `json:"title,omitempty"`
	CategoryRef *CatalogObjectReference    `json:"categoryRef,omitempty"`
	Tags        []string                   `json:"tags"`
	Media       []*MediaDefinition         `json:"media"`
	Options     []*ProductOptionDefinition `json:"options"`
}

type ProductStatus struct {
	ObservedGeneration  int32                      `json:"observedGeneration"`
	LastAppliedRevision *string                    `json:"lastAppliedRevision,omitempty"`
	Conditions          []*ProductCondition        `json:"conditions"`
	Resolved            *ResolvedProductDefinition `json:"resolved,omitempty"`
}

// Input for publishing catalog changes
type PublishCatalogInput struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Release version tag (e.g., v1.0.0)
	Version string `json:"version"`
	// Release notes/commit message
	Message string `json:"message"`
}

// Payload for publishCatalog mutation
type PublishCatalogPayload struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// New catalog version
	CatalogVersion *CatalogVersion `json:"catalogVersion,omitempty"`
}

type Query struct {
}

// Refresh token mutation input (Relay pattern)
type RefreshTokenInput struct {
	// Client mutation ID for request tracking (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

// Refresh token mutation payload (Relay pattern)
type RefreshTokenPayload struct {
	// Client mutation ID for request tracking (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// New authentication session
	Session *AuthSession `json:"session,omitempty"`
}

type RenameRepositoryInput struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Relay ID of the repository to rename.
	RepositoryID string `json:"repositoryId"`
	NewName      string `json:"newName"`
}

type RenameRepositoryPayload struct {
	ClientMutationID *string     `json:"clientMutationId,omitempty"`
	Repository       *Repository `json:"repository"`
}

// Input for reordering categories (drag-and-drop)
type ReorderCategoriesInput struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Ordered list of category IDs within parent
	OrderedIds []string `json:"orderedIds"`
	// Parent category ID (null for root categories)
	ParentID *string `json:"parentId,omitempty"`
	// Category ID being moved (for tree restructure)
	MovedCategoryID *string `json:"movedCategoryId,omitempty"`
	// New parent ID for moved category (for tree restructure)
	NewParentID *string `json:"newParentId,omitempty"`
}

// Payload for reorderCategories mutation
type ReorderCategoriesPayload struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Updated categories
	Categories []*Category `json:"categories,omitempty"`
}

// Input for reordering collections (drag-and-drop)
type ReorderCollectionsInput struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Ordered list of collection IDs
	OrderedIds []string `json:"orderedIds"`
}

// Payload for reorderCollections mutation
type ReorderCollectionsPayload struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Updated collections
	Collections []*Collection `json:"collections,omitempty"`
}

// A git repository. Has a stable internal identity (id) that is independent of
// its human-readable namespace path. Renaming or transferring a repository does
// not change its id.
type Repository struct {
	// Globally unique Relay ID.
	ID string `json:"id"`
	// Human-readable name within the namespace (e.g., "my-catalog").
	// Mutable on rename.
	Name string `json:"name"`
	// The namespace that owns this repository.
	Namespace *Namespace `json:"namespace"`
	// Default branch name (e.g., "main").
	DefaultBranch string `json:"defaultBranch"`
	// Storage class tag. Reserved for future multi-storage-root use.
	StorageClass string `json:"storageClass"`
	// Absolute filesystem path derived from the internal repo_id using the fanout formula.
	// Informational — for operator use. Example: /data/01/96/0196f3a2-4b1c-7e9d-a301-8b2c4d5e6f7a.git
	StoragePath string    `json:"storagePath"`
	CreatedAt   time.Time `json:"createdAt"`
	CreatedBy   string    `json:"createdBy"`
	UpdatedAt   time.Time `json:"updatedAt"`
	UpdatedBy   string    `json:"updatedBy"`
}

func (Repository) IsNode() {}

// Globally unique identifier (format: [type]_[base62])
func (this Repository) GetID() string { return this.ID }

// Selector for a single repository lookup.
// Exactly one field must be set.
type RepositoryBy struct {
	// Look up by globally unique Relay ID.
	ID *string `json:"id,omitempty"`
	// Look up by namespace identifier + repository name.
	NamespacePath *RepositoryNamespacePath `json:"namespacePath,omitempty"`
}

type RepositoryConnection struct {
	Edges      []*RepositoryEdge `json:"edges"`
	PageInfo   *PageInfo         `json:"pageInfo"`
	TotalCount int32             `json:"totalCount"`
}

type RepositoryEdge struct {
	Cursor string      `json:"cursor"`
	Node   *Repository `json:"node"`
}

// Composite selector: namespace identifier (human-readable slug) + repository name.
type RepositoryNamespacePath struct {
	// Namespace identifier slug (e.g., "acme").
	Namespace string `json:"namespace"`
	// Repository name (e.g., "my-catalog").
	Name string `json:"name"`
}

type ResolvedCategoryDefinition struct {
	Name string   `json:"name"`
	Path []string `json:"path"`
}

// Controller-computed category hierarchy metadata.
type ResolvedCategoryTaxonomy struct {
	Depth        int32  `json:"depth"`
	AncestorPath string `json:"ancestorPath"`
	ChildCount   int32  `json:"childCount"`
	ProductCount int32  `json:"productCount"`
}

type ResolvedFileDefinition struct {
	Name        string  `json:"name"`
	URL         string  `json:"url"`
	ContentType *string `json:"contentType,omitempty"`
}

type ResolvedProductDefinition struct {
	Category          *ResolvedCategoryDefinition `json:"category,omitempty"`
	PriceRange        []*PriceRangeDefinition     `json:"priceRange"`
	TotalInventory    int32                       `json:"totalInventory"`
	VariantSummary    *VariantSummaryDefinition   `json:"variantSummary,omitempty"`
	DefaultVariantRef *CatalogObjectReference     `json:"defaultVariantRef,omitempty"`
	Media             []*ResolvedFileDefinition   `json:"media"`
}

type TransferRepositoryInput struct {
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Relay ID of the repository to transfer.
	RepositoryID string `json:"repositoryId"`
	// Relay ID of the destination namespace.
	TargetNamespaceID string `json:"targetNamespaceId"`
}

type TransferRepositoryPayload struct {
	ClientMutationID *string     `json:"clientMutationId,omitempty"`
	Repository       *Repository `json:"repository"`
}

// Input for updating a category
type UpdateCategoryInput struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Category ID to update
	ID string `json:"id"`
	// New name
	Name *string `json:"name,omitempty"`
	// New slug
	Slug *string `json:"slug,omitempty"`
	// New parent ID (null to make root, ID to change parent)
	ParentID *string `json:"parentId,omitempty"`
	// New display order
	DisplayOrder *int32 `json:"displayOrder,omitempty"`
	// New body content
	Body *string `json:"body,omitempty"`
	// TODO: Should this be a datetime?
	// Version for optimistic locking
	Version time.Time `json:"version"`
}

// Payload for updateCategory mutation
type UpdateCategoryPayload struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// The updated category
	Category *Category `json:"category,omitempty"`
	// Conflict information (if optimistic lock failed)
	Conflict *CategoryOptimisticLockConflict `json:"conflict,omitempty"`
}

// Input for updating a collection
type UpdateCollectionInput struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// Collection ID to update
	ID string `json:"id"`
	// New name
	Name *string `json:"name,omitempty"`
	// New slug
	Slug *string `json:"slug,omitempty"`
	// New display order
	DisplayOrder *int32 `json:"displayOrder,omitempty"`
	// New product IDs (replaces all)
	ProductIds []string `json:"productIds,omitempty"`
	// New body content
	Body *string `json:"body,omitempty"`
	// TODO: Should this be a datatime?
	// Version for optimistic locking
	Version time.Time `json:"version"`
}

// Payload for updateCollection mutation
type UpdateCollectionPayload struct {
	// Client mutation ID (Relay pattern)
	ClientMutationID *string `json:"clientMutationId,omitempty"`
	// The updated collection
	Collection *Collection `json:"collection,omitempty"`
	// Conflict information (if optimistic lock failed)
	Conflict *CollectionOptimisticLockConflict `json:"conflict,omitempty"`
}

// Authenticated user information
type User struct {
	// Username
	Username string `json:"username"`
	// Whether the user has admin privileges
	IsAdmin bool `json:"isAdmin"`
}

type VariantSummaryDefinition struct {
	Total       int32 `json:"total"`
	Ready       int32 `json:"ready"`
	Unavailable int32 `json:"unavailable"`
}

type ConditionStatus string

const (
	ConditionStatusTrue    ConditionStatus = "TRUE"
	ConditionStatusFalse   ConditionStatus = "FALSE"
	ConditionStatusUnknown ConditionStatus = "UNKNOWN"
)

var AllConditionStatus = []ConditionStatus{
	ConditionStatusTrue,
	ConditionStatusFalse,
	ConditionStatusUnknown,
}

func (e ConditionStatus) IsValid() bool {
	switch e {
	case ConditionStatusTrue, ConditionStatusFalse, ConditionStatusUnknown:
		return true
	}
	return false
}

func (e ConditionStatus) String() string {
	return string(e)
}

func (e *ConditionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConditionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConditionStatus", str)
	}
	return nil
}

func (e ConditionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConditionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConditionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Product inventory status
type InventoryStatus string

const (
	InventoryStatusInStock      InventoryStatus = "IN_STOCK"
	InventoryStatusOutOfStock   InventoryStatus = "OUT_OF_STOCK"
	InventoryStatusPreorder     InventoryStatus = "PREORDER"
	InventoryStatusDiscontinued InventoryStatus = "DISCONTINUED"
)

var AllInventoryStatus = []InventoryStatus{
	InventoryStatusInStock,
	InventoryStatusOutOfStock,
	InventoryStatusPreorder,
	InventoryStatusDiscontinued,
}

func (e InventoryStatus) IsValid() bool {
	switch e {
	case InventoryStatusInStock, InventoryStatusOutOfStock, InventoryStatusPreorder, InventoryStatusDiscontinued:
		return true
	}
	return false
}

func (e InventoryStatus) String() string {
	return string(e)
}

func (e *InventoryStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InventoryStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InventoryStatus", str)
	}
	return nil
}

func (e InventoryStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InventoryStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InventoryStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// The tier of a namespace, which determines ownership and repository capabilities.
type NamespaceTier string

const (
	// User-space namespace: owned by an individual, directly owns repositories.
	// Any authenticated user may create one.
	NamespaceTierUser NamespaceTier = "USER"
	// Organisation namespace: owned by a team or company, directly owns repositories.
	// May declare a parent enterprise at creation time.
	// Any authenticated user may create one.
	NamespaceTierOrganisation NamespaceTier = "ORGANISATION"
	// Enterprise namespace: organises organisations, does NOT own repositories directly.
	// Only callers with an elevated platform role (isAdmin) may create one.
	NamespaceTierEnterprise NamespaceTier = "ENTERPRISE"
)

var AllNamespaceTier = []NamespaceTier{
	NamespaceTierUser,
	NamespaceTierOrganisation,
	NamespaceTierEnterprise,
}

func (e NamespaceTier) IsValid() bool {
	switch e {
	case NamespaceTierUser, NamespaceTierOrganisation, NamespaceTierEnterprise:
		return true
	}
	return false
}

func (e NamespaceTier) String() string {
	return string(e)
}

func (e *NamespaceTier) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NamespaceTier(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NamespaceTier", str)
	}
	return nil
}

func (e NamespaceTier) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NamespaceTier) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NamespaceTier) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProductConditionType string

const (
	ProductConditionTypePublished         ProductConditionType = "PUBLISHED"
	ProductConditionTypeAdmissionAccepted ProductConditionType = "ADMISSION_ACCEPTED"
	ProductConditionTypeCategoryResolved  ProductConditionType = "CATEGORY_RESOLVED"
	ProductConditionTypeOptionsAccepted   ProductConditionType = "OPTIONS_ACCEPTED"
	ProductConditionTypeVariantsResolved  ProductConditionType = "VARIANTS_RESOLVED"
	ProductConditionTypeReady             ProductConditionType = "READY"
)

var AllProductConditionType = []ProductConditionType{
	ProductConditionTypePublished,
	ProductConditionTypeAdmissionAccepted,
	ProductConditionTypeCategoryResolved,
	ProductConditionTypeOptionsAccepted,
	ProductConditionTypeVariantsResolved,
	ProductConditionTypeReady,
}

func (e ProductConditionType) IsValid() bool {
	switch e {
	case ProductConditionTypePublished, ProductConditionTypeAdmissionAccepted, ProductConditionTypeCategoryResolved, ProductConditionTypeOptionsAccepted, ProductConditionTypeVariantsResolved, ProductConditionTypeReady:
		return true
	}
	return false
}

func (e ProductConditionType) String() string {
	return string(e)
}

func (e *ProductConditionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProductConditionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProductConditionType", str)
	}
	return nil
}

func (e ProductConditionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProductConditionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProductConditionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
