package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	"github.com/commerce-projects/gitstore/api/internal/catalog"
	"github.com/commerce-projects/gitstore/api/internal/graph/generated"
	"github.com/commerce-projects/gitstore/api/internal/graph/model"
)

// Products is the resolver for the products field.
func (r *categoryResolver) Products(ctx context.Context, obj *model.Category, first *int32, after *string, last *int32, before *string) (*model.ProductConnection, error) {
	// Get catalog
	cat, err := r.service.GetCatalog(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get catalog: %w", err)
	}

	// Get all products in this category and its subcategories
	products, err := getProductsInCategoryTree(cat, obj.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to get products: %w", err)
	}

	// Simple pagination: for now, return all products
	// TODO: Implement proper cursor-based pagination
	edges := make([]*model.ProductEdge, len(products))
	for i, p := range products {
		edges[i] = &model.ProductEdge{
			Cursor: p.ID, // Use ID as cursor for simplicity
			Node:   CatalogProductToGraphQL(p),
		}
	}

	// Calculate pagination info
	hasNextPage := false
	hasPreviousPage := false
	var startCursor, endCursor *string

	if len(edges) > 0 {
		start := edges[0].Cursor
		end := edges[len(edges)-1].Cursor
		startCursor = &start
		endCursor = &end
	}

	return &model.ProductConnection{
		Edges:      edges,
		TotalCount: int32(len(products)),
		PageInfo: &model.PageInfo{
			HasNextPage:     hasNextPage,
			HasPreviousPage: hasPreviousPage,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
	}, nil
}

// getProductsInCategoryTree returns all products in a category and its subcategories
func getProductsInCategoryTree(cat *catalog.Catalog, categoryID string) ([]*catalog.Product, error) {
	// Build category hierarchy to find all descendant categories
	cat.BuildCategoryHierarchy()

	// Collect all category IDs (current + descendants)
	categoryIDs := []string{categoryID}

	// Get the category to access its children
	category, ok := cat.GetCategory(categoryID)
	if !ok {
		return []*catalog.Product{}, nil
	}

	// Recursively collect all descendant category IDs
	collectDescendantIDs(category, &categoryIDs)

	// Filter products by category IDs
	allProducts := cat.AllProducts()
	result := make([]*catalog.Product, 0)

	for _, product := range allProducts {
		for _, catID := range categoryIDs {
			if product.CategoryID == catID {
				result = append(result, product)
				break
			}
		}
	}

	return result, nil
}

// collectDescendantIDs recursively collects IDs of all descendant categories
func collectDescendantIDs(category *catalog.Category, ids *[]string) {
	if category.Children == nil {
		return
	}

	for _, child := range category.Children {
		*ids = append(*ids, child.ID)
		collectDescendantIDs(child, ids)
	}
}

// Category returns generated.CategoryResolver implementation.
func (r *Resolver) Category() generated.CategoryResolver { return &categoryResolver{r} }

type categoryResolver struct{ *Resolver }
