package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	"github.com/gitstore-dev/gitstore/api/internal/graph/generated"
	"github.com/gitstore-dev/gitstore/api/internal/graph/model"
)

// Products is the resolver for the products field.
func (r *collectionResolver) Products(ctx context.Context, obj *model.Collection, first *int32, after *string, last *int32, before *string) (*model.ProductConnection, error) {
	// Get catalog
	cat, err := r.service.GetCatalog(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get catalog: %w", err)
	}

	// Find all products that belong to this collection
	products := getProductsInCollection(cat, obj.ID)

	// Simple pagination: for now, return all products
	// TODO: Implement proper cursor-based pagination
	edges := make([]*model.ProductEdge, len(products))
	for i, p := range products {
		edges[i] = &model.ProductEdge{
			Cursor: p.ID, // Use ID as cursor for simplicity
			Node:   CatalogProductToGraphQL(p),
		}
	}

	// Calculate pagination info
	hasNextPage := false
	hasPreviousPage := false
	var startCursor, endCursor *string

	if len(edges) > 0 {
		start := edges[0].Cursor
		end := edges[len(edges)-1].Cursor
		startCursor = &start
		endCursor = &end
	}

	return &model.ProductConnection{
		Edges:      edges,
		TotalCount: int32(len(products)),
		PageInfo: &model.PageInfo{
			HasNextPage:     hasNextPage,
			HasPreviousPage: hasPreviousPage,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
	}, nil
}

// Collection returns generated.CollectionResolver implementation.
func (r *Resolver) Collection() generated.CollectionResolver { return &collectionResolver{r} }

type collectionResolver struct{ *Resolver }
