package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"time"

	"github.com/commerce-projects/gitstore/api/internal/graph/generated"
	"github.com/commerce-projects/gitstore/api/internal/graph/model"
	"github.com/commerce-projects/gitstore/api/internal/graph/scalar"
	"github.com/google/uuid"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.CreateProductPayload, error) {
	// Build input map for service
	serviceInput := map[string]interface{}{
		"title": input.Title,
		"price": float64(input.Price),
	}

	if input.Sku != nil {
		serviceInput["sku"] = *input.Sku
	}
	if input.Currency != nil {
		serviceInput["currency"] = *input.Currency
	}
	if input.Body != nil {
		serviceInput["body"] = *input.Body
	}
	if input.InventoryStatus != nil {
		serviceInput["inventoryStatus"] = string(*input.InventoryStatus)
	}
	if input.InventoryQuantity != nil {
		serviceInput["inventoryQuantity"] = *input.InventoryQuantity
	}
	if input.Images != nil {
		serviceInput["images"] = input.Images
	}
	if input.Metadata != nil {
		serviceInput["metadata"] = input.Metadata
	}

	// Create product via service
	catalogProduct, err := r.service.CreateProduct(ctx, serviceInput)
	if err != nil {
		return nil, fmt.Errorf("failed to create product: %w", err)
	}

	// Convert to GraphQL model
	product := CatalogProductToGraphQL(catalogProduct)

	return &model.CreateProductPayload{
		ClientMutationID: input.ClientMutationID,
		Product:          product,
	}, nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, input model.UpdateProductInput) (*model.UpdateProductPayload, error) {
	// TODO: Implement proper git-backed product update with optimistic locking
	// For now, return mock response to unblock E2E tests
	var price scalar.Decimal
	if input.Price != nil {
		price = *input.Price
	}

	product := &model.Product{
		ID:                input.ID,
		Title:             stringOrDefault(input.Title, "Updated Product"),
		Sku:               stringOrDefault(input.Sku, "updated-sku"),
		Price:             price,
		Currency:          stringOrDefault(input.Currency, "USD"),
		Body:              input.Body,
		InventoryStatus:   derefInventoryStatus(input.InventoryStatus),
		InventoryQuantity: input.InventoryQuantity,
		Category:          nil, // TODO: lookup category
		Collections:       []*model.Collection{}, // TODO: lookup collections
		Images:            input.Images,
		Metadata:          input.Metadata,
		CreatedAt:         time.Now().Add(-24 * time.Hour),
		UpdatedAt:         time.Now(),
	}

	return &model.UpdateProductPayload{
		ClientMutationID: input.ClientMutationID,
		Product:          product,
		Conflict:         nil, // No conflicts in mock
	}, nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, input model.DeleteProductInput) (*model.DeleteProductPayload, error) {
	// TODO: Implement proper git-backed product deletion
	// For now, return mock response to unblock E2E tests
	idCopy := input.ID
	return &model.DeleteProductPayload{
		ClientMutationID: input.ClientMutationID,
		DeletedProductID: &idCopy,
	}, nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.CreateCategoryInput) (*model.CreateCategoryPayload, error) {
	// TODO: Implement proper git-backed category creation
	// For now, return mock response to unblock E2E tests
	category := &model.Category{
		ID:           generateID(),
		Name:         input.Name,
		Slug:         input.Slug,
		Body:         input.Body,
		Parent:       nil, // TODO: lookup parent
		Children:     []*model.Category{},
		DisplayOrder: intOrDefault(input.DisplayOrder, 0),
		Products:     &model.ProductConnection{Edges: []*model.ProductEdge{}, PageInfo: &model.PageInfo{}},
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	}

	return &model.CreateCategoryPayload{
		ClientMutationID: input.ClientMutationID,
		Category:         category,
	}, nil
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, input model.UpdateCategoryInput) (*model.UpdateCategoryPayload, error) {
	// TODO: Implement proper git-backed category update
	// For now, return mock response to unblock E2E tests
	category := &model.Category{
		ID:           input.ID,
		Name:         stringOrDefault(input.Name, "Updated Category"),
		Slug:         stringOrDefault(input.Slug, "updated-category"),
		Body:         input.Body,
		Parent:       nil, // TODO: lookup parent
		Children:     []*model.Category{},
		DisplayOrder: intOrDefault(input.DisplayOrder, 0),
		Products:     &model.ProductConnection{Edges: []*model.ProductEdge{}, PageInfo: &model.PageInfo{}},
		CreatedAt:    time.Now().Add(-24 * time.Hour),
		UpdatedAt:    time.Now(),
	}

	return &model.UpdateCategoryPayload{
		ClientMutationID: input.ClientMutationID,
		Category:         category,
		Conflict:         nil,
	}, nil
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, input model.DeleteCategoryInput) (*model.DeleteCategoryPayload, error) {
	// TODO: Implement proper git-backed category deletion
	// For now, return mock response to unblock E2E tests
	idCopy := input.ID
	return &model.DeleteCategoryPayload{
		ClientMutationID:  input.ClientMutationID,
		DeletedCategoryID: &idCopy,
	}, nil
}

// ReorderCategories is the resolver for the reorderCategories field.
func (r *mutationResolver) ReorderCategories(ctx context.Context, input model.ReorderCategoriesInput) (*model.ReorderCategoriesPayload, error) {
	// TODO: Implement proper git-backed category reordering
	// For now, return mock response with updated display orders
	categories := make([]*model.Category, len(input.OrderedIds))
	for i, id := range input.OrderedIds {
		categories[i] = &model.Category{
			ID:           id,
			Name:         fmt.Sprintf("Category %d", i+1),
			Slug:         fmt.Sprintf("category-%d", i+1),
			DisplayOrder: int32(i),
			Children:     []*model.Category{},
			Products:     &model.ProductConnection{Edges: []*model.ProductEdge{}, PageInfo: &model.PageInfo{}},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		}
	}

	return &model.ReorderCategoriesPayload{
		ClientMutationID: input.ClientMutationID,
		Categories:       categories,
	}, nil
}

// CreateCollection is the resolver for the createCollection field.
func (r *mutationResolver) CreateCollection(ctx context.Context, input model.CreateCollectionInput) (*model.CreateCollectionPayload, error) {
	collection := &model.Collection{
		ID:           generateID(),
		Name:         input.Name,
		Slug:         input.Slug,
		Body:         input.Body,
		DisplayOrder: intOrDefault(input.DisplayOrder, 0),
		Products:     &model.ProductConnection{Edges: []*model.ProductEdge{}, PageInfo: &model.PageInfo{}},
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	}
	return &model.CreateCollectionPayload{
		ClientMutationID: input.ClientMutationID,
		Collection:       collection,
	}, nil
}

// UpdateCollection is the resolver for the updateCollection field.
func (r *mutationResolver) UpdateCollection(ctx context.Context, input model.UpdateCollectionInput) (*model.UpdateCollectionPayload, error) {
	collection := &model.Collection{
		ID:           input.ID,
		Name:         stringOrDefault(input.Name, "Updated Collection"),
		Slug:         stringOrDefault(input.Slug, "updated-collection"),
		Body:         input.Body,
		DisplayOrder: intOrDefault(input.DisplayOrder, 0),
		Products:     &model.ProductConnection{Edges: []*model.ProductEdge{}, PageInfo: &model.PageInfo{}},
		CreatedAt:    time.Now().Add(-24 * time.Hour),
		UpdatedAt:    time.Now(),
	}
	return &model.UpdateCollectionPayload{
		ClientMutationID: input.ClientMutationID,
		Collection:       collection,
		Conflict:         nil,
	}, nil
}

// DeleteCollection is the resolver for the deleteCollection field.
func (r *mutationResolver) DeleteCollection(ctx context.Context, input model.DeleteCollectionInput) (*model.DeleteCollectionPayload, error) {
	idCopy := input.ID
	return &model.DeleteCollectionPayload{
		ClientMutationID:    input.ClientMutationID,
		DeletedCollectionID: &idCopy,
	}, nil
}

// ReorderCollections is the resolver for the reorderCollections field.
func (r *mutationResolver) ReorderCollections(ctx context.Context, input model.ReorderCollectionsInput) (*model.ReorderCollectionsPayload, error) {
	collections := make([]*model.Collection, len(input.OrderedIds))
	for i, id := range input.OrderedIds {
		collections[i] = &model.Collection{
			ID:           id,
			Name:         fmt.Sprintf("Collection %d", i+1),
			Slug:         fmt.Sprintf("collection-%d", i+1),
			DisplayOrder: int32(i),
			Products:     &model.ProductConnection{Edges: []*model.ProductEdge{}, PageInfo: &model.PageInfo{}},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		}
	}
	return &model.ReorderCollectionsPayload{
		ClientMutationID: input.ClientMutationID,
		Collections:      collections,
	}, nil
}

// PublishCatalog is the resolver for the publishCatalog field.
func (r *mutationResolver) PublishCatalog(ctx context.Context, input model.PublishCatalogInput) (*model.PublishCatalogPayload, error) {
	message := input.Message
	if message == "" {
		message = "Published catalog"
	}
	version := &model.CatalogVersion{
		Tag:         input.Version,
		Commit:      "abc123def456",
		PublishedAt: time.Now(),
		Message:     &message,
		Stats:       nil, // TODO: calculate stats
	}
	return &model.PublishCatalogPayload{
		ClientMutationID: input.ClientMutationID,
		CatalogVersion:   version,
	}, nil
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (model.Node, error) {
	// TODO: Implement proper node resolution
	return nil, fmt.Errorf("node not found")
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []string) ([]model.Node, error) {
	// TODO: Implement proper nodes resolution
	return []model.Node{}, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, sku string) (*model.Product, error) {
	// TODO: Implement proper product lookup by SKU
	return nil, nil
}

// ProductByID is the resolver for the productById field.
func (r *queryResolver) ProductByID(ctx context.Context, id string) (*model.Product, error) {
	// TODO: Implement proper product lookup by ID
	return nil, nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, first *int32, after *string, last *int32, before *string, filter *model.ProductFilter) (*model.ProductConnection, error) {
	// TODO: Implement proper product querying from git
	// For now, return empty list to unblock E2E tests
	return &model.ProductConnection{
		Edges:      []*model.ProductEdge{},
		TotalCount: 0,
		PageInfo: &model.PageInfo{
			HasNextPage:     false,
			HasPreviousPage: false,
			StartCursor:     nil,
			EndCursor:       nil,
		},
	}, nil
}

// Category returns a category by slug
func (r *queryResolver) Category(ctx context.Context, slug string) (*model.Category, error) {
	// TODO: Implement proper category lookup by slug
	return nil, nil
}

// CategoryByID is the resolver for the categoryById field.
func (r *queryResolver) CategoryByID(ctx context.Context, id string) (*model.Category, error) {
	// TODO: Implement proper category lookup by ID
	return nil, nil
}

// Categories returns all categories in hierarchical structure
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	// TODO: Implement proper category querying from git
	// For now, return empty list to unblock E2E tests
	return []*model.Category{}, nil
}

// Collection returns a collection by slug
func (r *queryResolver) Collection(ctx context.Context, slug string) (*model.Collection, error) {
	// TODO: Implement proper collection lookup by slug
	return nil, nil
}

// CollectionByID is the resolver for the collectionById field.
func (r *queryResolver) CollectionByID(ctx context.Context, id string) (*model.Collection, error) {
	// TODO: Implement proper collection lookup by ID
	return nil, nil
}

// Collections returns all collections
func (r *queryResolver) Collections(ctx context.Context) ([]*model.Collection, error) {
	// TODO: Implement proper collection querying
	return []*model.Collection{}, nil
}

// CatalogVersion is the resolver for the catalogVersion field.
func (r *queryResolver) CatalogVersion(ctx context.Context) (*model.CatalogVersion, error) {
	// TODO: Implement proper catalog version lookup
	return &model.CatalogVersion{
		Tag:         "v1.0.0",
		Commit:      "abc123",
		PublishedAt: time.Now(),
		Message:     nil,
		Stats:       nil,
	}, nil
}

// Mutation returns generated.MutationResolver interface
func (r *Resolver) Mutation() generated.MutationResolver {
	return &mutationResolver{r}
}

// Query returns generated.QueryResolver interface
func (r *Resolver) Query() generated.QueryResolver {
	return &queryResolver{r}
}

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// Helper function to generate unique IDs
func generateID() string {
	return uuid.New().String()
}

// Helper functions for optional field handling
func stringOrDefault(s *string, def string) string {
	if s != nil {
		return *s
	}
	return def
}

func floatOrDefault(f *float64, def float64) float64 {
	if f != nil {
		return *f
	}
	return def
}

func intOrDefault(i *int32, def int32) int32 {
	if i != nil {
		return *i
	}
	return def
}

func derefInventoryStatus(s *model.InventoryStatus) model.InventoryStatus {
	if s != nil {
		return *s
	}
	return model.InventoryStatusInStock
}
