package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"sort"

	"github.com/commerce-projects/gitstore/api/internal/graph/model"
	"github.com/commerce-projects/gitstore/api/internal/models"
	"go.uber.org/zap"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.CreateProductPayload, error) {
	panic(fmt.Errorf("not implemented: CreateProduct - createProduct"))
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, input model.UpdateProductInput) (*model.UpdateProductPayload, error) {
	panic(fmt.Errorf("not implemented: UpdateProduct - updateProduct"))
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, input model.DeleteProductInput) (*model.DeleteProductPayload, error) {
	panic(fmt.Errorf("not implemented: DeleteProduct - deleteProduct"))
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.CreateCategoryInput) (*model.CreateCategoryPayload, error) {
	panic(fmt.Errorf("not implemented: CreateCategory - createCategory"))
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, input model.UpdateCategoryInput) (*model.UpdateCategoryPayload, error) {
	panic(fmt.Errorf("not implemented: UpdateCategory - updateCategory"))
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, input model.DeleteCategoryInput) (*model.DeleteCategoryPayload, error) {
	panic(fmt.Errorf("not implemented: DeleteCategory - deleteCategory"))
}

// ReorderCategories is the resolver for the reorderCategories field.
func (r *mutationResolver) ReorderCategories(ctx context.Context, input model.ReorderCategoriesInput) (*model.ReorderCategoriesPayload, error) {
	panic(fmt.Errorf("not implemented: ReorderCategories - reorderCategories"))
}

// CreateCollection is the resolver for the createCollection field.
func (r *mutationResolver) CreateCollection(ctx context.Context, input model.CreateCollectionInput) (*model.CreateCollectionPayload, error) {
	panic(fmt.Errorf("not implemented: CreateCollection - createCollection"))
}

// UpdateCollection is the resolver for the updateCollection field.
func (r *mutationResolver) UpdateCollection(ctx context.Context, input model.UpdateCollectionInput) (*model.UpdateCollectionPayload, error) {
	panic(fmt.Errorf("not implemented: UpdateCollection - updateCollection"))
}

// DeleteCollection is the resolver for the deleteCollection field.
func (r *mutationResolver) DeleteCollection(ctx context.Context, input model.DeleteCollectionInput) (*model.DeleteCollectionPayload, error) {
	panic(fmt.Errorf("not implemented: DeleteCollection - deleteCollection"))
}

// ReorderCollections is the resolver for the reorderCollections field.
func (r *mutationResolver) ReorderCollections(ctx context.Context, input model.ReorderCollectionsInput) (*model.ReorderCollectionsPayload, error) {
	panic(fmt.Errorf("not implemented: ReorderCollections - reorderCollections"))
}

// PublishCatalog is the resolver for the publishCatalog field.
func (r *mutationResolver) PublishCatalog(ctx context.Context, input model.PublishCatalogInput) (*model.PublishCatalogPayload, error) {
	panic(fmt.Errorf("not implemented: PublishCatalog - publishCatalog"))
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (model.Node, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []string) ([]model.Node, error) {
	panic(fmt.Errorf("not implemented: Nodes - nodes"))
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, sku string) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: Product - product"))
}

// ProductByID is the resolver for the productById field.
func (r *queryResolver) ProductByID(ctx context.Context, id string) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: ProductByID - productById"))
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, first *int32, after *string, last *int32, before *string, filter *model.ProductFilter) (*model.ProductConnection, error) {
	panic(fmt.Errorf("not implemented: Products - products"))
}

// Category returns a category by slug
func (r *queryResolver) Category(ctx context.Context, slug string) (*models.Category, error) {
	r.logger.Debug("Fetching category by slug", zap.String("slug", slug))

	// Get catalog from cache
	cat, err := r.cache.Get(ctx)
	if err != nil {
		r.logger.Error("Failed to load catalog", zap.Error(err))
		return nil, err
	}

	// Get category by slug
	catalogCat, ok := cat.GetCategoryBySlug(slug)
	if !ok {
		r.logger.Debug("Category not found", zap.String("slug", slug))
		return nil, nil
	}

	// Build full tree to get parent/children relationships
	tree := buildCategoryTree(cat.AllCategories())

	// Get the category with relationships from tree
	modelCat, ok := tree.GetCategory(catalogCat.ID)
	if !ok {
		// This shouldn't happen, but handle gracefully
		modelCat = catalogCategoryToModel(catalogCat)
	}

	r.logger.Debug("Category found",
		zap.String("slug", slug),
		zap.String("id", modelCat.ID),
	)

	return modelCat, nil
}

// CategoryByID is the resolver for the categoryById field.
func (r *queryResolver) CategoryByID(ctx context.Context, id string) (*model.Category, error) {
	panic(fmt.Errorf("not implemented: CategoryByID - categoryById"))
}

// Categories returns all categories in hierarchical structure
func (r *queryResolver) Categories(ctx context.Context) ([]*models.Category, error) {
	r.logger.Debug("Fetching all categories")

	// Get catalog from cache
	cat, err := r.cache.Get(ctx)
	if err != nil {
		r.logger.Error("Failed to load catalog", zap.Error(err))
		return nil, err
	}

	// Get all categories from catalog
	catalogCategories := cat.AllCategories()

	// Build category tree
	tree := models.NewCategoryTree()
	for _, cat := range catalogCategories {
		modelCat := catalogCategoryToModel(cat)
		tree.AddCategory(modelCat)
	}
	tree.Build()

	// Return all categories in flat list (sorted by hierarchy)
	result := tree.GetFlatList()

	r.logger.Debug("Categories fetched",
		zap.Int("count", len(result)),
	)

	return result, nil
}

// Collection returns a collection by slug
func (r *queryResolver) Collection(ctx context.Context, slug string) (*models.Collection, error) {
	r.logger.Debug("Fetching collection by slug", zap.String("slug", slug))

	// Get catalog from cache
	cat, err := r.cache.Get(ctx)
	if err != nil {
		r.logger.Error("Failed to load catalog", zap.Error(err))
		return nil, err
	}

	// Get collection by slug
	catalogColl, ok := cat.GetCollectionBySlug(slug)
	if !ok {
		r.logger.Debug("Collection not found", zap.String("slug", slug))
		return nil, nil
	}

	modelColl := catalogCollectionToModel(catalogColl)

	r.logger.Debug("Collection found",
		zap.String("slug", slug),
		zap.String("id", modelColl.ID),
	)

	return modelColl, nil
}

// CollectionByID is the resolver for the collectionById field.
func (r *queryResolver) CollectionByID(ctx context.Context, id string) (*model.Collection, error) {
	panic(fmt.Errorf("not implemented: CollectionByID - collectionById"))
}

// Collections returns all collections
func (r *queryResolver) Collections(ctx context.Context) ([]*models.Collection, error) {
	r.logger.Debug("Fetching all collections")

	// Get catalog from cache
	cat, err := r.cache.Get(ctx)
	if err != nil {
		r.logger.Error("Failed to load catalog", zap.Error(err))
		return nil, err
	}

	// Get all collections from catalog
	catalogCollections := cat.AllCollections()

	// Convert to model collections
	result := make([]*models.Collection, 0, len(catalogCollections))
	for _, coll := range catalogCollections {
		result = append(result, catalogCollectionToModel(coll))
	}

	// Sort by display order
	sort.Slice(result, func(i, j int) bool {
		return result[i].DisplayOrder < result[j].DisplayOrder
	})

	r.logger.Debug("Collections fetched",
		zap.Int("count", len(result)),
	)

	return result, nil
}

// CatalogVersion is the resolver for the catalogVersion field.
func (r *queryResolver) CatalogVersion(ctx context.Context) (*model.CatalogVersion, error) {
	panic(fmt.Errorf("not implemented: CatalogVersion - catalogVersion"))
}

// Mutation returns MutationResolver interface
func (r *Resolver) Mutation() MutationResolver {
	return &mutationResolver{r}
}

// Query returns QueryResolver interface
func (r *Resolver) Query() QueryResolver {
	return &queryResolver{r}
}

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
