package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"

	"github.com/gitstore-dev/gitstore/api/internal/catalog"
	"github.com/gitstore-dev/gitstore/api/internal/datastore"
	"github.com/gitstore-dev/gitstore/api/internal/graph/generated"
	"github.com/gitstore-dev/gitstore/api/internal/graph/model"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.uber.org/zap"
)

// Parent is the resolver for the parent field.
func (r *categoryResolver) Parent(ctx context.Context, obj *model.Category) (*model.Category, error) {
	if obj == nil || obj.Status == nil || obj.Status.Resolved == nil || obj.Spec == nil || obj.Spec.ParentRef == nil || obj.Metadata == nil {
		return nil, nil
	}
	if !categoryConditionTrue(obj.Status.Conditions, catalog.ConditionParentResolved) {
		return nil, nil
	}
	parent, err := r.store.GetCategoryTaxonomyByName(ctx, obj.Metadata.Namespace, obj.Spec.ParentRef.Name)
	if errors.Is(err, datastore.ErrNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("load parent category: %w", err)
	}
	return DatastoreCategoryTaxonomyToGraphQL(parent), nil
}

// Children is the resolver for the children field.
func (r *categoryResolver) Children(ctx context.Context, obj *model.Category) ([]*model.Category, error) {
	if obj == nil || obj.Status == nil || obj.Status.Resolved == nil || obj.Metadata == nil {
		return []*model.Category{}, nil
	}
	maxDepth := int32(1)
	conn, err := r.service.listCategoryDescendants(ctx, obj.Metadata.Namespace, &model.CategoryFilterInput{
		DescendantOf: obj.Metadata.Name, MaxDepth: &maxDepth,
	}, datastore.PageParams{First: categoryFilterMaxPage})
	if err != nil {
		return nil, err
	}
	children := make([]*model.Category, 0, len(conn.Edges))
	for _, edge := range conn.Edges {
		children = append(children, edge.Node)
	}
	return children, nil
}

// Products is the resolver for the products field.
func (r *categoryResolver) Products(ctx context.Context, obj *model.Category, first *int32, after *string, last *int32, before *string) (*model.ProductConnection, error) {
	_, err := decodeNodeIDAs(nodeKindCategory, obj.ID)
	if err != nil {
		return nil, err
	}
	// TODO: Add category-scoped product listing to the datastore interface.
	// For now, return all products paginated (filter by category will be added later).
	params := toPageParams(first, after, last, before)
	result, err := r.service.GetProducts(ctx, "", params)
	if err != nil {
		return nil, fmt.Errorf("failed to get products: %w", err)
	}
	return BuildProductConnection(result), nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.CreateCategoryInput) (*model.CreateCategoryPayload, error) {
	category, err := r.service.CommitCategoryManifest(ctx, CategoryManifestInput{
		APIVersion: input.APIVersion, Kind: input.Kind, Metadata: input.Metadata, Spec: input.Spec, Body: input.Body,
	}, callerUsernameOrAnon(ctx, r), true)
	if err != nil {
		return nil, categoryMutationGraphQLError(err)
	}
	return &model.CreateCategoryPayload{Category: DatastoreCategoryTaxonomyToGraphQL(category)}, nil
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, input model.UpdateCategoryInput) (*model.UpdateCategoryPayload, error) {
	category, err := r.service.CommitCategoryManifest(ctx, CategoryManifestInput{
		APIVersion: input.APIVersion, Kind: input.Kind, Metadata: input.Metadata, Spec: input.Spec, Body: input.Body,
	}, callerUsernameOrAnon(ctx, r), false)
	if err != nil {
		return nil, categoryMutationGraphQLError(err)
	}
	return &model.UpdateCategoryPayload{Category: DatastoreCategoryTaxonomyToGraphQL(category)}, nil
}

// DeleteCategory is the resolver for the existing CategoryTaxonomy-backed
// deleteCategory API. It starts (or returns) the shared foreground lifecycle.
func (r *mutationResolver) DeleteCategory(ctx context.Context, input model.DeleteCategoryInput) (*model.DeleteCategoryPayload, error) {
	uid, err := decodeNodeIDAs(nodeKindCategory, input.ID)
	if err != nil {
		return nil, err
	}
	category, outcome, err := r.service.DeleteCategoryManifest(ctx, uid, callerUsernameOrAnon(ctx, r))
	if err != nil {
		return nil, categoryMutationGraphQLError(err)
	}
	return &model.DeleteCategoryPayload{Category: DatastoreCategoryTaxonomyToGraphQL(category), Outcome: outcome}, nil
}

// CompleteCategoryDeletion is the resolver for the completeCategoryDeletion field.
func (r *mutationResolver) CompleteCategoryDeletion(ctx context.Context, input model.CompleteCategoryDeletionInput) (*model.CompleteCategoryDeletionPayload, error) {
	deleted, err := r.completeCategoryDeletion(ctx, input.Namespace, input.Name, input.ResourceVersion)
	if err != nil {
		return nil, err
	}
	payload := &model.CompleteCategoryDeletionPayload{}
	if deleted != nil {
		id := mustEncodeNodeID(nodeKindCategory, deleted.UID)
		payload.ID = &id
	}
	return payload, nil
}

// UpdateCategoryStatus is the resolver for the updateCategoryStatus field.
func (r *mutationResolver) UpdateCategoryStatus(ctx context.Context, input model.UpdateCategoryStatusInput) (*model.UpdateCategoryStatusPayload, error) {
	if input.DecoupleProducts != nil && *input.DecoupleProducts {
		_, hasMore, err := r.service.DecoupleCategoryProducts(ctx, input.Namespace, input.Name, input.ResourceVersion)
		if errors.Is(err, datastore.ErrConflict) {
			current, getErr := r.store.GetCategoryTaxonomyByName(ctx, input.Namespace, input.Name)
			if getErr != nil {
				return nil, gqlerror.Errorf("decouple Products conflict, and could not re-fetch current version: %v", getErr)
			}
			return nil, statusConflictError("CategoryTaxonomy", input.Namespace, input.Name, current.ResourceVersion)
		}
		if err != nil {
			return nil, err
		}
		return &model.UpdateCategoryStatusPayload{HasMoreProductDependents: hasMore}, nil
	}
	if input.CompleteDeletion != nil && *input.CompleteDeletion {
		if _, err := r.completeCategoryDeletion(ctx, input.Namespace, input.Name, input.ResourceVersion); err != nil {
			return nil, err
		}
		return &model.UpdateCategoryStatusPayload{}, nil
	}
	patch := toCategoryTaxonomyStatusPatch(input)
	updated, err := r.store.UpdateCategoryTaxonomyStatus(ctx, input.Namespace, input.Name, patch)
	if err != nil {
		if errors.Is(err, datastore.ErrConflict) {
			StatusWriteConflictsTotal.WithLabelValues("CategoryTaxonomy").Inc()
			r.logger.Info("status write conflict",
				zap.String("kind", "CategoryTaxonomy"),
				zap.String("namespace", input.Namespace),
				zap.String("name", input.Name))
			current, getErr := r.store.GetCategoryTaxonomyByName(ctx, input.Namespace, input.Name)
			if getErr != nil {
				return nil, gqlerror.Errorf("status update conflict, and could not re-fetch current version: %v", getErr)
			}
			return nil, statusConflictError("CategoryTaxonomy", input.Namespace, input.Name, current.ResourceVersion)
		}
		if errors.Is(err, datastore.ErrNotFound) {
			return nil, &gqlerror.Error{
				Message:    fmt.Sprintf("CategoryTaxonomy %s/%s not found", input.Namespace, input.Name),
				Extensions: map[string]any{"code": "NOT_FOUND"},
			}
		}
		return nil, gqlerror.Errorf("update category status: %v", err)
	}
	return &model.UpdateCategoryStatusPayload{Category: DatastoreCategoryTaxonomyToGraphQL(updated)}, nil
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, by model.CategoryBy) (*model.Category, error) {
	switch {
	case by.ID != nil:
		categoryUID, err := decodeNodeIDAs(nodeKindCategory, *by.ID)
		if err != nil {
			return nil, err
		}
		c, err := r.service.GetCategoryTaxonomyByUID(ctx, categoryUID)
		if err != nil {
			return nil, nil
		}
		return DatastoreCategoryTaxonomyToGraphQL(c), nil
	case by.NamespacePath != nil:
		c, err := r.service.GetCategoryTaxonomyByName(ctx, by.NamespacePath.Namespace, by.NamespacePath.Name)
		if err != nil {
			return nil, nil
		}
		return DatastoreCategoryTaxonomyToGraphQL(c), nil
	default:
		return nil, gqlerror.Errorf("CategoryBy: exactly one selector required")
	}
}

// Categories returns categories as a Relay connection.
func (r *queryResolver) Categories(ctx context.Context, namespace string, filter *model.CategoryFilterInput, first *int32, after *string, last *int32, before *string) (*model.CategoryConnection, error) {
	params := toPageParams(first, after, last, before)
	if filter != nil {
		return r.service.listCategoryDescendants(ctx, namespace, filter, params)
	}
	result, err := r.service.GetCategoryTaxonomies(ctx, namespace, params)
	if err != nil {
		if errors.Is(err, datastore.ErrInvalidArgument) {
			return nil, badCategoryListArgument("cursor belongs to a filtered category list")
		}
		return nil, fmt.Errorf("failed to get categories: %w", err)
	}
	return BuildCategoryConnection(result), nil
}

// WatchCategories is the resolver for the watchCategories field.
func (r *subscriptionResolver) WatchCategories(ctx context.Context, namespace *string, selector *model.LabelSelectorInput, resourceVersion *string) (<-chan *model.CategoryWatchEvent, error) {
	return watchCatalogJournal(ctx, r.Resolver, "CategoryTaxonomy", namespace, selector, resourceVersion, "typed", categoryJournalEventToGraphQL)
}

// Category returns generated.CategoryResolver implementation.
func (r *Resolver) Category() generated.CategoryResolver { return &categoryResolver{r} }

type categoryResolver struct{ *Resolver }
