package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"

	"github.com/gitstore-dev/gitstore/api/internal/datastore"
	"github.com/gitstore-dev/gitstore/api/internal/graph/model"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// File is the resolver for the file field.
func (r *queryResolver) File(ctx context.Context, namespace string, name string) (*model.File, error) {
	if namespace == "" || name == "" {
		return nil, &gqlerror.Error{Message: "File namespace and name are required", Extensions: map[string]any{"code": "BAD_USER_INPUT"}}
	}
	file, err := r.store.GetFileByName(ctx, namespace, name)
	if errors.Is(err, datastore.ErrNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, gqlerror.Errorf("retrieve File: %v", err)
	}
	return DatastoreFileToGraphQL(file), nil
}

// WatchFiles is the resolver for the watchFiles field.
func (r *subscriptionResolver) WatchFiles(ctx context.Context, namespace *string, selector *model.LabelSelectorInput, resourceVersion *string) (<-chan *model.FileWatchEvent, error) {
	return watchCatalogJournal(ctx, r.Resolver, "File", namespace, selector, resourceVersion, "typed", fileJournalEventToGraphQL)
}
