package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"time"

	"github.com/gitstore-dev/gitstore/api/internal/datastore"
	"github.com/gitstore-dev/gitstore/api/internal/graph/model"
	"github.com/gitstore-dev/gitstore/api/internal/middleware/security"
	"github.com/gitstore-dev/gitstore/api/internal/watchjournal"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateNamespace is the resolver for the createNamespace field.
func (r *mutationResolver) CreateNamespace(ctx context.Context, input model.CreateNamespaceInput) (*model.CreateNamespacePayload, error) {
	ns, err := r.service.CreateNamespace(ctx, input, callerUsernameOrAnon(ctx, r))
	if err != nil {
		return nil, err
	}
	return &model.CreateNamespacePayload{
		Namespace: DatastoreNamespaceToGraphQL(ns),
	}, nil
}

// UpdateNamespace is the resolver for the updateNamespace field.
func (r *mutationResolver) UpdateNamespace(ctx context.Context, input model.UpdateNamespaceInput) (*model.UpdateNamespacePayload, error) {
	ns, err := r.service.UpdateNamespace(ctx, input, callerUsernameOrAnon(ctx, r))
	if err != nil {
		return nil, err
	}
	return &model.UpdateNamespacePayload{Namespace: DatastoreNamespaceToGraphQL(ns)}, nil
}

// DeleteNamespace is the resolver for the deleteNamespace field.
func (r *mutationResolver) DeleteNamespace(ctx context.Context, input model.DeleteNamespaceInput) (*model.DeleteNamespacePayload, error) {
	ns, ok := security.AuthorizedNamespaceForDeletion(ctx)
	if !ok || ns.Name != input.Identifier {
		return nil, gqlerror.Errorf("namespace deletion authorization context is missing")
	}
	outcome, err := r.service.DeleteNamespace(ctx, ns)
	if err != nil {
		return nil, err
	}
	return &model.DeleteNamespacePayload{
		DeletedIdentifier: input.Identifier,
		Outcome:           model.NamespaceDeletionOutcome(outcome),
	}, nil
}

// CompleteNamespaceDeletion is the resolver for the completeNamespaceDeletion field.
func (r *mutationResolver) CompleteNamespaceDeletion(ctx context.Context, input model.CompleteNamespaceDeletionInput) (*model.CompleteNamespaceDeletionPayload, error) {
	deleted, err := r.service.CompleteNamespaceDeletion(ctx, input.Identifier, input.ResourceVersion)
	if errors.Is(err, datastore.ErrConflict) {
		return &model.CompleteNamespaceDeletionPayload{
			Conflict: &model.StatusConflict{CurrentResourceVersion: deleted.ResourceVersion},
		}, nil
	}
	if err != nil {
		return nil, err
	}
	return &model.CompleteNamespaceDeletionPayload{DeletedIdentifier: &input.Identifier}, nil
}

// Namespace is the resolver for the namespace field.
func (r *queryResolver) Namespace(ctx context.Context, by model.NamespaceBy) (*model.Namespace, error) {
	if by.ID != nil {
		namespaceID, err := decodeNodeIDAs(nodeKindNamespace, *by.ID)
		if err != nil {
			return nil, err
		}
		ns, err := r.service.GetNamespaceByID(ctx, namespaceID)
		if err != nil {
			return nil, err
		}
		return DatastoreNamespaceToGraphQL(ns), nil
	}

	name := by.Name
	if name == nil {
		name = by.Identifier
	}
	ns, err := r.service.GetNamespaceByName(ctx, *name)
	if err != nil {
		return nil, err
	}
	return DatastoreNamespaceToGraphQL(ns), nil
}

// Namespaces is the resolver for the namespaces field.
func (r *queryResolver) Namespaces(ctx context.Context, first *int32, after *string, last *int32, before *string) (*model.NamespaceConnection, error) {
	params := toPageParams(first, after, last, before)
	result, err := r.service.ListNamespaces(ctx, params)
	if err != nil {
		return nil, err
	}
	return BuildNamespaceConnection(result), nil
}

// WatchNamespaces is the resolver for the watchNamespaces field.
func (r *subscriptionResolver) WatchNamespaces(ctx context.Context, selector *model.LabelSelectorInput, resourceVersion *string) (<-chan *model.NamespaceWatchEvent, error) {
	if r.namespaceSubscriber == nil || !r.namespaceWatch.ReadersEnabled {
		return nil, namespaceWatchGraphQLError(&watchjournal.TerminalError{Code: watchjournal.CodeUnavailable, Reason: "MATERIALIZER_NOT_READY"})
	}
	rawCursor := ""
	if resourceVersion != nil {
		rawCursor = *resourceVersion
	}
	streamCtx, cancel := context.WithCancel(ctx)
	stream, err := r.namespaceSubscriber.SubscribePath(streamCtx, rawCursor, "typed")
	if err != nil {
		cancel()
		return nil, namespaceWatchGraphQLError(err)
	}
	out := make(chan *model.NamespaceWatchEvent, r.namespaceWatch.SubscriberBuffer)
	go func() {
		defer cancel()
		defer close(out)
		events := stream.Events
		errorsOut := stream.Errors
		for events != nil || errorsOut != nil {
			select {
			case <-ctx.Done():
				return
			case streamErr, ok := <-errorsOut:
				if !ok {
					errorsOut = nil
					continue
				}
				if streamErr != nil {
					addNamespaceWatchSubscriptionError(ctx, namespaceWatchGraphQLError(streamErr))
					return
				}
			case event, ok := <-events:
				if !ok {
					events = nil
					continue
				}
				projected, matches := projectNamespaceJournalEventForSelector(event, selector)
				if !matches {
					continue
				}
				namespace, decodeErr := namespaceFromJournalEvent(projected)
				if decodeErr != nil {
					addNamespaceWatchSubscriptionError(ctx, decodeErr)
					return
				}
				converted, convertErr := NamespaceJournalEventToGraphQL(projected, namespace)
				if convertErr != nil {
					addNamespaceWatchSubscriptionError(ctx, convertErr)
					return
				}
				if sendErr := sendNamespaceWatchOutput(streamCtx, out, converted, time.Duration(r.namespaceWatch.SubscriberBackpressureMillis)*time.Millisecond); sendErr != nil {
					if streamCtx.Err() == nil {
						addNamespaceWatchSubscriptionError(streamCtx, namespaceWatchGraphQLError(sendErr))
					}
					return
				}
			}
		}
	}()
	return out, nil
}
