package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/gitstore-dev/gitstore/api/internal/catalog"
	"github.com/gitstore-dev/gitstore/api/internal/datastore"
	"github.com/gitstore-dev/gitstore/api/internal/eventbus"
	"github.com/gitstore-dev/gitstore/api/internal/graph/generated"
	"github.com/gitstore-dev/gitstore/api/internal/graph/model"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.CreateProductPayload, error) {
	product, err := r.service.CommitProductManifest(ctx, input.APIVersion, input.Kind, input.Metadata, input.Spec, input.Body, callerUsernameOrAnon(ctx, r), true)
	if err != nil {
		return nil, err
	}
	return &model.CreateProductPayload{Product: DatastoreProductToGraphQL(product)}, nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, input model.UpdateProductInput) (*model.UpdateProductPayload, error) {
	product, err := r.service.CommitProductManifest(ctx, input.APIVersion, input.Kind, input.Metadata, input.Spec, input.Body, callerUsernameOrAnon(ctx, r), false)
	if err != nil {
		return nil, err
	}
	return &model.UpdateProductPayload{Product: DatastoreProductToGraphQL(product)}, nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, input model.DeleteProductInput) (*model.DeleteProductPayload, error) {
	if input.ID == nil {
		return nil, gqlerror.Errorf("product ID is required")
	}
	uid, err := decodeNodeIDAs(nodeKindProduct, *input.ID)
	if err != nil {
		return nil, gqlerror.Errorf("invalid product ID")
	}
	product, started, err := r.service.DeleteProductManifest(ctx, uid, callerUsernameOrAnon(ctx, r))
	if err != nil {
		return nil, err
	}
	outcome := model.ProductDeletionOutcomeAlreadyTerminating
	if started {
		outcome = model.ProductDeletionOutcomeTerminationStarted
	}
	return &model.DeleteProductPayload{Product: DatastoreProductToGraphQL(product), Outcome: outcome}, nil
}

// UpdateProductStatus applies controller-managed category-resolution state.
// It may remove exactly one resolved category owner reference, but never
// touches the Git-authored spec.categoryRef.
func (r *mutationResolver) UpdateProductStatus(ctx context.Context, input model.UpdateProductStatusInput) (*model.UpdateProductStatusPayload, error) {
	product, err := r.store.GetProductByName(ctx, input.Namespace, input.Name)
	if err != nil {
		if errors.Is(err, datastore.ErrNotFound) {
			return nil, &gqlerror.Error{
				Message:    fmt.Sprintf("Product %s/%s not found", input.Namespace, input.Name),
				Extensions: map[string]any{"code": "NOT_FOUND"},
			}
		}
		return nil, gqlerror.Errorf("retrieve product status: %v", err)
	}
	if product.ResourceVersion != input.ResourceVersion {
		return nil, statusConflictError("Product", input.Namespace, input.Name, product.ResourceVersion)
	}
	if input.RemoveOwnerID != nil {
		var refs []catalog.OwnerReference
		if len(product.OwnerReferences) > 0 {
			if err := json.Unmarshal(product.OwnerReferences, &refs); err != nil {
				return nil, gqlerror.Errorf("decode product owner references: %v", err)
			}
		}
		filtered := refs[:0]
		for _, ref := range refs {
			if productOwnerReferenceNodeID(ref) != *input.RemoveOwnerID {
				filtered = append(filtered, ref)
			}
		}
		ownerReferences, err := json.Marshal(filtered)
		if err != nil {
			return nil, gqlerror.Errorf("encode product owner references: %v", err)
		}
		product.OwnerReferences = ownerReferences
	}
	var status catalog.ProductStatus
	if len(product.Status) > 0 {
		if err := json.Unmarshal(product.Status, &status); err != nil {
			return nil, gqlerror.Errorf("decode product status: %v", err)
		}
	}
	if input.Conditions != nil {
		status.Conditions = mergeProductConditions(status.Conditions, toConditions(input.Conditions))
	}
	statusJSON, err := json.Marshal(status)
	if err != nil {
		return nil, gqlerror.Errorf("encode product status: %v", err)
	}
	product.Status = statusJSON
	datastore.AdvanceProductSystemVersion(product)
	if err := r.store.UpdateProduct(ctx, product); err != nil {
		if errors.Is(err, datastore.ErrConflict) {
			current, getErr := r.store.GetProductByName(ctx, input.Namespace, input.Name)
			if getErr == nil {
				return nil, statusConflictError("Product", input.Namespace, input.Name, current.ResourceVersion)
			}
		}
		return nil, gqlerror.Errorf("update product status: %v", err)
	}
	if r.eventBus != nil {
		r.eventBus.Publish(eventbus.Event{
			Type:            eventbus.Modified,
			Kind:            "Product",
			Namespace:       product.Namespace,
			Name:            product.Name,
			ResourceVersion: product.ResourceVersion,
			Object:          product,
		})
	}
	return &model.UpdateProductStatusPayload{Product: DatastoreProductToGraphQL(product)}, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, by model.ProductBy) (*model.Product, error) {
	switch {
	case by.ID != nil:
		rawID, err := decodeNodeIDAs(nodeKindProduct, *by.ID)
		if err != nil {
			return nil, nil
		}
		p, err := r.service.GetProductByUID(ctx, rawID)
		if err != nil {
			return nil, nil
		}
		return DatastoreProductToGraphQL(p), nil
	case by.NamespacePath != nil:
		p, err := r.service.GetProductByName(ctx, by.NamespacePath.Namespace, by.NamespacePath.Name)
		if err != nil {
			return nil, nil
		}
		return DatastoreProductToGraphQL(p), nil
	default:
		return nil, gqlerror.Errorf("ProductBy: exactly one selector required")
	}
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, namespace string, first *int32, after *string, last *int32, before *string) (*model.ProductConnection, error) {
	params := toPageParams(first, after, last, before)
	result, err := r.service.GetProducts(ctx, namespace, params)
	if err != nil {
		return nil, fmt.Errorf("failed to get products: %w", err)
	}
	return BuildProductConnection(result), nil
}

// WatchProducts is the resolver for the watchProducts field.
func (r *subscriptionResolver) WatchProducts(ctx context.Context, namespace *string, selector *model.LabelSelectorInput, resourceVersion *string) (<-chan *model.ProductWatchEvent, error) {
	return r.watchProductResources(ctx, namespace, selector, resourceVersion)
}

// Product returns generated.ProductResolver implementation.
func (r *Resolver) Product() generated.ProductResolver { return &productResolver{r} }

type productResolver struct{ *Resolver }
