package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"

	"github.com/gitstore-dev/gitstore/api/internal/eventbus"
	"github.com/gitstore-dev/gitstore/api/internal/graph/generated"
	"github.com/gitstore-dev/gitstore/api/internal/graph/model"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.uber.org/zap"
)

const productWatchBootstrapCursor = "__product_watch_bootstrap__"

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, by model.ProductBy) (*model.Product, error) {
	switch {
	case by.ID != nil:
		rawID, err := decodeNodeIDAs(nodeKindProduct, *by.ID)
		if err != nil {
			return nil, nil
		}
		p, err := r.service.GetProductByUID(ctx, rawID)
		if err != nil {
			return nil, nil
		}
		return DatastoreProductToGraphQL(p), nil
	case by.NamespacePath != nil:
		p, err := r.service.GetProductByName(ctx, by.NamespacePath.Namespace, by.NamespacePath.Name)
		if err != nil {
			return nil, nil
		}
		return DatastoreProductToGraphQL(p), nil
	default:
		return nil, gqlerror.Errorf("ProductBy: exactly one selector required")
	}
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, namespace string, first *int32, after *string, last *int32, before *string) (*model.ProductConnection, error) {
	params := toPageParams(first, after, last, before)
	result, err := r.service.GetProducts(ctx, namespace, params)
	if err != nil {
		return nil, fmt.Errorf("failed to get products: %w", err)
	}
	return BuildProductConnection(result), nil
}

// WatchProducts is the resolver for the watchProducts field.
func (r *subscriptionResolver) WatchProducts(ctx context.Context, namespace *string, selector *model.LabelSelectorInput, resourceVersion *string) (<-chan *model.ProductWatchEvent, error) {
	if r.eventBus == nil {
		return nil, gqlerror.Errorf("watch subscriptions are not available")
	}
	rv := ""
	if resourceVersion != nil {
		rv = *resourceVersion
	}
	// The controller uses this private token to request a bookmark before its
	// initial Product snapshot. Numeric cursors, including "0", remain real
	// lower bounds for event-bus replay.
	bootstrap := rv == productWatchBootstrapCursor
	if bootstrap {
		rv = ""
	}
	events, unsubscribe, startCursor, err := r.eventBus.SubscribeWithCursor("Product", rv)
	if err != nil {
		if errors.Is(err, eventbus.ErrWatchExpired) {
			r.logger.Warn("watch cursor expired; controller must re-list",
				zap.String("kind", "Product"),
				zap.String("resource_version", rv))
			return nil, &gqlerror.Error{
				Message:    "watch cursor expired; re-list and resume from a fresh cursor",
				Extensions: map[string]any{"code": "WATCH_EXPIRED"},
			}
		}
		return nil, gqlerror.Errorf("watch subscription failed: %v", err)
	}
	r.logger.Debug("watch subscription opened",
		zap.String("kind", "Product"),
		zap.Bool("resumed", rv != ""))

	out := make(chan *model.ProductWatchEvent, 16)
	go func() {
		defer close(out)
		defer unsubscribe()
		if bootstrap {
			bookmark := toProductWatchEvent(eventbus.Event{Kind: "Product", Cursor: startCursor})
			select {
			case out <- bookmark:
			case <-ctx.Done():
				return
			}
		}
		for {
			select {
			case <-ctx.Done():
				return
			case ev, ok := <-events:
				if !ok {
					return
				}
				if !productEventMatchesFilters(ev, namespace) || !productEventMatchesSelector(ev, selector) {
					continue
				}
				select {
				case out <- toProductWatchEvent(ev):
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}

// Product returns generated.ProductResolver implementation.
func (r *Resolver) Product() generated.ProductResolver { return &productResolver{r} }

type productResolver struct{ *Resolver }
