package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"

	"github.com/gitstore-dev/gitstore/api/internal/datastore"
	"github.com/gitstore-dev/gitstore/api/internal/graph/model"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.uber.org/zap"
)

// CreateRepository is the resolver for the createRepository field.
func (r *mutationResolver) CreateRepository(ctx context.Context, input model.CreateRepositoryInput) (*model.CreateRepositoryPayload, error) {
	ns, err := r.service.GetNamespaceByName(ctx, input.Namespace)
	if err != nil {
		return nil, err
	}
	if err := r.authorizeRepositoryTenant(ctx, "create", input.Name, ns); err != nil {
		return nil, err
	}
	defaultBranch := "main"
	if input.DefaultBranch != nil && *input.DefaultBranch != "" {
		defaultBranch = *input.DefaultBranch
	}
	repo, err := r.service.CreateRepository(ctx, ns.Name, input.Name, defaultBranch, "default", callerUsernameOrAnon(ctx, r))
	if err != nil {
		return nil, err
	}
	r.logger.Info("lookup repository",
		zap.String("namespace", input.Namespace),
		zap.String("name", input.Name),
		zap.String("repo_id", repo.ID),
	)
	result, err := datastoreRepositoryToModelStrict(repo, ns, r.storageDataDir)
	if err != nil {
		return nil, gqlerror.Errorf("failed to hydrate repository: %v", err)
	}
	return &model.CreateRepositoryPayload{
		Repository: result,
	}, nil
}

// RenameRepository is the resolver for the renameRepository field.
func (r *mutationResolver) RenameRepository(ctx context.Context, input model.RenameRepositoryInput) (*model.RenameRepositoryPayload, error) {
	repoID, err := decodeNodeIDAs(nodeKindRepository, input.RepositoryID)
	if err != nil {
		return nil, err
	}
	repo, err := r.service.GetRepository(ctx, repoID)
	if err != nil {
		return nil, err
	}
	ns, err := r.service.GetNamespaceByName(ctx, repo.Namespace)
	if err != nil {
		return nil, err
	}
	if err := r.authorizeRepositoryTenant(ctx, "rename", repo.Name, ns); err != nil {
		return nil, err
	}
	repo, err = r.service.RenameRepository(ctx, repoID, input.NewName, callerUsernameOrAnon(ctx, r))
	if err != nil {
		return nil, err
	}
	r.logger.Info("rename repository",
		zap.String("repo_id", repoID),
		zap.String("new_name", input.NewName),
	)
	result, err := datastoreRepositoryToModelStrict(repo, ns, r.storageDataDir)
	if err != nil {
		return nil, gqlerror.Errorf("failed to hydrate repository: %v", err)
	}
	return &model.RenameRepositoryPayload{
		Repository: result,
	}, nil
}

// TransferRepository is the resolver for the transferRepository field.
func (r *mutationResolver) TransferRepository(ctx context.Context, input model.TransferRepositoryInput) (*model.TransferRepositoryPayload, error) {
	repoID, err := decodeNodeIDAs(nodeKindRepository, input.RepositoryID)
	if err != nil {
		return nil, err
	}
	targetNsID, err := decodeNodeIDAs(nodeKindNamespace, input.TargetNamespaceID)
	if err != nil {
		return nil, err
	}
	ns, err := r.service.GetNamespaceByID(ctx, targetNsID)
	if err != nil {
		return nil, err
	}
	repo, err := r.service.GetRepository(ctx, repoID)
	if err != nil {
		return nil, err
	}
	sourceNS, err := r.service.GetNamespaceByName(ctx, repo.Namespace)
	if err != nil {
		return nil, err
	}
	if err := r.authorizeRepositoryTenant(ctx, "transfer", repo.Name, sourceNS, ns); err != nil {
		return nil, err
	}
	repo, err = r.service.TransferRepository(ctx, repoID, ns.Name, callerUsernameOrAnon(ctx, r))
	if err != nil {
		return nil, err
	}
	r.logger.Info("transfer repository",
		zap.String("repo_id", repoID),
		zap.String("to_namespace_id", targetNsID),
	)
	result, err := datastoreRepositoryToModelStrict(repo, ns, r.storageDataDir)
	if err != nil {
		return nil, gqlerror.Errorf("failed to hydrate repository: %v", err)
	}
	return &model.TransferRepositoryPayload{
		Repository: result,
	}, nil
}

// DeleteRepository is the resolver for the deleteRepository field.
func (r *mutationResolver) DeleteRepository(ctx context.Context, input model.DeleteRepositoryInput) (*model.DeleteRepositoryPayload, error) {
	repoID, err := decodeNodeIDAs(nodeKindRepository, input.RepositoryID)
	if err != nil {
		return nil, err
	}
	repo, err := r.service.GetRepository(ctx, repoID)
	if err != nil {
		return nil, err
	}
	ns, err := r.service.GetNamespaceByName(ctx, repo.Namespace)
	if err != nil {
		return nil, err
	}
	if err := r.authorizeRepositoryTenant(ctx, "delete", repo.Name, ns); err != nil {
		return nil, err
	}
	if err := r.service.DeleteRepository(ctx, repoID, callerUsernameOrAnon(ctx, r)); err != nil {
		return nil, err
	}
	r.logger.Info("delete repository", zap.String("repo_id", repoID))
	return &model.DeleteRepositoryPayload{
		DeletedRepositoryID: mustEncodeNodeID(nodeKindRepository, repoID),
	}, nil
}

// Repository is the resolver for the repository field.
func (r *queryResolver) Repository(ctx context.Context, by model.RepositoryBy) (*model.Repository, error) {
	if by.ID != nil {
		repoID, err := decodeNodeIDAs(nodeKindRepository, *by.ID)
		if err != nil {
			return nil, err
		}
		repo, err := r.service.GetRepository(ctx, repoID)
		if err != nil {
			return nil, err
		}
		ns, err := r.service.GetNamespaceByName(ctx, repo.Namespace)
		if err != nil {
			return nil, err
		}
		if err := r.authorizeRepositoryTenant(ctx, "read", repo.Name, ns); err != nil {
			return nil, err
		}
		r.logger.Info("lookup repository", zap.String("repo_id", repoID))
		result, err := datastoreRepositoryToModelStrict(repo, ns, r.storageDataDir)
		if err != nil {
			return nil, gqlerror.Errorf("failed to hydrate repository: %v", err)
		}
		return result, nil
	}
	if by.NamespacePath != nil {
		ns, err := r.service.GetNamespaceByName(ctx, by.NamespacePath.Namespace)
		if err != nil {
			return nil, err
		}
		mapping, err := r.service.LookupRepository(ctx, ns.Name, by.NamespacePath.Name)
		if err != nil {
			if errors.Is(err, datastore.ErrNotFound) {
				return nil, &gqlerror.Error{
					Message:    "repository not found",
					Extensions: map[string]any{"code": "NOT_FOUND"},
				}
			}
			return nil, err
		}
		repo, err := r.service.GetRepository(ctx, mapping.RepositoryID)
		if err != nil {
			return nil, err
		}
		if err := r.authorizeRepositoryTenant(ctx, "read", repo.Name, ns); err != nil {
			return nil, err
		}
		r.logger.Info("lookup repository",
			zap.String("namespace", ns.Name),
			zap.String("name", by.NamespacePath.Name),
			zap.String("repo_id", mapping.RepositoryID),
		)
		result, err := datastoreRepositoryToModelStrict(repo, ns, r.storageDataDir)
		if err != nil {
			return nil, gqlerror.Errorf("failed to hydrate repository: %v", err)
		}
		return result, nil
	}
	return nil, gqlerror.Errorf("repository: exactly one of id or namespacePath must be provided")
}

// Repositories is the resolver for the repositories field.
func (r *queryResolver) Repositories(ctx context.Context, namespace string, first *int32, after *string, last *int32, before *string) (*model.RepositoryConnection, error) {
	ns, err := r.service.GetNamespaceByName(ctx, namespace)
	if err != nil {
		return nil, err
	}
	if err := r.authorizeRepositoryTenant(ctx, "read", namespace, ns); err != nil {
		return nil, err
	}
	params := toPageParams(first, after, last, before)
	result, err := r.service.ListRepositoriesByNamespace(ctx, ns.Name, params)
	if err != nil {
		return nil, err
	}
	return BuildRepositoryConnection(result, ns, r.storageDataDir)
}
