package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/gitstore-dev/gitstore/api/internal/graph/generated"
	"github.com/gitstore-dev/gitstore/api/internal/graph/model"
)

// PublishCatalog is the resolver for the publishCatalog field.
// TODO(remove)
func (r *mutationResolver) PublishCatalog(ctx context.Context, input model.PublishCatalogInput) (*model.PublishCatalogPayload, error) {
	message := input.Message
	if message == "" {
		message = "Published catalog"
	}

	stats := r.getCatalogStats(ctx)

	version := &model.CatalogVersion{
		Tag:         input.Version,
		Commit:      "abc123def456", // TODO: resolve actual commit from git push result
		PublishedAt: r.clock.Now(),
		Message:     &message,
		Stats:       stats,
	}
	return &model.PublishCatalogPayload{
		CatalogVersion: version,
	}, nil
}

// UpdateResourceStatus is the resolver for the updateResourceStatus field.
func (r *mutationResolver) UpdateResourceStatus(ctx context.Context, input model.UpdateResourceStatusInput) (*model.UpdateResourceStatusPayload, error) {
	panic(fmt.Errorf("not implemented: UpdateResourceStatus - updateResourceStatus"))
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (model.Node, error) {
	kind, rawID, err := DecodeNodeID(id)
	if err != nil {
		return nil, invalidGlobalIDError(err)
	}
	return r.resolveNode(ctx, kind, rawID)
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []string) ([]model.Node, error) {
	nodes := make([]model.Node, len(ids))
	for i, id := range ids {
		kind, rawID, err := DecodeNodeID(id)
		if err != nil {
			continue
		}
		node, err := r.resolveNode(ctx, kind, rawID)
		if err != nil {
			continue
		}
		nodes[i] = node
	}
	return nodes, nil
}

// CatalogVersion is the resolver for the catalogVersion field.
// TODO(remove)
func (r *queryResolver) CatalogVersion(ctx context.Context) (*model.CatalogVersion, error) {
	stats := r.getCatalogStats(ctx)
	return &model.CatalogVersion{
		Tag:         "",
		Commit:      "",
		PublishedAt: r.clock.Now(),
		Message:     nil,
		Stats:       stats,
	}, nil
}

// WatchResources is the resolver for the watchResources field.
func (r *subscriptionResolver) WatchResources(ctx context.Context, kind string, namespace *string, selector *model.LabelSelectorInput, resourceVersion *string) (<-chan *model.WatchEvent, error) {
	panic(fmt.Errorf("not implemented: WatchResources - watchResources"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
