// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 GitStore contributors

// Proto stubs are generated by buf (buf.gen.rust.yaml → gitstore-git-service/gen/).
// No build-time compilation needed.
fn main() {}
