/**
 * THIS FILE IS AUTO-GENERATED BY GRAPHQL CODE GENERATOR
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * To regenerate this file, run:
 *   npm run codegen
 *
 * This file contains:
 * - TypeScript types for all GraphQL schema types
 * - React hooks for all GraphQL queries and mutations
 * - Type-safe GraphQL operations
 */

// This is a placeholder file. Run `npm run codegen` to generate the actual types.
// The codegen tool will read from:
// - Schema: ../shared/schemas/*.graphql
// - Operations: src/graphql/**/*.graphql
//
// Generated hooks will be named based on operation names:
// - Queries: useGetProductsQuery, useGetCategoriesQuery, etc.
// - Mutations: useCreateProductMutation, useUpdateProductMutation, etc.

export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };

// Placeholder types - will be replaced by codegen
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  DateTime: { input: string; output: string; }
  Decimal: { input: string; output: string; }
  JSON: { input: any; output: any; }
};

// Placeholder - run codegen to generate actual types
export type Product = {
  __typename?: 'Product';
  id: Scalars['ID']['output'];
  title: Scalars['String']['output'];
  sku: Scalars['String']['output'];
  price: Scalars['Decimal']['output'];
  compareAtPrice?: Maybe<Scalars['Decimal']['output']>;
  inventoryStatus: InventoryStatus;
  inventoryQuantity: Scalars['Int']['output'];
  description?: Maybe<Scalars['String']['output']>;
  categoryId?: Maybe<Scalars['ID']['output']>;
  collectionIds: Array<Scalars['ID']['output']>;
  images: Array<Scalars['String']['output']>;
  metadata?: Maybe<Scalars['JSON']['output']>;
  createdAt: Scalars['DateTime']['output'];
  updatedAt: Scalars['DateTime']['output'];
  version: Scalars['String']['output'];
};

export enum InventoryStatus {
  InStock = 'IN_STOCK',
  OutOfStock = 'OUT_OF_STOCK',
  Preorder = 'PREORDER',
  Discontinued = 'DISCONTINUED'
}

// Add more placeholder types as needed
// Run `npm run codegen` to generate complete types

console.warn(
  'Using placeholder GraphQL types. Run `npm run codegen` to generate actual types from schema.'
);
