// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 GitStore contributors

use async_trait::async_trait;
use regex::Regex;
use tracing::error;

use super::{AdmissionDecision, AdmissionHandler, RefUpdate};

// Re-export catalog proto types.
// Generated by buf (buf.gen.rust.yaml) into gen/gitstore/catalog/v1/.
pub mod catalog_proto {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/gen/gitstore/catalog/v1/gitstore.catalog.v1.rs"
    ));
}

use catalog_proto::catalog_service_client::CatalogServiceClient;
use catalog_proto::AdmitResourcesRequest;

/// Implements `AdmissionHandler` for the post-receive slot.
/// Checks the ref against `branch_pattern` (a full-match regex); if matching,
/// fire-and-forgets `AdmitResources`. Always returns `Accept`.
pub struct AdmissionControlHandler {
    client: CatalogServiceClient<tonic::transport::Channel>,
    branch_pattern: Regex,
}

impl AdmissionControlHandler {
    pub fn new(
        client: CatalogServiceClient<tonic::transport::Channel>,
        branch_pattern: Regex,
    ) -> Self {
        Self {
            client,
            branch_pattern,
        }
    }

    pub async fn connect(url: &str, branch_pattern: String) -> anyhow::Result<Self> {
        let re = Regex::new(&branch_pattern)
            .map_err(|e| anyhow::anyhow!("invalid branch_pattern {:?}: {}", branch_pattern, e))?;
        let endpoint = tonic::transport::Endpoint::from_shared(url.to_string())?;
        let channel = endpoint.connect_lazy();
        let client = CatalogServiceClient::new(channel);
        Ok(Self::new(client, re))
    }
}

#[async_trait]
impl AdmissionHandler for AdmissionControlHandler {
    async fn admit(
        &self,
        _phase: &str,
        updates: &[RefUpdate],
        repository_id: &str,
    ) -> anyhow::Result<AdmissionDecision> {
        for update in updates {
            if !self.branch_pattern.is_match(&update.ref_name) {
                // Ref does not match branch pattern — skip, no gRPC call.
                continue;
            }

            let old_commit_sha = update.old_oid.clone();
            let new_commit_sha = update.new_oid.clone();
            let ref_name = update.ref_name.clone();
            let mut client = self.client.clone();
            let repository_id = repository_id.to_string();

            tokio::spawn(async move {
                let req = AdmitResourcesRequest {
                    repository_id,
                    commit_sha: new_commit_sha.clone(),
                    ref_name: ref_name.clone(),
                    old_commit_sha,
                    new_commit_sha,
                    changed_paths: vec![],
                };
                if let Err(e) = client.admit_resources(req).await {
                    error!(
                        ref_name = %ref_name,
                        error = %e,
                        "admit_resources_error"
                    );
                }
            });
        }

        Ok(AdmissionDecision::Accept)
    }
}

// ---------------------------------------------------------------------------
// Unit tests (T019)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use catalog_proto::{
        catalog_service_server::{CatalogService, CatalogServiceServer},
        AdmitResourcesResponse, ValidateResourcesRequest, ValidateResourcesResponse,
    };
    use std::sync::{
        atomic::{AtomicU32, Ordering},
        Arc,
    };
    use tokio::time::Duration;
    use tonic::{transport::Server, Request, Response, Status};

    struct MockCatalogService {
        admit_call_count: Arc<AtomicU32>,
    }

    #[tonic::async_trait]
    impl CatalogService for MockCatalogService {
        async fn validate_resources(
            &self,
            _req: Request<ValidateResourcesRequest>,
        ) -> Result<Response<ValidateResourcesResponse>, Status> {
            Ok(Response::new(ValidateResourcesResponse {
                accepted: true,
                errors: vec![],
            }))
        }

        async fn admit_resources(
            &self,
            _req: Request<AdmitResourcesRequest>,
        ) -> Result<Response<AdmitResourcesResponse>, Status> {
            self.admit_call_count.fetch_add(1, Ordering::SeqCst);
            Ok(Response::new(AdmitResourcesResponse {}))
        }
    }

    async fn start_mock_server(admit_count: Arc<AtomicU32>) -> String {
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let addr = listener.local_addr().unwrap();
        let svc = MockCatalogService {
            admit_call_count: admit_count,
        };
        tokio::spawn(async move {
            Server::builder()
                .add_service(CatalogServiceServer::new(svc))
                .serve_with_incoming(tokio_stream::wrappers::TcpListenerStream::new(listener))
                .await
                .unwrap();
        });
        tokio::time::sleep(Duration::from_millis(10)).await;
        format!("http://{}", addr)
    }

    fn make_update(ref_name: &str, old_oid_zeros: bool) -> RefUpdate {
        RefUpdate {
            ref_name: ref_name.to_string(),
            old_oid: if old_oid_zeros {
                "0".repeat(40)
            } else {
                "a".repeat(40)
            },
            new_oid: "b".repeat(40),
        }
    }

    // T019a: ref matching branch_pattern triggers AdmitResources call
    #[tokio::test]
    async fn test_matching_ref_triggers_admit() {
        let count = Arc::new(AtomicU32::new(0));
        let addr = start_mock_server(count.clone()).await;

        let handler = AdmissionControlHandler::connect(&addr, "refs/heads/main".to_string())
            .await
            .unwrap();

        let updates = vec![make_update("refs/heads/main", false)];
        let result = handler
            .admit("post-receive", &updates, "repo-1")
            .await
            .unwrap();
        assert!(matches!(result, AdmissionDecision::Accept));

        // Give the spawned task time to complete
        tokio::time::sleep(Duration::from_millis(100)).await;
        assert_eq!(
            count.load(Ordering::SeqCst),
            1,
            "expected one AdmitResources call"
        );
    }

    // T019b: ref NOT matching branch_pattern → Accept immediately, no gRPC call
    #[tokio::test]
    async fn test_non_matching_ref_no_grpc_call() {
        let count = Arc::new(AtomicU32::new(0));
        let addr = start_mock_server(count.clone()).await;

        let handler = AdmissionControlHandler::connect(&addr, "refs/heads/main".to_string())
            .await
            .unwrap();

        let updates = vec![make_update("refs/heads/feature/my-feature", false)];
        let result = handler
            .admit("post-receive", &updates, "repo-1")
            .await
            .unwrap();
        assert!(matches!(result, AdmissionDecision::Accept));

        tokio::time::sleep(Duration::from_millis(50)).await;
        assert_eq!(
            count.load(Ordering::SeqCst),
            0,
            "non-matching ref must not call AdmitResources"
        );
    }

    // T019c: gRPC transport error → error logged, Accept returned (fire-and-forget)
    #[tokio::test]
    async fn test_transport_error_returns_accept() {
        let handler =
            AdmissionControlHandler::connect("http://127.0.0.1:1", "refs/heads/main".to_string())
                .await
                .unwrap();

        let updates = vec![make_update("refs/heads/main", false)];
        let result = handler
            .admit("post-receive", &updates, "repo-1")
            .await
            .unwrap();
        // Must always return Accept — errors are fire-and-forget
        assert!(matches!(result, AdmissionDecision::Accept));
    }

    // T019d: old_oid all-zeros (new branch) matching pattern triggers admission
    #[tokio::test]
    async fn test_new_branch_creation_triggers_admit() {
        let count = Arc::new(AtomicU32::new(0));
        let addr = start_mock_server(count.clone()).await;

        let handler = AdmissionControlHandler::connect(&addr, "refs/heads/main".to_string())
            .await
            .unwrap();

        let updates = vec![make_update("refs/heads/main", true)]; // zero old_oid
        let result = handler
            .admit("post-receive", &updates, "repo-1")
            .await
            .unwrap();
        assert!(matches!(result, AdmissionDecision::Accept));

        tokio::time::sleep(Duration::from_millis(100)).await;
        assert_eq!(
            count.load(Ordering::SeqCst),
            1,
            "new branch creation must trigger admit"
        );
    }

    // T019e: anchored pattern must not match a ref that merely contains the pattern as a prefix
    // (e.g. "refs/heads/main-old" must not match "^refs/heads/main$")
    #[tokio::test]
    async fn test_prefix_extended_ref_no_grpc_call() {
        let count = Arc::new(AtomicU32::new(0));
        let addr = start_mock_server(count.clone()).await;

        let handler = AdmissionControlHandler::connect(&addr, "^refs/heads/main$".to_string())
            .await
            .unwrap();

        let updates = vec![make_update("refs/heads/main-old", false)];
        let result = handler
            .admit("post-receive", &updates, "repo-1")
            .await
            .unwrap();
        assert!(matches!(result, AdmissionDecision::Accept));

        tokio::time::sleep(Duration::from_millis(50)).await;
        assert_eq!(
            count.load(Ordering::SeqCst),
            0,
            "refs/heads/main-old must not match ^refs/heads/main$ branch pattern"
        );
    }

    // T019f: zero new_oid (branch deletion) on matching ref triggers exactly one AdmitResources call
    #[tokio::test]
    async fn test_branch_deletion_triggers_admit() {
        let count = Arc::new(AtomicU32::new(0));
        let addr = start_mock_server(count.clone()).await;

        let handler = AdmissionControlHandler::connect(&addr, "refs/heads/main".to_string())
            .await
            .unwrap();

        let update = RefUpdate {
            ref_name: "refs/heads/main".to_string(),
            old_oid: "a".repeat(40),
            new_oid: "0".repeat(40), // zero new-OID = branch deletion
        };
        let result = handler
            .admit("post-receive", &[update], "repo-1")
            .await
            .unwrap();
        assert!(matches!(result, AdmissionDecision::Accept));

        tokio::time::sleep(Duration::from_millis(100)).await;
        assert_eq!(
            count.load(Ordering::SeqCst),
            1,
            "branch deletion must trigger exactly one AdmitResources call"
        );
    }

    // T019g: zero new_oid (branch deletion) on a non-matching ref must NOT trigger admission
    #[tokio::test]
    async fn test_branch_deletion_non_matching_ref_no_call() {
        let count = Arc::new(AtomicU32::new(0));
        let addr = start_mock_server(count.clone()).await;

        let handler = AdmissionControlHandler::connect(&addr, "^refs/heads/main$".to_string())
            .await
            .unwrap();

        let update = RefUpdate {
            ref_name: "refs/heads/experiment/foo".to_string(),
            old_oid: "a".repeat(40),
            new_oid: "0".repeat(40), // zero new-OID = branch deletion
        };
        let result = handler
            .admit("post-receive", &[update], "repo-1")
            .await
            .unwrap();
        assert!(matches!(result, AdmissionDecision::Accept));

        tokio::time::sleep(Duration::from_millis(50)).await;
        assert_eq!(
            count.load(Ordering::SeqCst),
            0,
            "branch deletion on non-matching ref must not call AdmitResources"
        );
    }

    // T019h: wildcard pattern admits any feature branch (regex "refs/heads/.*")
    #[tokio::test]
    async fn test_wildcard_pattern_matches_feature_branch() {
        let count = Arc::new(AtomicU32::new(0));
        let addr = start_mock_server(count.clone()).await;

        let handler = AdmissionControlHandler::connect(&addr, "refs/heads/.*".to_string())
            .await
            .unwrap();

        let updates = vec![make_update("refs/heads/feature/my-feature", false)];
        let result = handler
            .admit("post-receive", &updates, "repo-1")
            .await
            .unwrap();
        assert!(matches!(result, AdmissionDecision::Accept));

        tokio::time::sleep(Duration::from_millis(100)).await;
        assert_eq!(
            count.load(Ordering::SeqCst),
            1,
            "refs/heads/.* must admit any refs/heads/ branch"
        );
    }

    // T019i: invalid regex in branch_pattern is rejected at construction time
    #[tokio::test]
    async fn test_invalid_pattern_rejected() {
        let result =
            AdmissionControlHandler::connect("http://127.0.0.1:1", "[invalid".to_string()).await;
        assert!(
            result.is_err(),
            "invalid regex must be rejected at connect()"
        );
    }
}
