// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 GitStore contributors

use std::time::Duration;

use async_trait::async_trait;
use tracing::{error, info};

use super::{AdmissionDecision, HookContext, ResourceBlob, ValidationHandler};

// Re-export catalog proto types for use in this module.
// Generated by buf (buf.gen.rust.yaml) into gen/gitstore/catalog/v1/.
pub mod catalog_proto {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/gen/gitstore/catalog/v1/gitstore.catalog.v1.rs"
    ));
}

use catalog_proto::catalog_service_client::CatalogServiceClient;
use catalog_proto::{ResourceBlob as ProtoBlob, ValidateResourcesRequest};

/// Calls `CatalogService.ValidateResources` gRPC with timeout.
/// On `accepted=false`: aggregates all `ValidationError.message` fields into rejection.
/// On timeout or transport error: returns `Reject("validation service unavailable")`.
pub struct SchemaValidationHandler {
    client: CatalogServiceClient<tonic::transport::Channel>,
    timeout: Duration,
    repository_id: String,
}

impl SchemaValidationHandler {
    pub fn new(
        client: CatalogServiceClient<tonic::transport::Channel>,
        timeout: Duration,
        repository_id: String,
    ) -> Self {
        Self {
            client,
            timeout,
            repository_id,
        }
    }

    pub async fn connect(
        url: &str,
        timeout: Duration,
        repository_id: String,
    ) -> anyhow::Result<Self> {
        let endpoint = tonic::transport::Endpoint::from_shared(url.to_string())?;
        let channel = endpoint.connect_lazy();
        let client = CatalogServiceClient::new(channel);
        Ok(Self::new(client, timeout, repository_id))
    }
}

#[async_trait]
impl ValidationHandler for SchemaValidationHandler {
    async fn validate(
        &self,
        blobs: &[ResourceBlob],
        _hook_ctx: &HookContext,
    ) -> anyhow::Result<AdmissionDecision> {
        let start = std::time::Instant::now();
        let file_count = blobs.len();

        let proto_blobs: Vec<ProtoBlob> = blobs
            .iter()
            .map(|b| ProtoBlob {
                path: b.path.clone(),
                blob_oid: b.blob_oid.clone(),
                content: b.content.clone(),
            })
            .collect();

        let req = ValidateResourcesRequest {
            repository_id: self.repository_id.clone(),
            blobs: proto_blobs,
        };

        let mut client = self.client.clone();
        let result = tokio::time::timeout(self.timeout, client.validate_resources(req)).await;

        let duration_ms = start.elapsed().as_millis() as u64;

        match result {
            Err(_elapsed) => {
                error!(
                    file_count,
                    duration_ms,
                    outcome = "timeout",
                    "validation_callout_complete"
                );
                self.record_metric("timeout");
                Ok(AdmissionDecision::Reject(
                    "validation service unavailable".to_string(),
                ))
            }
            Ok(Err(e)) => {
                error!(
                    file_count,
                    duration_ms,
                    outcome = "service_unavailable",
                    error = %e,
                    "validation_callout_complete"
                );
                self.record_metric("service_unavailable");
                Ok(AdmissionDecision::Reject(
                    "validation service unavailable".to_string(),
                ))
            }
            Ok(Ok(resp)) => {
                let resp = resp.into_inner();
                if resp.accepted {
                    info!(
                        file_count,
                        duration_ms,
                        outcome = "accepted",
                        "validation_callout_complete"
                    );
                    self.record_metric("accepted");
                    Ok(AdmissionDecision::Accept)
                } else {
                    let error_summary: Vec<String> = resp
                        .errors
                        .iter()
                        .map(|e| {
                            if e.file_path.is_empty() {
                                e.message.clone()
                            } else {
                                format!("{}: {}", e.file_path, e.message)
                            }
                        })
                        .collect();
                    let aggregated = error_summary.join("; ");
                    error!(
                        file_count,
                        duration_ms,
                        outcome = "rejected",
                        error_summary = %aggregated,
                        "validation_callout_complete"
                    );
                    self.record_metric("rejected");
                    Ok(AdmissionDecision::Reject(aggregated))
                }
            }
        }
    }
}

impl SchemaValidationHandler {
    fn record_metric(&self, result: &str) {
        use crate::git::metrics::increment_schema_validation_total;
        increment_schema_validation_total(result);
    }
}

// ---------------------------------------------------------------------------
// Unit tests (T010)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use catalog_proto::{
        catalog_service_server::{CatalogService, CatalogServiceServer},
        AdmitResourcesRequest, AdmitResourcesResponse, ValidateResourcesResponse, ValidationError,
    };
    use std::sync::Arc;
    use tonic::{transport::Server, Request, Response, Status};

    // ---- mock gRPC server ----

    type ValidateFn = Arc<
        dyn Fn(ValidateResourcesRequest) -> Result<ValidateResourcesResponse, Status> + Send + Sync,
    >;

    struct MockCatalogService {
        validate_fn: ValidateFn,
    }

    #[tonic::async_trait]
    impl CatalogService for MockCatalogService {
        async fn validate_resources(
            &self,
            req: Request<ValidateResourcesRequest>,
        ) -> Result<Response<ValidateResourcesResponse>, Status> {
            (self.validate_fn)(req.into_inner()).map(Response::new)
        }

        async fn admit_resources(
            &self,
            _req: Request<AdmitResourcesRequest>,
        ) -> Result<Response<AdmitResourcesResponse>, Status> {
            Ok(Response::new(AdmitResourcesResponse {}))
        }
    }

    async fn start_mock_server(
        validate_fn: impl Fn(ValidateResourcesRequest) -> Result<ValidateResourcesResponse, Status>
            + Send
            + Sync
            + 'static,
    ) -> String {
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let addr = listener.local_addr().unwrap();
        let svc = MockCatalogService {
            validate_fn: Arc::new(validate_fn),
        };
        tokio::spawn(async move {
            Server::builder()
                .add_service(CatalogServiceServer::new(svc))
                .serve_with_incoming(tokio_stream::wrappers::TcpListenerStream::new(listener))
                .await
                .unwrap();
        });
        // give the server a moment to bind
        tokio::time::sleep(std::time::Duration::from_millis(10)).await;
        format!("http://{}", addr)
    }

    fn make_blob(path: &str, content: &[u8]) -> ResourceBlob {
        ResourceBlob {
            path: path.to_string(),
            blob_oid: "a".repeat(40),
            content: content.to_vec(),
        }
    }

    // T010a: mock server returning accepted=true → Accept
    #[tokio::test]
    async fn test_accepted_response_returns_accept() {
        let addr = start_mock_server(|_req| {
            Ok(ValidateResourcesResponse {
                accepted: true,
                errors: vec![],
            })
        })
        .await;

        let handler =
            SchemaValidationHandler::connect(&addr, Duration::from_secs(5), "repo-1".into())
                .await
                .unwrap();

        let blobs = vec![make_blob("products/p.md", b"---\nkind: Product\n---")];
        let result = handler
            .validate(&blobs, &HookContext::default())
            .await
            .unwrap();
        assert!(matches!(result, AdmissionDecision::Accept));
    }

    // T010b: mock returning accepted=false with two ValidationErrors → Reject with aggregated message
    #[tokio::test]
    async fn test_rejected_response_aggregates_errors() {
        let addr = start_mock_server(|_req| {
            Ok(ValidateResourcesResponse {
                accepted: false,
                errors: vec![
                    ValidationError {
                        file_path: "products/p.md".into(),
                        field: "spec.title".into(),
                        constraint: "max=200".into(),
                        message: "spec.title exceeds maximum length of 200 characters".into(),
                    },
                    ValidationError {
                        file_path: "products/p.md".into(),
                        field: "status".into(),
                        constraint: "system-managed".into(),
                        message: "status is system-managed and must not be set by authors".into(),
                    },
                ],
            })
        })
        .await;

        let handler =
            SchemaValidationHandler::connect(&addr, Duration::from_secs(5), "repo-1".into())
                .await
                .unwrap();

        let blobs = vec![make_blob("products/p.md", b"---\nkind: Product\n---")];
        let result = handler
            .validate(&blobs, &HookContext::default())
            .await
            .unwrap();
        match result {
            AdmissionDecision::Reject(msg) => {
                assert!(
                    msg.contains("products/p.md"),
                    "expected file path in: {msg}"
                );
                assert!(msg.contains("spec.title"), "expected spec.title in: {msg}");
                assert!(
                    msg.contains("system-managed"),
                    "expected system-managed in: {msg}"
                );
            }
            _ => panic!("expected Reject"),
        }
    }

    // T010c: timeout fires before response → Reject("validation service unavailable")
    #[tokio::test]
    async fn test_timeout_returns_reject_unavailable() {
        let addr = start_mock_server(|_req| {
            // Simulate slow server by sleeping — but we can't easily do async here
            // so we use a delay in the response path via a blocking sleep
            std::thread::sleep(std::time::Duration::from_millis(200));
            Ok(ValidateResourcesResponse {
                accepted: true,
                errors: vec![],
            })
        })
        .await;

        let handler =
            SchemaValidationHandler::connect(&addr, Duration::from_millis(50), "repo-1".into())
                .await
                .unwrap();

        let blobs = vec![make_blob("products/p.md", b"---\nkind: Product\n---")];
        let result = handler
            .validate(&blobs, &HookContext::default())
            .await
            .unwrap();
        match result {
            AdmissionDecision::Reject(msg) => {
                assert_eq!(msg, "validation service unavailable");
            }
            _ => panic!("expected Reject for timeout"),
        }
    }

    // T025a: configured timeout fires before slow response → Reject within budget
    // Connects to a port that accepts the TCP connection but never sends a gRPC response,
    // so the timeout fires after exactly `timeout_ms` without blocking the thread pool.
    #[tokio::test]
    async fn test_configured_timeout_fires_within_budget() {
        // Bind a TCP listener that accepts but never responds (simulates a hung server).
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let addr = listener.local_addr().unwrap();
        tokio::spawn(async move {
            loop {
                // Accept connections but hold them open without responding.
                if let Ok((_stream, _)) = listener.accept().await {
                    tokio::time::sleep(Duration::from_secs(60)).await;
                }
            }
        });

        let timeout = Duration::from_millis(150);
        let handler =
            SchemaValidationHandler::connect(&format!("http://{addr}"), timeout, "repo-1".into())
                .await
                .unwrap();

        let start = std::time::Instant::now();
        let blobs = vec![make_blob("products/p.md", b"---\nkind: Product\n---")];
        let result = handler
            .validate(&blobs, &HookContext::default())
            .await
            .unwrap();
        let elapsed = start.elapsed();

        match result {
            AdmissionDecision::Reject(msg) => assert_eq!(msg, "validation service unavailable"),
            _ => panic!("expected Reject on timeout"),
        }
        // Must complete within 2x the timeout (150ms * 2 = 300ms)
        assert!(
            elapsed < Duration::from_millis(500),
            "timeout took too long: {elapsed:?}"
        );
    }

    // T025b: gitstore_schema_validation_total{result="timeout"} counter increments
    #[tokio::test]
    async fn test_timeout_counter_increments() {
        use crate::git::metrics::increment_schema_validation_total;

        // Calling the counter function must not panic — counter is lazily registered.
        increment_schema_validation_total("timeout");
        increment_schema_validation_total("accepted");
        increment_schema_validation_total("rejected");
        increment_schema_validation_total("service_unavailable");
        // If we get here without panicking, the counter wired correctly.
    }

    // T010d: transport error → Reject
    #[tokio::test]
    async fn test_transport_error_returns_reject() {
        // Point to a port that has no server
        let handler = SchemaValidationHandler::connect(
            "http://127.0.0.1:1",
            Duration::from_secs(2),
            "repo-1".into(),
        )
        .await
        .unwrap();

        let blobs = vec![make_blob("products/p.md", b"---\nkind: Product\n---")];
        let result = handler
            .validate(&blobs, &HookContext::default())
            .await
            .unwrap();
        assert!(
            matches!(result, AdmissionDecision::Reject(_)),
            "expected Reject on transport error"
        );
    }

    // T044: calling validate with HookContext must not panic and must return a decision.
    #[tokio::test]
    async fn test_hook_context_propagated_to_validation() {
        use super::super::HookContext;
        let handler = SchemaValidationHandler::connect(
            "http://127.0.0.1:1",
            Duration::from_millis(50),
            "repo-1".into(),
        )
        .await
        .unwrap();

        let hook_ctx = HookContext {
            actor_subject: "test-user".to_string(),
            actor_auth_method: "basic".to_string(),
            max_pack_size_bytes: 0,
            max_file_size_bytes: 0,
            config_resource_version: String::new(),
        };
        let blobs = vec![make_blob("products/p.md", b"---\nkind: Product\n---")];
        // Call with HookContext — must not panic. Server is down so we'll get a Reject.
        let result = handler.validate(&blobs, &hook_ctx).await.unwrap();
        assert!(
            matches!(result, AdmissionDecision::Reject(_)),
            "expected Reject when server is unreachable"
        );
    }
}
