package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"time"

	"github.com/gitstore-dev/gitstore/api/internal/graph/model"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.uber.org/zap"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.LoginPayload, error) {
	if r.authMiddleware == nil {
		r.logger.Error("auth middleware not configured")
		return nil, gqlerror.Errorf("authentication service unavailable")
	}

	if !r.authMiddleware.ValidateCredentials(input.Username, input.Password) {
		r.logger.Debug("invalid credentials attempt",
			zap.String("username", input.Username),
		)
		return nil, gqlerror.Errorf("invalid username or password")
	}

	token, err := r.authMiddleware.GenerateSessionToken(input.Username, true)
	if err != nil {
		r.logger.Error("failed to generate session token",
			zap.String("username", input.Username),
			zap.Error(err),
		)
		return nil, gqlerror.Errorf("internal server error")
	}

	expiresAt := time.Now().Add(r.authMiddleware.GetTokenDuration())
	return &model.LoginPayload{
		ClientMutationID: input.ClientMutationID,
		Session: &model.AuthSession{
			Token:     token,
			ExpiresAt: expiresAt,
			User: &model.User{
				Username: input.Username,
				IsAdmin:  true,
			},
		},
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, input model.LogoutInput) (*model.LogoutPayload, error) {
	return nil, gqlerror.Errorf("not implemented: Logout")
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input model.RefreshTokenInput) (*model.RefreshTokenPayload, error) {
	return nil, gqlerror.Errorf("not implemented: RefreshToken")
}
