package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"

	"github.com/gitstore-dev/gitstore/api/internal/graph/generated"
	"github.com/gitstore-dev/gitstore/api/internal/graph/model"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Products is the resolver for the products field.
func (r *categoryResolver) Products(ctx context.Context, obj *model.Category, first *int32, after *string, last *int32, before *string) (*model.ProductConnection, error) {
	_, err := decodeNodeIDAs(nodeKindCategory, obj.ID)
	if err != nil {
		return nil, err
	}
	// TODO: Add category-scoped product listing to the datastore interface.
	// For now, return all products paginated (filter by category will be added later).
	params := toPageParams(first, after, last, before)
	result, err := r.service.GetProducts(ctx, "", params)
	if err != nil {
		return nil, fmt.Errorf("failed to get products: %w", err)
	}
	return BuildProductConnection(result), nil
}

// CreateCategory is the resolver for the createCategory field.
// Category mutations are managed via git push; this stub returns an informative error.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.CreateCategoryInput) (*model.CreateCategoryPayload, error) {
	return nil, errors.New("category mutations are managed via git push")
}

// UpdateCategory is the resolver for the updateCategory field.
// Category mutations are managed via git push; this stub returns an informative error.
func (r *mutationResolver) UpdateCategory(ctx context.Context, input model.UpdateCategoryInput) (*model.UpdateCategoryPayload, error) {
	return nil, errors.New("category mutations are managed via git push")
}

// DeleteCategory is the resolver for the deleteCategory field.
// Category mutations are managed via git push; this stub returns an informative error.
func (r *mutationResolver) DeleteCategory(ctx context.Context, input model.DeleteCategoryInput) (*model.DeleteCategoryPayload, error) {
	return nil, errors.New("category mutations are managed via git push")
}

// ReorderCategories is the resolver for the reorderCategories field.
// Category mutations are managed via git push; this stub returns an informative error.
func (r *mutationResolver) ReorderCategories(ctx context.Context, input model.ReorderCategoriesInput) (*model.ReorderCategoriesPayload, error) {
	// Validate node IDs before rejecting (preserves existing validation behaviour).
	if _, err := decodeNodeIDsAs(nodeKindCategory, input.OrderedIds); err != nil {
		return nil, err
	}
	return nil, errors.New("category mutations are managed via git push")
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, by model.CategoryBy) (*model.Category, error) {
	switch {
	case by.ID != nil:
		categoryUID, err := decodeNodeIDAs(nodeKindCategory, *by.ID)
		if err != nil {
			return nil, err
		}
		c, err := r.service.GetCategoryTaxonomyByUID(ctx, categoryUID)
		if err != nil {
			return nil, nil
		}
		return DatastoreCategoryTaxonomyToGraphQL(c), nil
	case by.NamespacePath != nil:
		c, err := r.service.GetCategoryTaxonomyByName(ctx, by.NamespacePath.Namespace, by.NamespacePath.Name)
		if err != nil {
			return nil, nil
		}
		return DatastoreCategoryTaxonomyToGraphQL(c), nil
	default:
		return nil, gqlerror.Errorf("CategoryBy: exactly one selector required")
	}
}

// Categories returns categories as a Relay connection.
func (r *queryResolver) Categories(ctx context.Context, first *int32, after *string, last *int32, before *string) (*model.CategoryConnection, error) {
	ns := namespaceFromContext(ctx)
	params := toPageParams(first, after, last, before)
	result, err := r.service.GetCategoryTaxonomies(ctx, ns, params)
	if err != nil {
		return nil, fmt.Errorf("failed to get categories: %w", err)
	}
	return BuildCategoryConnection(result), nil
}

// Category returns generated.CategoryResolver implementation.
func (r *Resolver) Category() generated.CategoryResolver { return &categoryResolver{r} }

type categoryResolver struct{ *Resolver }
