package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/gitstore-dev/gitstore/api/internal/graph/generated"
	"github.com/gitstore-dev/gitstore/api/internal/graph/model"
)

// Products is the resolver for the products field.
func (r *collectionResolver) Products(ctx context.Context, obj *model.Collection, first *int32, after *string, last *int32, before *string) (*model.ProductConnection, error) {
	uid, err := decodeNodeIDAs(nodeKindCollection, obj.ID)
	if err != nil {
		return nil, err
	}
	c, err := r.service.GetCollectionByUID(ctx, uid)
	if err != nil {
		return nil, fmt.Errorf("collection not found: %w", err)
	}
	var spec struct {
		Selector *struct {
			MatchLabels      map[string]string `json:"matchLabels"`
			MatchExpressions []struct {
				Key      string   `json:"key"`
				Operator string   `json:"operator"`
				Values   []string `json:"values"`
			} `json:"matchExpressions"`
		} `json:"selector"`
	}
	if c.Spec != nil {
		if err := jsonUnmarshal(c.Spec, &spec); err == nil && spec.Selector != nil {
			selector := specSelectorToCatalog(spec.Selector)
			ns := c.Namespace
			products, err := r.service.ListProductsByLabelSelector(ctx, ns, selector)
			if err != nil {
				return nil, fmt.Errorf("failed to list collection products: %w", err)
			}
			return BuildProductConnectionFromSlice(products), nil
		}
	}
	return &model.ProductConnection{
		Edges:    []*model.ProductEdge{},
		PageInfo: &model.PageInfo{},
	}, nil
}

// CreateCollection is the resolver for the createCollection field.
func (r *mutationResolver) CreateCollection(_ context.Context, _ model.CreateCollectionInput) (*model.CreateCollectionPayload, error) {
	return nil, fmt.Errorf("createCollection is deprecated: manage collections via git push")
}

// UpdateCollection is the resolver for the updateCollection field.
func (r *mutationResolver) UpdateCollection(_ context.Context, _ model.UpdateCollectionInput) (*model.UpdateCollectionPayload, error) {
	return nil, fmt.Errorf("updateCollection is deprecated: manage collections via git push")
}

// DeleteCollection is the resolver for the deleteCollection field.
func (r *mutationResolver) DeleteCollection(_ context.Context, _ model.DeleteCollectionInput) (*model.DeleteCollectionPayload, error) {
	return nil, fmt.Errorf("deleteCollection is deprecated: manage collections via git push")
}

// Collection is the resolver for the collection field.
func (r *queryResolver) Collection(ctx context.Context, by model.CollectionBy) (*model.Collection, error) {
	if by.ID != nil {
		uid, err := decodeNodeIDAs(nodeKindCollection, *by.ID)
		if err != nil {
			return nil, err
		}
		c, err := r.service.GetCollectionByUID(ctx, uid)
		if err != nil {
			return nil, nil
		}
		return DatastoreCollectionToGraphQL(c), nil
	}
	if by.NamespacePath != nil {
		c, err := r.service.GetCollectionByName(ctx, by.NamespacePath.Namespace, by.NamespacePath.Name)
		if err != nil {
			return nil, nil
		}
		return DatastoreCollectionToGraphQL(c), nil
	}
	return nil, fmt.Errorf("collection lookup requires id or namespacePath")
}

// Collections returns collections as a Relay connection.
func (r *queryResolver) Collections(ctx context.Context, namespace string, first *int32, after *string, last *int32, before *string) (*model.CollectionConnection, error) {
	params := toPageParams(first, after, last, before)
	result, err := r.service.GetCollections(ctx, namespace, params)
	if err != nil {
		return nil, fmt.Errorf("failed to get collections: %w", err)
	}
	return BuildCollectionConnection(result), nil
}

// Collection returns generated.CollectionResolver implementation.
func (r *Resolver) Collection() generated.CollectionResolver { return &collectionResolver{r} }

type collectionResolver struct{ *Resolver }
