package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/gitstore-dev/gitstore/api/internal/graph/generated"
	"github.com/gitstore-dev/gitstore/api/internal/graph/model"
)

// Products is the resolver for the products field.
func (r *collectionResolver) Products(ctx context.Context, obj *model.Collection, first *int32, after *string, last *int32, before *string) (*model.ProductConnection, error) {
	// Get all products and filter to those belonging to this collection.
	// The datastore doesn't yet have a direct collection-filter; we fetch all
	// and filter client-side. This matches the previous behaviour.
	all, err := r.service.GetProducts(ctx, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to get products: %w", err)
	}

	// Build edges from catalog products filtered by collection ID
	edges := make([]*model.ProductEdge, 0)
	for _, p := range all {
		for _, cid := range p.CollectionIDs {
			if cid == obj.ID {
				edges = append(edges, &model.ProductEdge{
					Cursor: p.ID,
					Node:   CatalogProductToGraphQL(p),
				})
				break
			}
		}
	}

	hasNextPage := false
	hasPreviousPage := false
	var startCursor, endCursor *string
	if len(edges) > 0 {
		start := edges[0].Cursor
		end := edges[len(edges)-1].Cursor
		startCursor = &start
		endCursor = &end
	}

	return &model.ProductConnection{
		Edges:      edges,
		TotalCount: int32(len(edges)),
		PageInfo: &model.PageInfo{
			HasNextPage:     hasNextPage,
			HasPreviousPage: hasPreviousPage,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
	}, nil
}

// Collection returns generated.CollectionResolver implementation.
func (r *Resolver) Collection() generated.CollectionResolver { return &collectionResolver{r} }

type collectionResolver struct{ *Resolver }
