package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 GitStore contributors

import (
	"context"

	"github.com/gitstore-dev/gitstore/api/internal/graph/model"
	"github.com/gitstore-dev/gitstore/api/internal/middleware"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateNamespace is the resolver for the createNamespace field.
func (r *mutationResolver) CreateNamespace(ctx context.Context, input model.CreateNamespaceInput) (*model.CreateNamespacePayload, error) {
	user, ok := middleware.GetUserFromContext(ctx)
	if !ok || user == nil {
		return nil, gqlerror.Errorf("authentication required")
	}

	ns, err := r.service.CreateNamespace(ctx, input, user.Username, user.IsAdmin)
	if err != nil {
		return nil, err
	}

	return &model.CreateNamespacePayload{Namespace: datastoreNamespaceToModel(ns)}, nil
}

// DeleteNamespace is the resolver for the deleteNamespace field.
func (r *mutationResolver) DeleteNamespace(ctx context.Context, input model.DeleteNamespaceInput) (*model.DeleteNamespacePayload, error) {
	user, ok := middleware.GetUserFromContext(ctx)
	if !ok || user == nil {
		return nil, gqlerror.Errorf("authentication required")
	}

	if err := r.service.DeleteNamespace(ctx, input.Identifier, user.Username, user.IsAdmin); err != nil {
		return nil, err
	}

	return &model.DeleteNamespacePayload{DeletedIdentifier: input.Identifier}, nil
}

// Namespace is the resolver for the namespace field.
func (r *queryResolver) Namespace(ctx context.Context, identifier string) (*model.Namespace, error) {
	ns, err := r.service.GetNamespaceByIdentifier(ctx, identifier)
	if err != nil {
		return nil, err
	}
	return datastoreNamespaceToModel(ns), nil
}

// NamespaceByID is the resolver for the namespaceById field.
func (r *queryResolver) NamespaceByID(ctx context.Context, id string) (*model.Namespace, error) {
	ns, err := r.service.GetNamespaceByID(ctx, id)
	if err != nil {
		return nil, err
	}
	return datastoreNamespaceToModel(ns), nil
}

// Namespaces is the resolver for the namespaces field.
func (r *queryResolver) Namespaces(ctx context.Context) ([]*model.Namespace, error) {
	nss, err := r.service.ListNamespaces(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Namespace, len(nss))
	for i, ns := range nss {
		result[i] = datastoreNamespaceToModel(ns)
	}
	return result, nil
}
