package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/gitstore-dev/gitstore/api/internal/graph/model"
)

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, by model.ProductBy) (*model.Product, error) {
	switch {
	case by.ID != nil:
		rawID, err := decodeNodeIDAs(nodeKindProduct, *by.ID)
		if err != nil {
			return nil, nil
		}
		p, err := r.service.GetProductByUID(ctx, rawID)
		if err != nil {
			return nil, nil
		}
		return DatastoreProductToGraphQL(p), nil
	case by.NamespacePath != nil:
		p, err := r.service.GetProductByName(ctx, by.NamespacePath.Namespace, by.NamespacePath.Name)
		if err != nil {
			return nil, nil
		}
		return DatastoreProductToGraphQL(p), nil
	default:
		return nil, fmt.Errorf("ProductBy: exactly one selector required")
	}
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, namespace string, first *int32, after *string, last *int32, before *string) (*model.ProductConnection, error) {
	params := toPageParams(first, after, last, before)
	result, err := r.service.GetProducts(ctx, namespace, params)
	if err != nil {
		return nil, fmt.Errorf("failed to get products: %w", err)
	}
	return BuildProductConnection(result), nil
}
