package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"sort"

	"github.com/gitstore-dev/gitstore/api/internal/datastore"
	"github.com/gitstore-dev/gitstore/api/internal/graph/model"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.uber.org/zap"
)

// CreateRepository is the resolver for the createRepository field.
func (r *mutationResolver) CreateRepository(ctx context.Context, input model.CreateRepositoryInput) (*model.CreateRepositoryPayload, error) {
	namespaceID, err := decodeNodeIDAs(nodeKindNamespace, input.NamespaceID)
	if err != nil {
		return nil, err
	}
	defaultBranch := "main"
	if input.DefaultBranch != nil && *input.DefaultBranch != "" {
		defaultBranch = *input.DefaultBranch
	}
	repo, err := r.service.CreateRepository(ctx, namespaceID, input.Name, defaultBranch, "default", callerUsernameOrAnon(ctx, r))
	if err != nil {
		return nil, err
	}
	ns, err := r.service.GetNamespaceByID(ctx, namespaceID)
	if err != nil {
		return nil, err
	}
	r.logger.Info("lookup repository",
		zap.String("namespace_id", namespaceID),
		zap.String("name", input.Name),
		zap.String("repo_id", repo.ID),
	)
	return &model.CreateRepositoryPayload{
		ClientMutationID: input.ClientMutationID,
		Repository:       datastoreRepositoryToModel(repo, ns, r.storageDataDir),
	}, nil
}

// RenameRepository is the resolver for the renameRepository field.
func (r *mutationResolver) RenameRepository(ctx context.Context, input model.RenameRepositoryInput) (*model.RenameRepositoryPayload, error) {
	repoID, err := decodeNodeIDAs(nodeKindRepository, input.RepositoryID)
	if err != nil {
		return nil, err
	}
	repo, err := r.service.RenameRepository(ctx, repoID, input.NewName, callerUsernameOrAnon(ctx, r))
	if err != nil {
		return nil, err
	}
	ns, err := r.service.GetNamespaceByID(ctx, repo.NamespaceID)
	if err != nil {
		return nil, err
	}
	r.logger.Info("rename repository",
		zap.String("repo_id", repoID),
		zap.String("new_name", input.NewName),
	)
	return &model.RenameRepositoryPayload{
		ClientMutationID: input.ClientMutationID,
		Repository:       datastoreRepositoryToModel(repo, ns, r.storageDataDir),
	}, nil
}

// TransferRepository is the resolver for the transferRepository field.
func (r *mutationResolver) TransferRepository(ctx context.Context, input model.TransferRepositoryInput) (*model.TransferRepositoryPayload, error) {
	repoID, err := decodeNodeIDAs(nodeKindRepository, input.RepositoryID)
	if err != nil {
		return nil, err
	}
	targetNsID, err := decodeNodeIDAs(nodeKindNamespace, input.TargetNamespaceID)
	if err != nil {
		return nil, err
	}
	repo, err := r.service.TransferRepository(ctx, repoID, targetNsID, callerUsernameOrAnon(ctx, r))
	if err != nil {
		return nil, err
	}
	ns, err := r.service.GetNamespaceByID(ctx, targetNsID)
	if err != nil {
		return nil, err
	}
	r.logger.Info("transfer repository",
		zap.String("repo_id", repoID),
		zap.String("to_namespace_id", targetNsID),
	)
	return &model.TransferRepositoryPayload{
		ClientMutationID: input.ClientMutationID,
		Repository:       datastoreRepositoryToModel(repo, ns, r.storageDataDir),
	}, nil
}

// DeleteRepository is the resolver for the deleteRepository field.
func (r *mutationResolver) DeleteRepository(ctx context.Context, input model.DeleteRepositoryInput) (*model.DeleteRepositoryPayload, error) {
	repoID, err := decodeNodeIDAs(nodeKindRepository, input.RepositoryID)
	if err != nil {
		return nil, err
	}
	if err := r.service.DeleteRepository(ctx, repoID, callerUsernameOrAnon(ctx, r)); err != nil {
		return nil, err
	}
	r.logger.Info("delete repository", zap.String("repo_id", repoID))
	return &model.DeleteRepositoryPayload{
		ClientMutationID:    input.ClientMutationID,
		DeletedRepositoryID: mustEncodeNodeID(nodeKindRepository, repoID),
	}, nil
}

// Repository is the resolver for the repository field.
func (r *queryResolver) Repository(ctx context.Context, by model.RepositoryBy) (*model.Repository, error) {
	if by.ID != nil {
		repoID, err := decodeNodeIDAs(nodeKindRepository, *by.ID)
		if err != nil {
			return nil, err
		}
		repo, err := r.service.GetRepository(ctx, repoID)
		if err != nil {
			return nil, err
		}
		ns, err := r.service.GetNamespaceByID(ctx, repo.NamespaceID)
		if err != nil {
			return nil, err
		}
		r.logger.Info("lookup repository", zap.String("repo_id", repoID))
		return datastoreRepositoryToModel(repo, ns, r.storageDataDir), nil
	}
	if by.NamespacePath != nil {
		ns, err := r.service.GetNamespaceByIdentifier(ctx, by.NamespacePath.Namespace)
		if err != nil {
			return nil, err
		}
		mapping, err := r.service.LookupRepository(ctx, ns.ID, by.NamespacePath.Name)
		if err != nil {
			return nil, gqlerror.Errorf("repository not found")
		}
		repo, err := r.service.GetRepository(ctx, mapping.RepoID)
		if err != nil {
			return nil, err
		}
		r.logger.Info("lookup repository",
			zap.String("namespace_id", ns.ID),
			zap.String("name", by.NamespacePath.Name),
			zap.String("repo_id", mapping.RepoID),
		)
		return datastoreRepositoryToModel(repo, ns, r.storageDataDir), nil
	}
	return nil, gqlerror.Errorf("repository: exactly one of id or namespacePath must be provided")
}

// Repositories is the resolver for the repositories field.
func (r *queryResolver) Repositories(ctx context.Context, namespaceID string, first *int32, after *string, last *int32, before *string) (*model.RepositoryConnection, error) {
	rawNsID, err := decodeNodeIDAs(nodeKindNamespace, namespaceID)
	if err != nil {
		return nil, err
	}
	ns, err := r.service.GetNamespaceByID(ctx, rawNsID)
	if err != nil {
		return nil, err
	}
	repos, err := r.service.ListRepositoriesByNamespace(ctx, rawNsID)
	if err != nil {
		return nil, err
	}
	sort.Slice(repos, func(i, j int) bool { return repos[i].Name < repos[j].Name })
	// Sort by created_at + id for keyset pagination
	sortReposByCreatedAtThenID(repos)

	allEdges := make([]*model.RepositoryEdge, len(repos))
	for i, repo := range repos {
		allEdges[i] = &model.RepositoryEdge{
			Cursor: EncodeKeysetCursor(repo.CreatedAt, repo.ID),
			Node:   datastoreRepositoryToModel(repo, ns, r.storageDataDir),
		}
	}
	start, end, hasNextPage, hasPreviousPage := applyKeysetWindow(len(allEdges), first, after, last, before, func(i int) string {
		repo := repos[i]
		return EncodeKeysetCursor(repo.CreatedAt, repo.ID)
	})
	edges := allEdges[start:end]
	var startCursor, endCursor *string
	if len(edges) > 0 {
		s := edges[0].Cursor
		e := edges[len(edges)-1].Cursor
		startCursor = &s
		endCursor = &e
	}
	return &model.RepositoryConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage:     hasNextPage,
			HasPreviousPage: hasPreviousPage,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
	}, nil
}

// callerUsernameOrAnon returns the authenticated user's username or "anon".
func callerUsernameOrAnon(ctx context.Context, r *mutationResolver) string {
	if r.authMiddleware == nil {
		return "anon"
	}
	return "anon"
}

// sortReposByCreatedAtThenID sorts repositories by created_at ascending, then by id as tie-breaker
func sortReposByCreatedAtThenID(repos []*datastore.Repository) {
	for i := 0; i < len(repos); i++ {
		for j := i + 1; j < len(repos); j++ {
			ri, rj := repos[i], repos[j]
			cmpTime := ri.CreatedAt.Compare(rj.CreatedAt)
			if cmpTime > 0 || (cmpTime == 0 && ri.ID > rj.ID) {
				repos[i], repos[j] = repos[j], repos[i]
			}
		}
	}
}
