package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"

	"github.com/gitstore-dev/gitstore/api/internal/graph/generated"
	"github.com/gitstore-dev/gitstore/api/internal/graph/model"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.CreateProductPayload, error) {
	categoryID, err := decodeNodeIDAs(nodeKindCategory, input.CategoryID)
	if err != nil {
		return nil, err
	}
	collectionIDs, err := decodeNodeIDsAs(nodeKindCollection, input.CollectionIds)
	if err != nil {
		return nil, err
	}

	// Build input map for service
	priceFloat, _ := input.Price.Float64()
	serviceInput := map[string]interface{}{
		"title":      input.Title,
		"sku":        input.Sku,
		"price":      priceFloat,
		"categoryId": categoryID,
	}

	if input.Currency != nil {
		serviceInput["currency"] = *input.Currency
	}
	if input.Body != nil {
		serviceInput["body"] = *input.Body
	}
	if input.InventoryStatus != nil {
		serviceInput["inventoryStatus"] = string(*input.InventoryStatus)
	}
	if input.InventoryQuantity != nil {
		serviceInput["inventoryQuantity"] = int(*input.InventoryQuantity)
	}
	if len(input.CollectionIds) > 0 {
		serviceInput["collectionIds"] = collectionIDs
	}
	if len(input.Images) > 0 {
		serviceInput["images"] = input.Images
	}
	if input.Metadata != nil {
		serviceInput["metadata"] = input.Metadata
	}

	// Create product via service
	catalogProduct, err := r.service.CreateProduct(ctx, serviceInput)
	if err != nil {
		return nil, fmt.Errorf("failed to create product: %w", err)
	}

	// Convert to GraphQL model
	product := CatalogProductToGraphQL(catalogProduct)

	return &model.CreateProductPayload{
		ClientMutationID: input.ClientMutationID,
		Product:          product,
	}, nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, input model.UpdateProductInput) (*model.UpdateProductPayload, error) {
	productID, err := decodeNodeIDAs(nodeKindProduct, input.ID)
	if err != nil {
		return nil, err
	}
	categoryID, err := decodeOptionalNodeIDAs(nodeKindCategory, input.CategoryID)
	if err != nil {
		return nil, err
	}
	collectionIDs, err := decodeNodeIDsAs(nodeKindCollection, input.CollectionIds)
	if err != nil {
		return nil, err
	}

	// Build input map for service
	serviceInput := map[string]interface{}{}

	if input.Title != nil {
		serviceInput["title"] = *input.Title
	}
	if input.Sku != nil {
		serviceInput["sku"] = *input.Sku
	}
	if input.Price != nil {
		priceFloat, _ := input.Price.Float64()
		serviceInput["price"] = priceFloat
	}
	if input.Currency != nil {
		serviceInput["currency"] = *input.Currency
	}
	if input.Body != nil {
		serviceInput["body"] = *input.Body
	}
	if input.InventoryStatus != nil {
		serviceInput["inventoryStatus"] = string(*input.InventoryStatus)
	}
	if input.InventoryQuantity != nil {
		serviceInput["inventoryQuantity"] = int(*input.InventoryQuantity)
	}
	if input.CategoryID != nil {
		serviceInput["categoryId"] = *categoryID
	}
	if len(input.CollectionIds) > 0 {
		serviceInput["collectionIds"] = collectionIDs
	}
	if len(input.Images) > 0 {
		serviceInput["images"] = input.Images
	}
	if input.Metadata != nil {
		serviceInput["metadata"] = input.Metadata
	}

	// Update product via service
	catalogProduct, err := r.service.UpdateProduct(ctx, productID, serviceInput)
	if err != nil {
		return nil, fmt.Errorf("failed to update product: %w", err)
	}

	// Convert to GraphQL model
	product := CatalogProductToGraphQL(catalogProduct)

	return &model.UpdateProductPayload{
		ClientMutationID: input.ClientMutationID,
		Product:          product,
		Conflict:         nil, // TODO: Implement optimistic locking
	}, nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, input model.DeleteProductInput) (*model.DeleteProductPayload, error) {
	productID, err := decodeNodeIDAs(nodeKindProduct, input.ID)
	if err != nil {
		return nil, err
	}

	// Delete product via service
	err = r.service.DeleteProduct(ctx, productID)
	if err != nil {
		return nil, fmt.Errorf("failed to delete product: %w", err)
	}

	idCopy := mustEncodeNodeID(nodeKindProduct, productID)
	return &model.DeleteProductPayload{
		ClientMutationID: input.ClientMutationID,
		DeletedProductID: &idCopy,
	}, nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.CreateCategoryInput) (*model.CreateCategoryPayload, error) {
	if _, err := decodeOptionalNodeIDAs(nodeKindCategory, input.ParentID); err != nil {
		return nil, err
	}
	rawID := generateID()

	// TODO: Implement proper git-backed category creation
	// For now, return mock response to unblock E2E tests
	category := &model.Category{
		ID:           mustEncodeNodeID(nodeKindCategory, rawID),
		Name:         input.Name,
		Slug:         input.Slug,
		Body:         input.Body,
		Parent:       nil, // TODO: lookup parent
		Children:     []*model.Category{},
		DisplayOrder: intOrDefault(input.DisplayOrder, 0),
		Products:     &model.ProductConnection{Edges: []*model.ProductEdge{}, PageInfo: &model.PageInfo{}},
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	}

	return &model.CreateCategoryPayload{
		ClientMutationID: input.ClientMutationID,
		Category:         category,
	}, nil
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, input model.UpdateCategoryInput) (*model.UpdateCategoryPayload, error) {
	categoryID, err := decodeNodeIDAs(nodeKindCategory, input.ID)
	if err != nil {
		return nil, err
	}
	if _, err := decodeOptionalNodeIDAs(nodeKindCategory, input.ParentID); err != nil {
		return nil, err
	}

	// TODO: Implement proper git-backed category update
	// For now, return mock response to unblock E2E tests
	category := &model.Category{
		ID:           mustEncodeNodeID(nodeKindCategory, categoryID),
		Name:         stringOrDefault(input.Name, "Updated Category"),
		Slug:         stringOrDefault(input.Slug, "updated-category"),
		Body:         input.Body,
		Parent:       nil, // TODO: lookup parent
		Children:     []*model.Category{},
		DisplayOrder: intOrDefault(input.DisplayOrder, 0),
		Products:     &model.ProductConnection{Edges: []*model.ProductEdge{}, PageInfo: &model.PageInfo{}},
		CreatedAt:    time.Now().Add(-24 * time.Hour),
		UpdatedAt:    time.Now(),
	}

	return &model.UpdateCategoryPayload{
		ClientMutationID: input.ClientMutationID,
		Category:         category,
		Conflict:         nil,
	}, nil
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, input model.DeleteCategoryInput) (*model.DeleteCategoryPayload, error) {
	categoryID, err := decodeNodeIDAs(nodeKindCategory, input.ID)
	if err != nil {
		return nil, err
	}

	// TODO: Implement proper git-backed category deletion
	// For now, return mock response to unblock E2E tests
	idCopy := mustEncodeNodeID(nodeKindCategory, categoryID)
	return &model.DeleteCategoryPayload{
		ClientMutationID:  input.ClientMutationID,
		DeletedCategoryID: &idCopy,
	}, nil
}

// ReorderCategories is the resolver for the reorderCategories field.
func (r *mutationResolver) ReorderCategories(ctx context.Context, input model.ReorderCategoriesInput) (*model.ReorderCategoriesPayload, error) {
	orderedIDs, err := decodeNodeIDsAs(nodeKindCategory, input.OrderedIds)
	if err != nil {
		return nil, err
	}
	if _, err := decodeOptionalNodeIDAs(nodeKindCategory, input.ParentID); err != nil {
		return nil, err
	}
	if _, err := decodeOptionalNodeIDAs(nodeKindCategory, input.MovedCategoryID); err != nil {
		return nil, err
	}
	if _, err := decodeOptionalNodeIDAs(nodeKindCategory, input.NewParentID); err != nil {
		return nil, err
	}

	// TODO: Implement proper git-backed category reordering
	// For now, return mock response with updated display orders
	categories := make([]*model.Category, len(orderedIDs))
	for i, id := range orderedIDs {
		categories[i] = &model.Category{
			ID:           mustEncodeNodeID(nodeKindCategory, id),
			Name:         fmt.Sprintf("Category %d", i+1),
			Slug:         fmt.Sprintf("category-%d", i+1),
			DisplayOrder: int32(i),
			Children:     []*model.Category{},
			Products:     &model.ProductConnection{Edges: []*model.ProductEdge{}, PageInfo: &model.PageInfo{}},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		}
	}

	return &model.ReorderCategoriesPayload{
		ClientMutationID: input.ClientMutationID,
		Categories:       categories,
	}, nil
}

// CreateCollection is the resolver for the createCollection field.
func (r *mutationResolver) CreateCollection(ctx context.Context, input model.CreateCollectionInput) (*model.CreateCollectionPayload, error) {
	if _, err := decodeNodeIDsAs(nodeKindProduct, input.ProductIds); err != nil {
		return nil, err
	}
	rawID := generateID()

	collection := &model.Collection{
		ID:           mustEncodeNodeID(nodeKindCollection, rawID),
		Name:         input.Name,
		Slug:         input.Slug,
		Body:         input.Body,
		DisplayOrder: intOrDefault(input.DisplayOrder, 0),
		Products:     &model.ProductConnection{Edges: []*model.ProductEdge{}, PageInfo: &model.PageInfo{}},
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	}
	return &model.CreateCollectionPayload{
		ClientMutationID: input.ClientMutationID,
		Collection:       collection,
	}, nil
}

// UpdateCollection is the resolver for the updateCollection field.
func (r *mutationResolver) UpdateCollection(ctx context.Context, input model.UpdateCollectionInput) (*model.UpdateCollectionPayload, error) {
	collectionID, err := decodeNodeIDAs(nodeKindCollection, input.ID)
	if err != nil {
		return nil, err
	}
	if _, err := decodeNodeIDsAs(nodeKindProduct, input.ProductIds); err != nil {
		return nil, err
	}

	collection := &model.Collection{
		ID:           mustEncodeNodeID(nodeKindCollection, collectionID),
		Name:         stringOrDefault(input.Name, "Updated Collection"),
		Slug:         stringOrDefault(input.Slug, "updated-collection"),
		Body:         input.Body,
		DisplayOrder: intOrDefault(input.DisplayOrder, 0),
		Products:     &model.ProductConnection{Edges: []*model.ProductEdge{}, PageInfo: &model.PageInfo{}},
		CreatedAt:    time.Now().Add(-24 * time.Hour),
		UpdatedAt:    time.Now(),
	}
	return &model.UpdateCollectionPayload{
		ClientMutationID: input.ClientMutationID,
		Collection:       collection,
		Conflict:         nil,
	}, nil
}

// DeleteCollection is the resolver for the deleteCollection field.
func (r *mutationResolver) DeleteCollection(ctx context.Context, input model.DeleteCollectionInput) (*model.DeleteCollectionPayload, error) {
	collectionID, err := decodeNodeIDAs(nodeKindCollection, input.ID)
	if err != nil {
		return nil, err
	}
	idCopy := mustEncodeNodeID(nodeKindCollection, collectionID)
	return &model.DeleteCollectionPayload{
		ClientMutationID:    input.ClientMutationID,
		DeletedCollectionID: &idCopy,
	}, nil
}

// ReorderCollections is the resolver for the reorderCollections field.
func (r *mutationResolver) ReorderCollections(ctx context.Context, input model.ReorderCollectionsInput) (*model.ReorderCollectionsPayload, error) {
	orderedIDs, err := decodeNodeIDsAs(nodeKindCollection, input.OrderedIds)
	if err != nil {
		return nil, err
	}

	collections := make([]*model.Collection, len(orderedIDs))
	for i, id := range orderedIDs {
		collections[i] = &model.Collection{
			ID:           mustEncodeNodeID(nodeKindCollection, id),
			Name:         fmt.Sprintf("Collection %d", i+1),
			Slug:         fmt.Sprintf("collection-%d", i+1),
			DisplayOrder: int32(i),
			Products:     &model.ProductConnection{Edges: []*model.ProductEdge{}, PageInfo: &model.PageInfo{}},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		}
	}
	return &model.ReorderCollectionsPayload{
		ClientMutationID: input.ClientMutationID,
		Collections:      collections,
	}, nil
}

// PublishCatalog is the resolver for the publishCatalog field.
func (r *mutationResolver) PublishCatalog(ctx context.Context, input model.PublishCatalogInput) (*model.PublishCatalogPayload, error) {
	message := input.Message
	if message == "" {
		message = "Published catalog"
	}

	stats := r.getCatalogStats(ctx)

	version := &model.CatalogVersion{
		Tag:         input.Version,
		Commit:      "abc123def456", // TODO: resolve actual commit from git push result
		PublishedAt: time.Now(),
		Message:     &message,
		Stats:       stats,
	}
	return &model.PublishCatalogPayload{
		ClientMutationID: input.ClientMutationID,
		CatalogVersion:   version,
	}, nil
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (model.Node, error) {
	kind, rawID, err := DecodeNodeID(id)
	if err != nil {
		return nil, invalidGlobalIDError(err)
	}
	return r.resolveNode(ctx, kind, rawID)
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []string) ([]model.Node, error) {
	nodes := make([]model.Node, len(ids))
	for i, id := range ids {
		kind, rawID, err := DecodeNodeID(id)
		if err != nil {
			continue
		}
		node, err := r.resolveNode(ctx, kind, rawID)
		if err != nil {
			continue
		}
		nodes[i] = node
	}
	return nodes, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, by model.ProductBy) (*model.Product, error) {
	if by.ID != nil {
		productID, err := decodeNodeIDAs(nodeKindProduct, *by.ID)
		if err != nil {
			return nil, err
		}
		catalogProduct, err := r.service.GetProductByID(ctx, productID)
		if err != nil {
			return nil, nil // Return nil instead of error for not found
		}
		return CatalogProductToGraphQL(catalogProduct), nil
	}

	catalogProduct, err := r.service.GetProductBySKU(ctx, *by.Sku)
	if err != nil {
		return nil, nil // Return nil instead of error for not found
	}
	return CatalogProductToGraphQL(catalogProduct), nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, first *int32, after *string, last *int32, before *string, filter *model.ProductFilter) (*model.ProductConnection, error) {
	// Get category filter if specified
	var categoryID *string
	if filter != nil {
		var err error
		categoryID, err = decodeOptionalNodeIDAs(nodeKindCategory, filter.CategoryID)
		if err != nil {
			return nil, err
		}
		filter = copyProductFilter(filter)
		filter.CategoryID = categoryID
		filter.CollectionID, err = decodeOptionalNodeIDAs(nodeKindCollection, filter.CollectionID)
		if err != nil {
			return nil, err
		}
	}

	// Get products from service
	products, err := r.service.GetProducts(ctx, categoryID)
	if err != nil {
		return nil, fmt.Errorf("failed to get products: %w", err)
	}

	// Apply additional filters
	if filter != nil {
		products = applyProductFilters(products, filter)
	}

	// Apply Relay-style cursor pagination
	return PaginateProducts(products, first, after, last, before)
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, by model.CategoryBy) (*model.Category, error) {
	if by.ID != nil {
		categoryID, err := decodeNodeIDAs(nodeKindCategory, *by.ID)
		if err != nil {
			return nil, err
		}
		catalogCategory, err := r.service.GetCategoryByID(ctx, categoryID)
		if err != nil {
			return nil, nil // Return nil for not found (not an error)
		}
		return CatalogCategoryToGraphQL(catalogCategory), nil
	}

	catalogCategory, err := r.service.GetCategoryBySlug(ctx, *by.Slug)
	if err != nil {
		return nil, nil // Return nil for not found (not an error)
	}
	return CatalogCategoryToGraphQL(catalogCategory), nil
}

// Categories returns categories as a Relay connection.
func (r *queryResolver) Categories(ctx context.Context, first *int32, after *string, last *int32, before *string) (*model.CategoryConnection, error) {
	catalogCategories, err := r.service.GetCategories(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get categories: %w", err)
	}

	return PaginateCategories(catalogCategories, first, after, last, before)
}

// Collection is the resolver for the collection field.
func (r *queryResolver) Collection(ctx context.Context, by model.CollectionBy) (*model.Collection, error) {
	if by.ID != nil {
		collectionID, err := decodeNodeIDAs(nodeKindCollection, *by.ID)
		if err != nil {
			return nil, err
		}
		catalogCollection, err := r.service.GetCollectionByID(ctx, collectionID)
		if err != nil {
			return nil, nil // Return nil for not found
		}
		return CatalogCollectionToGraphQL(catalogCollection), nil
	}

	catalogCollection, err := r.service.GetCollectionBySlug(ctx, *by.Slug)
	if err != nil {
		return nil, nil // Return nil for not found
	}
	return CatalogCollectionToGraphQL(catalogCollection), nil
}

// Collections returns collections as a Relay connection.
func (r *queryResolver) Collections(ctx context.Context, first *int32, after *string, last *int32, before *string) (*model.CollectionConnection, error) {
	catalogCollections, err := r.service.GetCollections(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get collections: %w", err)
	}

	return PaginateCollections(catalogCollections, first, after, last, before)
}

// CatalogVersion is the resolver for the catalogVersion field.
func (r *queryResolver) CatalogVersion(ctx context.Context) (*model.CatalogVersion, error) {
	stats := r.getCatalogStats(ctx)
	return &model.CatalogVersion{
		Tag:         "",
		Commit:      "",
		PublishedAt: time.Now(),
		Message:     nil,
		Stats:       stats,
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
