package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"time"

	"github.com/gitstore-dev/gitstore/api/internal/graph/generated"
	"github.com/gitstore-dev/gitstore/api/internal/graph/model"
)

// PublishCatalog is the resolver for the publishCatalog field.
func (r *mutationResolver) PublishCatalog(ctx context.Context, input model.PublishCatalogInput) (*model.PublishCatalogPayload, error) {
	message := input.Message
	if message == "" {
		message = "Published catalog"
	}

	stats := r.getCatalogStats(ctx)

	version := &model.CatalogVersion{
		Tag:         input.Version,
		Commit:      "abc123def456", // TODO: resolve actual commit from git push result
		PublishedAt: time.Now(),
		Message:     &message,
		Stats:       stats,
	}
	return &model.PublishCatalogPayload{
		ClientMutationID: input.ClientMutationID,
		CatalogVersion:   version,
	}, nil
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (model.Node, error) {
	kind, rawID, err := DecodeNodeID(id)
	if err != nil {
		return nil, invalidGlobalIDError(err)
	}
	return r.resolveNode(ctx, kind, rawID)
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []string) ([]model.Node, error) {
	nodes := make([]model.Node, len(ids))
	for i, id := range ids {
		kind, rawID, err := DecodeNodeID(id)
		if err != nil {
			continue
		}
		node, err := r.resolveNode(ctx, kind, rawID)
		if err != nil {
			continue
		}
		nodes[i] = node
	}
	return nodes, nil
}

// CatalogVersion is the resolver for the catalogVersion field.
func (r *queryResolver) CatalogVersion(ctx context.Context) (*model.CatalogVersion, error) {
	stats := r.getCatalogStats(ctx)
	return &model.CatalogVersion{
		Tag:         "",
		Commit:      "",
		PublishedAt: time.Now(),
		Message:     nil,
		Stats:       stats,
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
